"""Auto-generated by scripts/split_gl13_5.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_imperatives_{1,2}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

IMPERATIVES_HABLAR_COMER_INTRO = {
    "kind": "cards",
    "title": "Imperatives — hablar + comer (regular tú)",
    "cards": [
        {
            "kind": "text",
            "title": "hablar + comer (regular tú)",
            "body": "**Affirmative imperative** = command form. For regular -ar verbs, the **tú** command swaps -ar → -a (habla = speak!). For -er/-ir, swap to -e (come = eat!).",
        },
        {
            "kind": "text",
            "title": "Beyond tú",
            "body": "Other commands (usted, nosotros, ustedes) use the subjunctive stem: hable, hablemos, hablen. We'll cover those alongside tú so you see the whole picture.",
        },
        {
            "kind": "mini_table",
            "title": "hablar (to speak)",
            "rows": [
            ["tú", "habl|a"],
            ["usted", "habl|e"],
            ["nosotros", "habl|emos"],
            ["ustedes", "habl|en"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "comer (to eat)",
            "rows": [
            ["tú", "com|e"],
            ["usted", "com|a"],
            ["nosotros", "com|amos"],
            ["ustedes", "com|an"],
            ],
        },
    ],
    "recall": [
        {"verb": "hablar", "answers": {"tú": "habl|a", "usted": "habl|e", "nosotros": "habl|emos", "ustedes": "habl|en"}},
        {"verb": "comer", "answers": {"tú": "com|e", "usted": "com|a", "nosotros": "com|amos", "ustedes": "com|an"}},
    ],
}

IMPERATIVES_TENER_VENIR_INTRO = {
    "kind": "cards",
    "title": "Imperatives — tener + venir (irregular tú)",
    "cards": [
        {
            "kind": "text",
            "title": "tener + venir (irregular tú)",
            "body": "Eight common verbs have **short irregular tú commands**: di, haz, ve, pon, sal, sé, ten, ven. Here we drill **ten** (have!) and **ven** (come!).",
        },
        {
            "kind": "text",
            "title": "Beyond tú",
            "body": "Outside tú, these verbs use the regular subjunctive stem: tenga, tengamos, tengan / venga, vengamos, vengan. The yo-go pattern shows up here too (tengo → tenga).",
        },
        {
            "kind": "mini_table",
            "title": "tener (to have)",
            "rows": [
            ["tú", "|ten"],
            ["usted", "ten|ga"],
            ["nosotros", "ten|gamos"],
            ["ustedes", "ten|gan"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "venir (to come)",
            "rows": [
            ["tú", "|ven"],
            ["usted", "ven|ga"],
            ["nosotros", "ven|gamos"],
            ["ustedes", "ven|gan"],
            ],
        },
    ],
    "recall": [
        {"verb": "tener", "answers": {"tú": "|ten", "usted": "ten|ga", "nosotros": "ten|gamos", "ustedes": "ten|gan"}},
        {"verb": "venir", "answers": {"tú": "|ven", "usted": "ven|ga", "nosotros": "ven|gamos", "ustedes": "ven|gan"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_imperatives_hablar_comer_1": {
        "title": "Imperatives — hablar + comer (regular tú) (1/2)",
        "grammar_level": 13.5,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "imperative",
        "intro_chart": IMPERATIVES_HABLAR_COMER_INTRO,
        "rule_chart": IMPERATIVES_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"tú": "habl|a", "usted": "habl|e", "nosotros": "habl|emos", "ustedes": "habl|en"},
                "comer": {"tú": "com|e", "usted": "com|a", "nosotros": "com|amos", "ustedes": "com|an"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "Speak clearly.", "es": "Habla claramente.", "noun_id": None, "type": "written", "glosses": {"clearly": "claramente", "claramente": "clearly"}},
            {"en": "Speak slowly, please.", "es": "Hable despacio, por favor.", "noun_id": None, "type": "auditory", "glosses": {"slowly": "despacio", "despacio": "slowly"}},
            {"en": "Let's speak Spanish.", "es": "Hablemos español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "Speak, you all.", "es": "Hablen.", "noun_id": None, "type": "auditory", "glosses": {}},
            {"en": "Speak louder.", "es": "Habla más fuerte.", "noun_id": None, "type": "written", "glosses": {"louder": "más fuerte", "más fuerte": "louder"}},
            {"en": "Eat the fruit.", "es": "Come la fruta.", "noun_id": None, "type": "written", "glosses": {"fruit": "fruta", "fruta": "fruit"}},
            {"en": "Eat slowly, please.", "es": "Coma despacio, por favor.", "noun_id": None, "type": "auditory", "glosses": {"slowly": "despacio", "despacio": "slowly"}},
            {"en": "Let's eat together.", "es": "Comamos juntos.", "noun_id": None, "type": "written", "glosses": {"together": "juntos", "juntos": "together"}},
            {"en": "Eat, you all.", "es": "Coman.", "noun_id": None, "type": "auditory", "glosses": {}},
            {"en": "Eat now.", "es": "Come ahora.", "noun_id": None, "type": "written", "glosses": {"now": "ahora", "ahora": "now"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "usted"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "usted"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "tú"}],
        "phase_2_config": {
            "description": "Imperatives hablar + comer (regular tú) (1/2): hablar, comer",
            "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "usted"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "usted"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "tú"}],
        },
        "opener_en": "Speak slowly, please.",
        "opener_es": "Habla despacio, por favor.",
    },

    "grammar_imperatives_hablar_comer_2": {
        "title": "Imperatives — hablar + comer (regular tú) (2/2)",
        "grammar_level": 13.5,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "imperative",
        "rule_chart": IMPERATIVES_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"tú": "habl|a", "usted": "habl|e", "nosotros": "habl|emos", "ustedes": "habl|en"},
                "comer": {"tú": "com|e", "usted": "com|a", "nosotros": "com|amos", "ustedes": "com|an"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "Speak slowly, please.", "es": "Hable despacio, por favor.", "noun_id": None, "type": "written", "glosses": {"slowly": "despacio", "despacio": "slowly"}},
            {"en": "Speak Spanish!", "es": "Habla español!", "noun_id": None, "type": "auditory", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "Speak louder, you all.", "es": "Hablen más alto, ustedes.", "noun_id": None, "type": "written", "glosses": {"louder": "alto", "alto": "louder"}},
            {"en": "Let's speak about the movie.", "es": "Hablemos sobre la película.", "noun_id": None, "type": "auditory", "glosses": {"movie": "película", "película": "movie"}},
            {"en": "Speak clearly.", "es": "Hable claramente.", "noun_id": None, "type": "written", "glosses": {"clearly": "claramente", "claramente": "clearly"}},
            {"en": "Eat the fruit, please.", "es": "Coma la fruta, por favor.", "noun_id": None, "type": "written", "glosses": {"fruit": "fruta", "fruta": "fruit"}},
            {"en": "Eat now!", "es": "Come ahora!", "noun_id": None, "type": "auditory", "glosses": {"now": "ahora", "ahora": "now"}},
            {"en": "Eat all the vegetables, you all.", "es": "Coman todas las verduras, ustedes.", "noun_id": None, "type": "written", "glosses": {"vegetables": "verduras", "all": "todas", "verduras": "vegetables", "todas": "all"}},
            {"en": "Let's eat together.", "es": "Comamos juntos.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntos", "juntos": "together"}},
            {"en": "Eat the bread.", "es": "Coma el pan.", "noun_id": None, "type": "written", "glosses": {"bread": "pan", "pan": "bread"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "usted"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "usted"}, {"verb": "comer", "pronoun": "usted"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "usted"}],
        "phase_2_config": {
            "description": "Imperatives hablar + comer (regular tú) (2/2): hablar, comer",
            "targets": [{"verb": "hablar", "pronoun": "usted"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "usted"}, {"verb": "comer", "pronoun": "usted"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "usted"}],
        },
        "opener_en": "Eat the bread now.",
        "opener_es": "Come el pan ahora.",
    },

    "grammar_imperatives_tener_venir_1": {
        "title": "Imperatives — tener + venir (irregular tú) (1/2)",
        "grammar_level": 13.5,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["tener", "venir"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "imperative",
        "intro_chart": IMPERATIVES_TENER_VENIR_INTRO,
        "rule_chart": IMPERATIVES_RULE,
        "drill_config": {
            "answers": {
                "tener": {"tú": "|ten", "usted": "ten|ga", "nosotros": "ten|gamos", "ustedes": "ten|gan"},
                "venir": {"tú": "|ven", "usted": "ven|ga", "nosotros": "ven|gamos", "ustedes": "ven|gan"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "Have patience.", "es": "Ten paciencia.", "noun_id": None, "type": "written", "glosses": {"patience": "paciencia", "paciencia": "patience"}},
            {"en": "Have a seat, please.", "es": "Tenga un asiento, por favor.", "noun_id": None, "type": "auditory", "glosses": {"seat": "asiento", "asiento": "seat"}},
            {"en": "Let's have fun.", "es": "Tengamos diversión.", "noun_id": None, "type": "written", "glosses": {"fun": "diversión", "diversión": "fun"}},
            {"en": "Have the tickets ready.", "es": "Tengan los boletos listos.", "noun_id": None, "type": "auditory", "glosses": {"tickets": "boletos", "boletos": "tickets"}},
            {"en": "Have courage.", "es": "Ten valor.", "noun_id": None, "type": "written", "glosses": {"courage": "valor", "valor": "courage"}},
            {"en": "Come quickly.", "es": "Ven rápido.", "noun_id": None, "type": "written", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
            {"en": "Come inside, please.", "es": "Venga adentro, por favor.", "noun_id": None, "type": "auditory", "glosses": {"inside": "adentro", "adentro": "inside"}},
            {"en": "Let's come early.", "es": "Vengamos temprano.", "noun_id": None, "type": "written", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "Come to the party.", "es": "Vengan a la fiesta.", "noun_id": None, "type": "auditory", "glosses": {"party": "fiesta", "fiesta": "party"}},
            {"en": "Come here.", "es": "Ven aquí.", "noun_id": None, "type": "written", "glosses": {"here": "aquí", "aquí": "here"}},
        ],
        "drill_targets": [{"verb": "tener", "pronoun": "tú"}, {"verb": "tener", "pronoun": "usted"}, {"verb": "tener", "pronoun": "nosotros"}, {"verb": "tener", "pronoun": "ustedes"}, {"verb": "tener", "pronoun": "tú"}, {"verb": "venir", "pronoun": "tú"}, {"verb": "venir", "pronoun": "usted"}, {"verb": "venir", "pronoun": "nosotros"}, {"verb": "venir", "pronoun": "ustedes"}, {"verb": "venir", "pronoun": "tú"}],
        "phase_2_config": {
            "description": "Imperatives tener + venir (irregular tú) (1/2): tener, venir",
            "targets": [{"verb": "tener", "pronoun": "tú"}, {"verb": "tener", "pronoun": "usted"}, {"verb": "tener", "pronoun": "nosotros"}, {"verb": "tener", "pronoun": "ustedes"}, {"verb": "tener", "pronoun": "tú"}, {"verb": "venir", "pronoun": "tú"}, {"verb": "venir", "pronoun": "usted"}, {"verb": "venir", "pronoun": "nosotros"}, {"verb": "venir", "pronoun": "ustedes"}, {"verb": "venir", "pronoun": "tú"}],
        },
        "opener_en": "Have patience, please.",
        "opener_es": "Ten paciencia, por favor.",
    },

    "grammar_imperatives_tener_venir_2": {
        "title": "Imperatives — tener + venir (irregular tú) (2/2)",
        "grammar_level": 13.5,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["tener", "venir"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "imperative",
        "rule_chart": IMPERATIVES_RULE,
        "drill_config": {
            "answers": {
                "tener": {"tú": "|ten", "usted": "ten|ga", "nosotros": "ten|gamos", "ustedes": "ten|gan"},
                "venir": {"tú": "|ven", "usted": "ven|ga", "nosotros": "ven|gamos", "ustedes": "ven|gan"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "Have patience, please.", "es": "Tenga paciencia, por favor.", "noun_id": None, "type": "written", "glosses": {"patience": "paciencia", "paciencia": "patience"}},
            {"en": "Have a good day.", "es": "Ten un buen día.", "noun_id": None, "type": "auditory", "glosses": {"day": "día", "good": "buen", "buen": "good", "día": "day"}},
            {"en": "Have your books ready.", "es": "Tengan sus libros listos.", "noun_id": None, "type": "written", "glosses": {"books": "libros", "libros": "books", "ready": "listos", "listos": "ready"}},
            {"en": "Let's have fun today.", "es": "Tengamos diversión hoy.", "noun_id": None, "type": "auditory", "glosses": {"fun": "diversión", "diversión": "fun", "today": "hoy", "hoy": "today"}},
            {"en": "Have courage now.", "es": "Tenga valor ahora.", "noun_id": None, "type": "written", "glosses": {"courage": "valor", "valor": "courage", "now": "ahora", "ahora": "now"}},
            {"en": "Come early, please.", "es": "Venga temprano, por favor.", "noun_id": None, "type": "written", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "Come here.", "es": "Ven aquí.", "noun_id": None, "type": "auditory", "glosses": {"here": "aquí", "aquí": "here"}},
            {"en": "Come with us, you all.", "es": "Vengan con nosotros.", "noun_id": None, "type": "written", "glosses": {"us": "nosotros", "nosotros": "us"}},
            {"en": "Let's come together.", "es": "Vengamos juntos.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntos", "juntos": "together"}},
            {"en": "Come quickly, please.", "es": "Venga rápido, por favor.", "noun_id": None, "type": "written", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
        ],
        "drill_targets": [{"verb": "tener", "pronoun": "usted"}, {"verb": "tener", "pronoun": "tú"}, {"verb": "tener", "pronoun": "ustedes"}, {"verb": "tener", "pronoun": "nosotros"}, {"verb": "tener", "pronoun": "usted"}, {"verb": "venir", "pronoun": "usted"}, {"verb": "venir", "pronoun": "tú"}, {"verb": "venir", "pronoun": "ustedes"}, {"verb": "venir", "pronoun": "nosotros"}, {"verb": "venir", "pronoun": "usted"}],
        "phase_2_config": {
            "description": "Imperatives tener + venir (irregular tú) (2/2): tener, venir",
            "targets": [{"verb": "tener", "pronoun": "usted"}, {"verb": "tener", "pronoun": "tú"}, {"verb": "tener", "pronoun": "ustedes"}, {"verb": "tener", "pronoun": "nosotros"}, {"verb": "tener", "pronoun": "usted"}, {"verb": "venir", "pronoun": "usted"}, {"verb": "venir", "pronoun": "tú"}, {"verb": "venir", "pronoun": "ustedes"}, {"verb": "venir", "pronoun": "nosotros"}, {"verb": "venir", "pronoun": "usted"}],
        },
        "opener_en": "Come here right now.",
        "opener_es": "Ven aquí ahora mismo.",
    },

    "grammar_imperatives_hablar_comer_chat": {
        "title": "Imperatives — hablar + comer (regular tú) Chat",
        "grammar_level": 13.5,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "imperative",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Imperatives hablar + comer (regular tú) chat: hablar, comer", "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "usted"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "comer", "pronoun": "usted"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "usted"}]},
    },

    "grammar_imperatives_tener_venir_chat": {
        "title": "Imperatives — tener + venir (irregular tú) Chat",
        "grammar_level": 13.5,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["tener", "venir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "imperative",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Imperatives tener + venir (irregular tú) chat: tener, venir", "targets": [{"verb": "tener", "pronoun": "tú"}, {"verb": "tener", "pronoun": "usted"}, {"verb": "tener", "pronoun": "nosotros"}, {"verb": "tener", "pronoun": "ustedes"}, {"verb": "tener", "pronoun": "tú"}, {"verb": "venir", "pronoun": "usted"}, {"verb": "venir", "pronoun": "tú"}, {"verb": "venir", "pronoun": "ustedes"}, {"verb": "venir", "pronoun": "nosotros"}, {"verb": "venir", "pronoun": "usted"}]},
    },
