"""Auto-generated by scripts/split_gl17.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_preterite_regular_{1,2,3}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

PRETERITE_REGULAR_HABLAR_ENCONTRAR_INTRO = {
    "kind": "cards",
    "title": "Preterite Regular — hablar + encontrar (-ar)",
    "cards": [
        {
            "kind": "text",
            "title": "hablar + encontrar (-ar)",
            "body": "**Preterite** is the simple past for completed actions: 'I spoke,' 'I found.' For -ar verbs, the endings are **-é, -aste, -ó, -amos, -aron**. Note the accents on the yo and él forms.",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "encontrar is normally an o→ue stem-changer in the present (encuentro), but in the preterite it stays regular: encontré, encontraste...",
        },
        {
            "kind": "mini_table",
            "title": "hablar (to speak)",
            "rows": [
            ["yo", "habl|é"],
            ["tú", "habl|aste"],
            ["él / ella / usted", "habl|ó"],
            ["nosotros / nosotras", "habl|amos"],
            ["ellos / ellas / ustedes", "habl|aron"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "encontrar (to find)",
            "rows": [
            ["yo", "encontr|é"],
            ["tú", "encontr|aste"],
            ["él / ella / usted", "encontr|ó"],
            ["nosotros / nosotras", "encontr|amos"],
            ["ellos / ellas / ustedes", "encontr|aron"],
            ],
        },
    ],
    "recall": [
        {"verb": "hablar", "answers": {"yo": "habl|é", "tú": "habl|aste", "él": "habl|ó", "nosotros": "habl|amos", "ellos": "habl|aron"}},
        {"verb": "encontrar", "answers": {"yo": "encontr|é", "tú": "encontr|aste", "él": "encontr|ó", "nosotros": "encontr|amos", "ellos": "encontr|aron"}},
    ],
}

PRETERITE_REGULAR_COMER_BEBER_INTRO = {
    "kind": "cards",
    "title": "Preterite Regular — comer + beber (-er)",
    "cards": [
        {
            "kind": "text",
            "title": "comer + beber (-er)",
            "body": "For regular -er verbs in the preterite, the endings are **-í, -iste, -ió, -imos, -ieron**. Like -ar, the yo and él forms carry an accent.",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "These same endings are shared by regular -ir verbs (you'll see in the next sub-block).",
        },
        {
            "kind": "mini_table",
            "title": "comer (to eat)",
            "rows": [
            ["yo", "com|í"],
            ["tú", "com|iste"],
            ["él / ella / usted", "com|ió"],
            ["nosotros / nosotras", "com|imos"],
            ["ellos / ellas / ustedes", "com|ieron"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "beber (to drink)",
            "rows": [
            ["yo", "beb|í"],
            ["tú", "beb|iste"],
            ["él / ella / usted", "beb|ió"],
            ["nosotros / nosotras", "beb|imos"],
            ["ellos / ellas / ustedes", "beb|ieron"],
            ],
        },
    ],
    "recall": [
        {"verb": "comer", "answers": {"yo": "com|í", "tú": "com|iste", "él": "com|ió", "nosotros": "com|imos", "ellos": "com|ieron"}},
        {"verb": "beber", "answers": {"yo": "beb|í", "tú": "beb|iste", "él": "beb|ió", "nosotros": "beb|imos", "ellos": "beb|ieron"}},
    ],
}

PRETERITE_REGULAR_SALIR_UNIR_INTRO = {
    "kind": "cards",
    "title": "Preterite Regular — salir + unir (-ir)",
    "cards": [
        {
            "kind": "text",
            "title": "salir + unir (-ir)",
            "body": "Regular -ir verbs use the **same preterite endings as -er**: -í, -iste, -ió, -imos, -ieron. salí, saliste, salió...",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "salir is yo-go in present (salgo) but completely regular in the preterite. unir is straightforward in both tenses.",
        },
        {
            "kind": "mini_table",
            "title": "salir (to leave/go out)",
            "rows": [
            ["yo", "sal|í"],
            ["tú", "sal|iste"],
            ["él / ella / usted", "sal|ió"],
            ["nosotros / nosotras", "sal|imos"],
            ["ellos / ellas / ustedes", "sal|ieron"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "unir (to unite/join)",
            "rows": [
            ["yo", "un|í"],
            ["tú", "un|iste"],
            ["él / ella / usted", "un|ió"],
            ["nosotros / nosotras", "un|imos"],
            ["ellos / ellas / ustedes", "un|ieron"],
            ],
        },
    ],
    "recall": [
        {"verb": "salir", "answers": {"yo": "sal|í", "tú": "sal|iste", "él": "sal|ió", "nosotros": "sal|imos", "ellos": "sal|ieron"}},
        {"verb": "unir", "answers": {"yo": "un|í", "tú": "un|iste", "él": "un|ió", "nosotros": "un|imos", "ellos": "un|ieron"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_preterite_regular_hablar_encontrar_1": {
        "title": "Preterite Regular — hablar + encontrar (-ar) (1/2)",
        "grammar_level": 17,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "encontrar"],
        "video_embed_id": "uBOH6A3vO0U",
        "drill_type": "conjugation",
        "tense": "preterite",
        "intro_chart": PRETERITE_REGULAR_HABLAR_ENCONTRAR_INTRO,
        "rule_chart": PRETERITE_REGULAR_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "habl|é", "tú": "habl|aste", "él": "habl|ó", "ella": "habl|ó", "usted": "habl|ó", "nosotros": "habl|amos", "nosotras": "habl|amos", "ellos": "habl|aron", "ellas": "habl|aron", "ustedes": "habl|aron"},
                "encontrar": {"yo": "encontr|é", "tú": "encontr|aste", "él": "encontr|ó", "ella": "encontr|ó", "usted": "encontr|ó", "nosotros": "encontr|amos", "nosotras": "encontr|amos", "ellos": "encontr|aron", "ellas": "encontr|aron", "ustedes": "encontr|aron"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I spoke with my friend.", "es": "Yo hablé con mi amigo.", "noun_id": None, "type": "written", "glosses": {"friend": "amigo", "amigo": "friend"}},
            {"en": "You spoke clearly.", "es": "Tú hablaste claramente.", "noun_id": None, "type": "auditory", "glosses": {"clearly": "claramente", "claramente": "clearly"}},
            {"en": "She spoke Spanish yesterday.", "es": "Ella habló español ayer.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish", "yesterday": "ayer", "ayer": "yesterday"}},
            {"en": "We (f) spoke a lot.", "es": "Nosotras hablamos mucho.", "noun_id": None, "type": "auditory", "glosses": {"much": "mucho", "mucho": "much"}},
            {"en": "You all spoke in class.", "es": "Ustedes hablaron en clase.", "noun_id": None, "type": "written", "glosses": {"class": "clase", "clase": "class"}},
            {"en": "I found a book.", "es": "Yo encontré un libro.", "noun_id": None, "type": "written", "glosses": {"book": "libro", "libro": "book"}},
            {"en": "You found the keys.", "es": "Tú encontraste las llaves.", "noun_id": None, "type": "auditory", "glosses": {"keys": "llaves", "llaves": "keys"}},
            {"en": "She found her bag.", "es": "Ella encontró su bolso.", "noun_id": None, "type": "written", "glosses": {"bag": "bolso", "bolso": "bag"}},
            {"en": "We (f) found new places.", "es": "Nosotras encontramos lugares nuevos.", "noun_id": None, "type": "auditory", "glosses": {"places": "lugares", "new": "nuevos", "lugares": "places", "nuevos": "new"}},
            {"en": "You all found the solution.", "es": "Ustedes encontraron la solución.", "noun_id": None, "type": "written", "glosses": {"solution": "solución", "solución": "solution"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "encontrar", "pronoun": "yo"}, {"verb": "encontrar", "pronoun": "tú"}, {"verb": "encontrar", "pronoun": "ella"}, {"verb": "encontrar", "pronoun": "nosotras"}, {"verb": "encontrar", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Preterite Regular hablar + encontrar (-ar) (1/2): hablar, encontrar",
            "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "encontrar", "pronoun": "yo"}, {"verb": "encontrar", "pronoun": "tú"}, {"verb": "encontrar", "pronoun": "ella"}, {"verb": "encontrar", "pronoun": "nosotras"}, {"verb": "encontrar", "pronoun": "ustedes"}],
        },
        "opener_en": "What did you say yesterday?",
        "opener_es": "¿Qué hablaste ayer?",
    },

    "grammar_preterite_regular_hablar_encontrar_2": {
        "title": "Preterite Regular — hablar + encontrar (-ar) (2/2)",
        "grammar_level": 17,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "encontrar"],
        "video_embed_id": "uBOH6A3vO0U",
        "drill_type": "conjugation",
        "tense": "preterite",
        "rule_chart": PRETERITE_REGULAR_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "habl|é", "tú": "habl|aste", "él": "habl|ó", "ella": "habl|ó", "usted": "habl|ó", "nosotros": "habl|amos", "nosotras": "habl|amos", "ellos": "habl|aron", "ellas": "habl|aron", "ustedes": "habl|aron"},
                "encontrar": {"yo": "encontr|é", "tú": "encontr|aste", "él": "encontr|ó", "ella": "encontr|ó", "usted": "encontr|ó", "nosotros": "encontr|amos", "nosotras": "encontr|amos", "ellos": "encontr|aron", "ellas": "encontr|aron", "ustedes": "encontr|aron"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You spoke with the teacher.", "es": "Tú hablaste con el profesor.", "noun_id": None, "type": "written", "glosses": {"teacher": "profesor", "profesor": "teacher"}},
            {"en": "I spoke Spanish yesterday.", "es": "Yo hablé español ayer.", "noun_id": None, "type": "auditory", "glosses": {"Spanish": "español", "español": "Spanish", "yesterday": "ayer", "ayer": "yesterday"}},
            {"en": "He spoke very clearly.", "es": "Él habló muy claro.", "noun_id": None, "type": "written", "glosses": {"very": "muy", "clear": "claro", "claro": "clear", "muy": "very"}},
            {"en": "We (m) spoke at the meeting.", "es": "Nosotros hablamos en la reunión.", "noun_id": None, "type": "auditory", "glosses": {"meeting": "reunión", "reunión": "meeting"}},
            {"en": "They (f) spoke to their friends.", "es": "Ellas hablaron con sus amigas.", "noun_id": None, "type": "written", "glosses": {"friends": "amigas", "amigas": "friends"}},
            {"en": "You found the keys.", "es": "Tú encontraste las llaves.", "noun_id": None, "type": "written", "glosses": {"keys": "llaves", "llaves": "keys"}},
            {"en": "I found a new book.", "es": "Yo encontré un libro nuevo.", "noun_id": None, "type": "auditory", "glosses": {"book": "libro", "new": "nuevo", "nuevo": "new", "libro": "book"}},
            {"en": "He found the restaurant quickly.", "es": "Él encontró el restaurante rápido.", "noun_id": None, "type": "written", "glosses": {"restaurant": "restaurante", "quickly": "rápido", "rápido": "quickly", "restaurante": "restaurant"}},
            {"en": "We (m) found old photos.", "es": "Nosotros encontramos fotos viejas.", "noun_id": None, "type": "auditory", "glosses": {"photos": "fotos", "old": "viejas", "viejas": "old", "fotos": "photos"}},
            {"en": "They (f) found a beautiful park.", "es": "Ellas encontraron un parque hermoso.", "noun_id": None, "type": "written", "glosses": {"park": "parque", "beautiful": "hermoso", "hermoso": "beautiful", "parque": "park"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "encontrar", "pronoun": "tú"}, {"verb": "encontrar", "pronoun": "yo"}, {"verb": "encontrar", "pronoun": "él"}, {"verb": "encontrar", "pronoun": "nosotros"}, {"verb": "encontrar", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Preterite Regular hablar + encontrar (-ar) (2/2): hablar, encontrar",
            "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "encontrar", "pronoun": "tú"}, {"verb": "encontrar", "pronoun": "yo"}, {"verb": "encontrar", "pronoun": "él"}, {"verb": "encontrar", "pronoun": "nosotros"}, {"verb": "encontrar", "pronoun": "ellas"}],
        },
        "opener_en": "Where did you find your keys?",
        "opener_es": "¿Dónde encontraste tus llaves?",
    },

    "grammar_preterite_regular_comer_beber_1": {
        "title": "Preterite Regular — comer + beber (-er) (1/2)",
        "grammar_level": 17,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["comer", "beber"],
        "video_embed_id": "uBOH6A3vO0U",
        "drill_type": "conjugation",
        "tense": "preterite",
        "intro_chart": PRETERITE_REGULAR_COMER_BEBER_INTRO,
        "rule_chart": PRETERITE_REGULAR_RULE,
        "drill_config": {
            "answers": {
                "comer": {"yo": "com|í", "tú": "com|iste", "él": "com|ió", "ella": "com|ió", "usted": "com|ió", "nosotros": "com|imos", "nosotras": "com|imos", "ellos": "com|ieron", "ellas": "com|ieron", "ustedes": "com|ieron"},
                "beber": {"yo": "beb|í", "tú": "beb|iste", "él": "beb|ió", "ella": "beb|ió", "usted": "beb|ió", "nosotros": "beb|imos", "nosotras": "beb|imos", "ellos": "beb|ieron", "ellas": "beb|ieron", "ustedes": "beb|ieron"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I ate an apple.", "es": "Yo comí una manzana.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "manzana": "apple"}},
            {"en": "You ate the bread.", "es": "Tú comiste el pan.", "noun_id": None, "type": "auditory", "glosses": {"bread": "pan", "pan": "bread"}},
            {"en": "She ate fresh fish.", "es": "Ella comió pescado fresco.", "noun_id": None, "type": "written", "glosses": {"fish": "pescado", "fresh": "fresco", "pescado": "fish", "fresco": "fresh"}},
            {"en": "We (f) ate delicious pasta.", "es": "Nosotras comimos pasta deliciosa.", "noun_id": None, "type": "auditory", "glosses": {"pasta": "pasta", "delicious": "deliciosa", "deliciosa": "delicious"}},
            {"en": "You all ate big sandwiches.", "es": "Ustedes comieron sándwiches grandes.", "noun_id": None, "type": "written", "glosses": {"sandwiches": "sándwiches", "big": "grandes", "sándwiches": "sandwiches", "grandes": "big"}},
            {"en": "I drank cold water.", "es": "Yo bebí agua fría.", "noun_id": None, "type": "written", "glosses": {"water": "agua", "cold": "fría", "agua": "water", "fría": "cold"}},
            {"en": "You drank orange juice.", "es": "Tú bebiste jugo de naranja.", "noun_id": None, "type": "auditory", "glosses": {"juice": "jugo", "orange": "naranja", "jugo": "juice", "naranja": "orange"}},
            {"en": "She drank hot coffee.", "es": "Ella bebió café caliente.", "noun_id": None, "type": "written", "glosses": {"coffee": "café", "hot": "caliente", "café": "coffee", "caliente": "hot"}},
            {"en": "We (f) drank fresh milk.", "es": "Nosotras bebimos leche fresca.", "noun_id": None, "type": "auditory", "glosses": {"milk": "leche", "fresh": "fresca", "leche": "milk", "fresca": "fresh"}},
            {"en": "You all drank cold tea.", "es": "Ustedes bebieron té frío.", "noun_id": None, "type": "written", "glosses": {"tea": "té", "cold": "frío", "té": "tea", "frío": "cold"}},
        ],
        "drill_targets": [{"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "ella"}, {"verb": "beber", "pronoun": "nosotras"}, {"verb": "beber", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Preterite Regular comer + beber (-er) (1/2): comer, beber",
            "targets": [{"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "ella"}, {"verb": "beber", "pronoun": "nosotras"}, {"verb": "beber", "pronoun": "ustedes"}],
        },
        "opener_en": "What did you eat for lunch?",
        "opener_es": "¿Qué comiste para el almuerzo?",
    },

    "grammar_preterite_regular_comer_beber_2": {
        "title": "Preterite Regular — comer + beber (-er) (2/2)",
        "grammar_level": 17,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["comer", "beber"],
        "video_embed_id": "uBOH6A3vO0U",
        "drill_type": "conjugation",
        "tense": "preterite",
        "rule_chart": PRETERITE_REGULAR_RULE,
        "drill_config": {
            "answers": {
                "comer": {"yo": "com|í", "tú": "com|iste", "él": "com|ió", "ella": "com|ió", "usted": "com|ió", "nosotros": "com|imos", "nosotras": "com|imos", "ellos": "com|ieron", "ellas": "com|ieron", "ustedes": "com|ieron"},
                "beber": {"yo": "beb|í", "tú": "beb|iste", "él": "beb|ió", "ella": "beb|ió", "usted": "beb|ió", "nosotros": "beb|imos", "nosotras": "beb|imos", "ellos": "beb|ieron", "ellas": "beb|ieron", "ustedes": "beb|ieron"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You ate the red apple.", "es": "Tú comiste la manzana roja.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "red": "roja", "manzana": "apple", "roja": "red"}},
            {"en": "I ate fresh bread.", "es": "Yo comí pan fresco.", "noun_id": None, "type": "auditory", "glosses": {"bread": "pan", "fresh": "fresco", "pan": "bread", "fresco": "fresh"}},
            {"en": "He ate the big fish.", "es": "Él comió el pez grande.", "noun_id": None, "type": "written", "glosses": {"fish": "pez", "big": "grande", "pez": "fish", "grande": "big"}},
            {"en": "We (m) ate delicious meals.", "es": "Nosotros comimos comidas deliciosas.", "noun_id": None, "type": "auditory", "glosses": {"meal": "comidas", "delicious": "deliciosas", "comidas": "meal", "deliciosas": "delicious"}},
            {"en": "They (f) ate sweet fruits.", "es": "Ellas comieron frutas dulces.", "noun_id": None, "type": "written", "glosses": {"fruit": "frutas", "sweet": "dulces", "frutas": "fruit", "dulces": "sweet"}},
            {"en": "You drank cold water.", "es": "Tú bebiste agua fría.", "noun_id": None, "type": "written", "glosses": {"water": "agua", "cold": "fría", "agua": "water", "fría": "cold"}},
            {"en": "I drank hot coffee.", "es": "Yo bebí café caliente.", "noun_id": None, "type": "auditory", "glosses": {"coffee": "café", "hot": "caliente", "café": "coffee", "caliente": "hot"}},
            {"en": "He drank fresh juice.", "es": "Él bebió jugo fresco.", "noun_id": None, "type": "written", "glosses": {"juice": "jugo", "fresh": "fresco", "jugo": "juice", "fresco": "fresh"}},
            {"en": "We (m) drank sweet milk.", "es": "Nosotros bebimos leche dulce.", "noun_id": None, "type": "auditory", "glosses": {"milk": "leche", "sweet": "dulce", "leche": "milk", "dulce": "sweet"}},
            {"en": "They (f) drank cold tea.", "es": "Ellas bebieron té frío.", "noun_id": None, "type": "written", "glosses": {"tea": "té", "cold": "frío", "té": "tea", "frío": "cold"}},
        ],
        "drill_targets": [{"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "él"}, {"verb": "beber", "pronoun": "nosotros"}, {"verb": "beber", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Preterite Regular comer + beber (-er) (2/2): comer, beber",
            "targets": [{"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "él"}, {"verb": "beber", "pronoun": "nosotros"}, {"verb": "beber", "pronoun": "ellas"}],
        },
        "opener_en": "What did you drink at the party?",
        "opener_es": "¿Qué bebiste en la fiesta?",
    },

    "grammar_preterite_regular_salir_unir_1": {
        "title": "Preterite Regular — salir + unir (-ir) (1/2)",
        "grammar_level": 17,
        "lesson_number": 5,
        "lesson_type": "conjugation",
        "word_workload": ["salir", "unir"],
        "video_embed_id": "uBOH6A3vO0U",
        "drill_type": "conjugation",
        "tense": "preterite",
        "intro_chart": PRETERITE_REGULAR_SALIR_UNIR_INTRO,
        "rule_chart": PRETERITE_REGULAR_RULE,
        "drill_config": {
            "answers": {
                "salir": {"yo": "sal|í", "tú": "sal|iste", "él": "sal|ió", "ella": "sal|ió", "usted": "sal|ió", "nosotros": "sal|imos", "nosotras": "sal|imos", "ellos": "sal|ieron", "ellas": "sal|ieron", "ustedes": "sal|ieron"},
                "unir": {"yo": "un|í", "tú": "un|iste", "él": "un|ió", "ella": "un|ió", "usted": "un|ió", "nosotros": "un|imos", "nosotras": "un|imos", "ellos": "un|ieron", "ellas": "un|ieron", "ustedes": "un|ieron"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I left the house early.", "es": "Yo salí de la casa temprano.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "early": "temprano", "casa": "house", "temprano": "early"}},
            {"en": "You left with your friends.", "es": "Tú saliste con tus amigos.", "noun_id": None, "type": "auditory", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "She left the party at midnight.", "es": "Ella salió de la fiesta a medianoche.", "noun_id": None, "type": "written", "glosses": {"party": "fiesta", "midnight": "medianoche", "fiesta": "party", "medianoche": "midnight"}},
            {"en": "We (f) left the school quickly.", "es": "Nosotras salimos de la escuela rápido.", "noun_id": None, "type": "auditory", "glosses": {"school": "escuela", "quickly": "rápido", "escuela": "school", "rápido": "quickly"}},
            {"en": "You all left the restaurant late.", "es": "Ustedes salieron del restaurante tarde.", "noun_id": None, "type": "written", "glosses": {"restaurant": "restaurante", "late": "tarde", "restaurante": "restaurant", "tarde": "late"}},
            {"en": "I joined the team yesterday.", "es": "Yo uní al equipo ayer.", "noun_id": None, "type": "written", "glosses": {"team": "equipo", "yesterday": "ayer", "equipo": "team", "ayer": "yesterday"}},
            {"en": "You joined the group quickly.", "es": "Tú uniste al grupo rápido.", "noun_id": None, "type": "auditory", "glosses": {"group": "grupo", "quickly": "rápido", "grupo": "group", "rápido": "quickly"}},
            {"en": "She joined the club last week.", "es": "Ella unió al club la semana pasada.", "noun_id": None, "type": "written", "glosses": {"club": "club", "week": "semana", "last": "pasada", "semana": "week", "pasada": "last"}},
            {"en": "We (f) joined the classes early.", "es": "Nosotras unimos a las clases temprano.", "noun_id": None, "type": "auditory", "glosses": {"classes": "clases", "early": "temprano", "clases": "classes", "temprano": "early"}},
            {"en": "You all joined the meeting yesterday.", "es": "Ustedes unieron a la reunión ayer.", "noun_id": None, "type": "written", "glosses": {"meeting": "reunión", "yesterday": "ayer", "reunión": "meeting", "ayer": "yesterday"}},
        ],
        "drill_targets": [{"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "ella"}, {"verb": "salir", "pronoun": "nosotras"}, {"verb": "salir", "pronoun": "ustedes"}, {"verb": "unir", "pronoun": "yo"}, {"verb": "unir", "pronoun": "tú"}, {"verb": "unir", "pronoun": "ella"}, {"verb": "unir", "pronoun": "nosotras"}, {"verb": "unir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Preterite Regular salir + unir (-ir) (1/2): salir, unir",
            "targets": [{"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "ella"}, {"verb": "salir", "pronoun": "nosotras"}, {"verb": "salir", "pronoun": "ustedes"}, {"verb": "unir", "pronoun": "yo"}, {"verb": "unir", "pronoun": "tú"}, {"verb": "unir", "pronoun": "ella"}, {"verb": "unir", "pronoun": "nosotras"}, {"verb": "unir", "pronoun": "ustedes"}],
        },
        "opener_en": "What time did you leave?",
        "opener_es": "¿A qué hora saliste?",
    },

    "grammar_preterite_regular_salir_unir_2": {
        "title": "Preterite Regular — salir + unir (-ir) (2/2)",
        "grammar_level": 17,
        "lesson_number": 6,
        "lesson_type": "conjugation",
        "word_workload": ["salir", "unir"],
        "video_embed_id": "uBOH6A3vO0U",
        "drill_type": "conjugation",
        "tense": "preterite",
        "rule_chart": PRETERITE_REGULAR_RULE,
        "drill_config": {
            "answers": {
                "salir": {"yo": "sal|í", "tú": "sal|iste", "él": "sal|ió", "ella": "sal|ió", "usted": "sal|ió", "nosotros": "sal|imos", "nosotras": "sal|imos", "ellos": "sal|ieron", "ellas": "sal|ieron", "ustedes": "sal|ieron"},
                "unir": {"yo": "un|í", "tú": "un|iste", "él": "un|ió", "ella": "un|ió", "usted": "un|ió", "nosotros": "un|imos", "nosotras": "un|imos", "ellos": "un|ieron", "ellas": "un|ieron", "ustedes": "un|ieron"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You left the house early.", "es": "Tú saliste de la casa temprano.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "early": "temprano", "casa": "house", "temprano": "early"}},
            {"en": "I left the party at midnight.", "es": "Yo salí de la fiesta a medianoche.", "noun_id": None, "type": "auditory", "glosses": {"party": "fiesta", "midnight": "medianoche", "fiesta": "party", "medianoche": "midnight"}},
            {"en": "He left the restaurant quickly.", "es": "Él salió del restaurante rápidamente.", "noun_id": None, "type": "written", "glosses": {"restaurant": "restaurante", "quickly": "rápidamente", "restaurante": "restaurant", "rápidamente": "quickly"}},
            {"en": "We left the park together.", "es": "Nosotros salimos del parque juntos.", "noun_id": None, "type": "auditory", "glosses": {"park": "parque", "together": "juntos", "parque": "park", "juntos": "together"}},
            {"en": "They (f) left the school late.", "es": "Ellas salieron de la escuela tarde.", "noun_id": None, "type": "written", "glosses": {"school": "escuela", "late": "tarde", "escuela": "school", "tarde": "late"}},
            {"en": "You joined the group yesterday.", "es": "Tú uniste al grupo ayer.", "noun_id": None, "type": "written", "glosses": {"group": "grupo", "yesterday": "ayer", "grupo": "group", "ayer": "yesterday"}},
            {"en": "I joined the team last week.", "es": "Yo uní al equipo la semana pasada.", "noun_id": None, "type": "auditory", "glosses": {"team": "equipo", "week": "semana", "last": "pasada", "equipo": "team", "semana": "week", "pasada": "last"}},
            {"en": "He joined the class early.", "es": "Él unió la clase temprano.", "noun_id": None, "type": "written", "glosses": {"class": "clase", "early": "temprano", "clase": "class", "temprano": "early"}},
            {"en": "We joined the clubs quickly.", "es": "Nosotros unimos los clubes rápidamente.", "noun_id": None, "type": "auditory", "glosses": {"clubs": "clubes", "quickly": "rápidamente", "clubes": "clubs", "rápidamente": "quickly"}},
            {"en": "They (f) joined the teams yesterday.", "es": "Ellas unieron los equipos ayer.", "noun_id": None, "type": "written", "glosses": {"teams": "equipos", "yesterday": "ayer", "equipos": "teams", "ayer": "yesterday"}},
        ],
        "drill_targets": [{"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "él"}, {"verb": "salir", "pronoun": "nosotros"}, {"verb": "salir", "pronoun": "ellas"}, {"verb": "unir", "pronoun": "tú"}, {"verb": "unir", "pronoun": "yo"}, {"verb": "unir", "pronoun": "él"}, {"verb": "unir", "pronoun": "nosotros"}, {"verb": "unir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Preterite Regular salir + unir (-ir) (2/2): salir, unir",
            "targets": [{"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "él"}, {"verb": "salir", "pronoun": "nosotros"}, {"verb": "salir", "pronoun": "ellas"}, {"verb": "unir", "pronoun": "tú"}, {"verb": "unir", "pronoun": "yo"}, {"verb": "unir", "pronoun": "él"}, {"verb": "unir", "pronoun": "nosotros"}, {"verb": "unir", "pronoun": "ellas"}],
        },
        "opener_en": "Did the team unite?",
        "opener_es": "¿Se unió el equipo?",
    },

    "grammar_preterite_regular_hablar_encontrar_chat": {
        "title": "Preterite Regular — hablar + encontrar (-ar) Chat",
        "grammar_level": 17,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "encontrar"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "preterite",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Preterite Regular hablar + encontrar (-ar) chat: hablar, encontrar", "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "encontrar", "pronoun": "tú"}, {"verb": "encontrar", "pronoun": "yo"}, {"verb": "encontrar", "pronoun": "él"}, {"verb": "encontrar", "pronoun": "nosotros"}, {"verb": "encontrar", "pronoun": "ellas"}]},
    },

    "grammar_preterite_regular_comer_beber_chat": {
        "title": "Preterite Regular — comer + beber (-er) Chat",
        "grammar_level": 17,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["comer", "beber"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "preterite",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Preterite Regular comer + beber (-er) chat: comer, beber", "targets": [{"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "él"}, {"verb": "beber", "pronoun": "nosotros"}, {"verb": "beber", "pronoun": "ellas"}]},
    },

    "grammar_preterite_regular_salir_unir_chat": {
        "title": "Preterite Regular — salir + unir (-ir) Chat",
        "grammar_level": 17,
        "lesson_number": 6.5,
        "lesson_type": "conjugation",
        "word_workload": ["salir", "unir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "preterite",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Preterite Regular salir + unir (-ir) chat: salir, unir", "targets": [{"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "ella"}, {"verb": "salir", "pronoun": "nosotras"}, {"verb": "salir", "pronoun": "ustedes"}, {"verb": "unir", "pronoun": "tú"}, {"verb": "unir", "pronoun": "yo"}, {"verb": "unir", "pronoun": "él"}, {"verb": "unir", "pronoun": "nosotros"}, {"verb": "unir", "pronoun": "ellas"}]},
    },
