"""Auto-generated by scripts/split_gl18_5.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_perfect_tenses_drill_{1,2}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

PERFECT_TENSES_PRESENT_INTRO = {
    "kind": "cards",
    "title": "Perfect Tenses — present perfect (hablar + comer)",
    "cards": [
        {
            "kind": "text",
            "title": "present perfect (hablar + comer)",
            "body": "**Present perfect** = haber-present + past participle: 'he hablado' (I have spoken). The endings of haber are: he, has, ha, hemos, han.",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "Past participles for regular verbs: -ar → -ado (hablado), -er/-ir → -ido (comido, vivido). They never agree in gender or number when used with haber.",
        },
        {
            "kind": "mini_table",
            "title": "hablar (to speak)",
            "rows": [
            ["yo", "|he hablado"],
            ["tú", "|has hablado"],
            ["él / ella / usted", "|ha hablado"],
            ["nosotros / nosotras", "|hemos hablado"],
            ["ellos / ellas / ustedes", "|han hablado"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "comer (to eat)",
            "rows": [
            ["yo", "|he comido"],
            ["tú", "|has comido"],
            ["él / ella / usted", "|ha comido"],
            ["nosotros / nosotras", "|hemos comido"],
            ["ellos / ellas / ustedes", "|han comido"],
            ],
        },
    ],
    "recall": [
        {"verb": "hablar", "answers": {"yo": "|he hablado", "tú": "|has hablado", "él": "|ha hablado", "nosotros": "|hemos hablado", "ellos": "|han hablado"}},
        {"verb": "comer", "answers": {"yo": "|he comido", "tú": "|has comido", "él": "|ha comido", "nosotros": "|hemos comido", "ellos": "|han comido"}},
    ],
}

PERFECT_TENSES_PLUPERFECT_INTRO = {
    "kind": "cards",
    "title": "Perfect Tenses — pluperfect (hablar + vivir)",
    "cards": [
        {
            "kind": "text",
            "title": "pluperfect (hablar + vivir)",
            "body": "**Pluperfect** = haber-imperfect + past participle: 'había hablado' (I had spoken). The endings: había, habías, había, habíamos, habían.",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "Use the pluperfect for actions that happened *before* another past action: 'cuando llegué, ya había comido' (when I arrived, I had already eaten).",
        },
        {
            "kind": "mini_table",
            "title": "hablar (to speak)",
            "rows": [
            ["yo", "|había hablado"],
            ["tú", "|habías hablado"],
            ["él / ella / usted", "|había hablado"],
            ["nosotros / nosotras", "|habíamos hablado"],
            ["ellos / ellas / ustedes", "|habían hablado"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "vivir (to live)",
            "rows": [
            ["yo", "|había vivido"],
            ["tú", "|habías vivido"],
            ["él / ella / usted", "|había vivido"],
            ["nosotros / nosotras", "|habíamos vivido"],
            ["ellos / ellas / ustedes", "|habían vivido"],
            ],
        },
    ],
    "recall": [
        {"verb": "hablar", "answers": {"yo": "|había hablado", "tú": "|habías hablado", "él": "|había hablado", "nosotros": "|habíamos hablado", "ellos": "|habían hablado"}},
        {"verb": "vivir", "answers": {"yo": "|había vivido", "tú": "|habías vivido", "él": "|había vivido", "nosotros": "|habíamos vivido", "ellos": "|habían vivido"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_perfect_tenses_present_perfect_1": {
        "title": "Perfect Tenses — present perfect (hablar + comer) (1/2)",
        "grammar_level": 18.5,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "perfect",
        "intro_chart": PERFECT_TENSES_PRESENT_INTRO,
        "rule_chart": PERFECT_TENSES_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "|he hablado", "tú": "|has hablado", "él": "|ha hablado", "ella": "|ha hablado", "usted": "|ha hablado", "nosotros": "|hemos hablado", "nosotras": "|hemos hablado", "ellos": "|han hablado", "ellas": "|han hablado", "ustedes": "|han hablado"},
                "comer": {"yo": "|he comido", "tú": "|has comido", "él": "|ha comido", "ella": "|ha comido", "usted": "|ha comido", "nosotros": "|hemos comido", "nosotras": "|hemos comido", "ellos": "|han comido", "ellas": "|han comido", "ustedes": "|han comido"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I have spoken with the teacher.", "es": "Yo he hablado con el profesor.", "noun_id": None, "type": "written", "glosses": {"teacher": "profesor", "profesor": "teacher"}},
            {"en": "You have spoken very clearly.", "es": "Tú has hablado muy claro.", "noun_id": None, "type": "auditory", "glosses": {"clearly": "claro", "claro": "clearly"}},
            {"en": "She has spoken about the problem.", "es": "Ella ha hablado sobre el problema.", "noun_id": None, "type": "written", "glosses": {"problem": "problema", "problema": "problem"}},
            {"en": "We (f) have spoken a lot today.", "es": "Nosotras hemos hablado mucho hoy.", "noun_id": None, "type": "auditory", "glosses": {"today": "hoy", "hoy": "today"}},
            {"en": "You (pl) have spoken with the students.", "es": "Ustedes han hablado con los estudiantes.", "noun_id": None, "type": "written", "glosses": {"students": "estudiantes", "estudiantes": "students"}},
            {"en": "I have eaten the red apple.", "es": "Yo he comido la manzana roja.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "red": "roja", "manzana": "apple", "roja": "red"}},
            {"en": "You have eaten quickly.", "es": "Tú has comido rápido.", "noun_id": None, "type": "auditory", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
            {"en": "She has eaten the fresh bread.", "es": "Ella ha comido el pan fresco.", "noun_id": None, "type": "written", "glosses": {"bread": "pan", "fresh": "fresco", "pan": "bread", "fresco": "fresh"}},
            {"en": "We (f) have eaten at home.", "es": "Nosotras hemos comido en casa.", "noun_id": None, "type": "auditory", "glosses": {"home": "casa", "casa": "home"}},
            {"en": "You (pl) have eaten the big meal.", "es": "Ustedes han comido la comida grande.", "noun_id": None, "type": "written", "glosses": {"meal": "comida", "big": "grande", "comida": "meal", "grande": "big"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Perfect Tenses present perfect (hablar + comer) (1/2): hablar, comer",
            "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}],
        },
        "opener_en": "Have you spoken with him?",
        "opener_es": "¿Has hablado con él?",
    },

    "grammar_perfect_tenses_present_perfect_2": {
        "title": "Perfect Tenses — present perfect (hablar + comer) (2/2)",
        "grammar_level": 18.5,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "perfect",
        "rule_chart": PERFECT_TENSES_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "|he hablado", "tú": "|has hablado", "él": "|ha hablado", "ella": "|ha hablado", "usted": "|ha hablado", "nosotros": "|hemos hablado", "nosotras": "|hemos hablado", "ellos": "|han hablado", "ellas": "|han hablado", "ustedes": "|han hablado"},
                "comer": {"yo": "|he comido", "tú": "|has comido", "él": "|ha comido", "ella": "|ha comido", "usted": "|ha comido", "nosotros": "|hemos comido", "nosotras": "|hemos comido", "ellos": "|han comido", "ellas": "|han comido", "ustedes": "|han comido"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You have spoken Spanish.", "es": "Tú has hablado español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "I have spoken with friends.", "es": "Yo he hablado con amigos.", "noun_id": None, "type": "auditory", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "He has spoken clearly.", "es": "Él ha hablado claramente.", "noun_id": None, "type": "written", "glosses": {"clearly": "claramente", "claramente": "clearly"}},
            {"en": "We (m) have spoken a lot.", "es": "Nosotros hemos hablado mucho.", "noun_id": None, "type": "auditory", "glosses": {"much": "mucho", "mucho": "much"}},
            {"en": "They (f) have spoken softly.", "es": "Ellas han hablado suavemente.", "noun_id": None, "type": "written", "glosses": {"softly": "suavemente", "suavemente": "softly"}},
            {"en": "You have eaten the apples.", "es": "Tú has comido las manzanas.", "noun_id": None, "type": "written", "glosses": {"apples": "manzanas", "manzanas": "apples"}},
            {"en": "I have eaten breakfast.", "es": "Yo he comido el desayuno.", "noun_id": None, "type": "auditory", "glosses": {"breakfast": "desayuno", "desayuno": "breakfast"}},
            {"en": "He has eaten quickly.", "es": "Él ha comido rápido.", "noun_id": None, "type": "written", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
            {"en": "We (m) have eaten well.", "es": "Nosotros hemos comido bien.", "noun_id": None, "type": "auditory", "glosses": {"well": "bien", "bien": "well"}},
            {"en": "They (f) have eaten fruit.", "es": "Ellas han comido fruta.", "noun_id": None, "type": "written", "glosses": {"fruit": "fruta", "fruta": "fruit"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Perfect Tenses present perfect (hablar + comer) (2/2): hablar, comer",
            "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}],
        },
        "opener_en": "Have you eaten lunch?",
        "opener_es": "¿Has comido el almuerzo?",
    },

    "grammar_perfect_tenses_pluperfect_1": {
        "title": "Perfect Tenses — pluperfect (hablar + vivir) (1/2)",
        "grammar_level": 18.5,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "vivir"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "perfect",
        "intro_chart": PERFECT_TENSES_PLUPERFECT_INTRO,
        "rule_chart": PERFECT_TENSES_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "|había hablado", "tú": "|habías hablado", "él": "|había hablado", "ella": "|había hablado", "usted": "|había hablado", "nosotros": "|habíamos hablado", "nosotras": "|habíamos hablado", "ellos": "|habían hablado", "ellas": "|habían hablado", "ustedes": "|habían hablado"},
                "vivir": {"yo": "|había vivido", "tú": "|habías vivido", "él": "|había vivido", "ella": "|había vivido", "usted": "|había vivido", "nosotros": "|habíamos vivido", "nosotras": "|habíamos vivido", "ellos": "|habían vivido", "ellas": "|habían vivido", "ustedes": "|habían vivido"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I had spoken Spanish.", "es": "Yo había hablado español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "You had spoken clearly.", "es": "Tú habías hablado claramente.", "noun_id": None, "type": "auditory", "glosses": {"clearly": "claramente", "claramente": "clearly"}},
            {"en": "She had spoken softly.", "es": "Ella había hablado suavemente.", "noun_id": None, "type": "written", "glosses": {"softly": "suavemente", "suavemente": "softly"}},
            {"en": "We (f) had spoken a lot.", "es": "Nosotras habíamos hablado mucho.", "noun_id": None, "type": "auditory", "glosses": {"a lot": "mucho", "mucho": "a lot"}},
            {"en": "You (pl) had spoken with friends.", "es": "Ustedes habían hablado con amigos.", "noun_id": None, "type": "written", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "I had lived in a big city.", "es": "Yo había vivido en una ciudad grande.", "noun_id": None, "type": "written", "glosses": {"city": "ciudad", "big": "grande", "grande": "big", "ciudad": "city"}},
            {"en": "You had lived happily.", "es": "Tú habías vivido felizmente.", "noun_id": None, "type": "auditory", "glosses": {"happily": "felizmente", "felizmente": "happily"}},
            {"en": "She had lived near the beach.", "es": "Ella había vivido cerca de la playa.", "noun_id": None, "type": "written", "glosses": {"beach": "playa", "playa": "beach"}},
            {"en": "We (f) had lived in small houses.", "es": "Nosotras habíamos vivido en casas pequeñas.", "noun_id": None, "type": "auditory", "glosses": {"houses": "casas", "small": "pequeñas", "pequeñas": "small", "casas": "houses"}},
            {"en": "You (pl) had lived many years.", "es": "Ustedes habían vivido muchos años.", "noun_id": None, "type": "written", "glosses": {"years": "años", "many": "muchos", "muchos": "many", "años": "years"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "ella"}, {"verb": "vivir", "pronoun": "nosotras"}, {"verb": "vivir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Perfect Tenses pluperfect (hablar + vivir) (1/2): hablar, vivir",
            "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "ella"}, {"verb": "vivir", "pronoun": "nosotras"}, {"verb": "vivir", "pronoun": "ustedes"}],
        },
        "opener_en": "Had you spoken to her before?",
        "opener_es": "¿Le habías hablado antes?",
    },

    "grammar_perfect_tenses_pluperfect_2": {
        "title": "Perfect Tenses — pluperfect (hablar + vivir) (2/2)",
        "grammar_level": 18.5,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "vivir"],
        "video_embed_id": None,
        "drill_type": "conjugation",
        "tense": "perfect",
        "rule_chart": PERFECT_TENSES_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "|había hablado", "tú": "|habías hablado", "él": "|había hablado", "ella": "|había hablado", "usted": "|había hablado", "nosotros": "|habíamos hablado", "nosotras": "|habíamos hablado", "ellos": "|habían hablado", "ellas": "|habían hablado", "ustedes": "|habían hablado"},
                "vivir": {"yo": "|había vivido", "tú": "|habías vivido", "él": "|había vivido", "ella": "|había vivido", "usted": "|había vivido", "nosotros": "|habíamos vivido", "nosotras": "|habíamos vivido", "ellos": "|habían vivido", "ellas": "|habían vivido", "ustedes": "|habían vivido"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You had spoken with the teacher.", "es": "Tú habías hablado con el profesor.", "noun_id": None, "type": "written", "glosses": {"teacher": "profesor", "profesor": "teacher"}},
            {"en": "I had spoken Spanish.", "es": "Yo había hablado español.", "noun_id": None, "type": "auditory", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "He had spoken clearly.", "es": "Él había hablado claramente.", "noun_id": None, "type": "written", "glosses": {"clearly": "claramente", "claramente": "clearly"}},
            {"en": "We (m) had spoken a lot.", "es": "Nosotros habíamos hablado mucho.", "noun_id": None, "type": "auditory", "glosses": {"a lot": "mucho", "mucho": "a lot"}},
            {"en": "They (f) had spoken softly.", "es": "Ellas habían hablado suavemente.", "noun_id": None, "type": "written", "glosses": {"softly": "suavemente", "suavemente": "softly"}},
            {"en": "You had lived in a big city.", "es": "Tú habías vivido en una ciudad grande.", "noun_id": None, "type": "written", "glosses": {"city": "ciudad", "big": "grande", "ciudad": "city", "grande": "big"}},
            {"en": "I had lived near the beach.", "es": "Yo había vivido cerca de la playa.", "noun_id": None, "type": "auditory", "glosses": {"beach": "playa", "playa": "beach"}},
            {"en": "He had lived in a small house.", "es": "Él había vivido en una casa pequeña.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "small": "pequeña", "casa": "house", "pequeña": "small"}},
            {"en": "We (m) had lived happily.", "es": "Nosotros habíamos vivido felizmente.", "noun_id": None, "type": "auditory", "glosses": {"happily": "felizmente", "felizmente": "happily"}},
            {"en": "They (f) had lived far away.", "es": "Ellas habían vivido lejos.", "noun_id": None, "type": "written", "glosses": {"far away": "lejos", "lejos": "far away"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "él"}, {"verb": "vivir", "pronoun": "nosotros"}, {"verb": "vivir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Perfect Tenses pluperfect (hablar + vivir) (2/2): hablar, vivir",
            "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "él"}, {"verb": "vivir", "pronoun": "nosotros"}, {"verb": "vivir", "pronoun": "ellas"}],
        },
        "opener_en": "Had you lived there before?",
        "opener_es": "¿Habías vivido allí antes?",
    },

    "grammar_perfect_tenses_present_perfect_chat": {
        "title": "Perfect Tenses — present perfect (hablar + comer) Chat",
        "grammar_level": 18.5,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "perfect",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Perfect Tenses present perfect (hablar + comer) chat: hablar, comer", "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}]},
    },

    "grammar_perfect_tenses_pluperfect_chat": {
        "title": "Perfect Tenses — pluperfect (hablar + vivir) Chat",
        "grammar_level": 18.5,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "vivir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "perfect",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Perfect Tenses pluperfect (hablar + vivir) chat: hablar, vivir", "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "él"}, {"verb": "vivir", "pronoun": "nosotros"}, {"verb": "vivir", "pronoun": "ellas"}]},
    },
