"""Auto-generated by scripts/split_gl18.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_gerund_{1,2,3,4}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

GERUND_HABLAR_CAMINAR_INTRO = {
    "kind": "cards",
    "title": "Gerund / Present Progressive — hablar + caminar (-ar)",
    "cards": [
        {
            "kind": "text",
            "title": "hablar + caminar (-ar)",
            "body": "**Present progressive** = estar + gerund: 'estoy hablando' (I am speaking). For -ar verbs, the gerund ending is **-ando**: hablando, caminando.",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "Spanish uses the progressive less often than English. Use it for actions happening *right now* or in a vivid moment, not for general habits.",
        },
        {
            "kind": "mini_table",
            "title": "hablar (to speak) — present progressive",
            "rows": [
            ["yo", "est|oy hablando"],
            ["tú", "est|ás hablando"],
            ["él / ella / usted", "est|á hablando"],
            ["nosotros / nosotras", "est|amos hablando"],
            ["ellos / ellas / ustedes", "est|án hablando"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "caminar (to walk) — present progressive",
            "rows": [
            ["yo", "est|oy caminando"],
            ["tú", "est|ás caminando"],
            ["él / ella / usted", "est|á caminando"],
            ["nosotros / nosotras", "est|amos caminando"],
            ["ellos / ellas / ustedes", "est|án caminando"],
            ],
        },
    ],
    "recall": [
        {"verb": "hablar", "answers": {"yo": "est|oy hablando", "tú": "est|ás hablando", "él": "est|á hablando", "nosotros": "est|amos hablando", "ellos": "est|án hablando"}},
        {"verb": "caminar", "answers": {"yo": "est|oy caminando", "tú": "est|ás caminando", "él": "est|á caminando", "nosotros": "est|amos caminando", "ellos": "est|án caminando"}},
    ],
}

GERUND_COMER_BEBER_INTRO = {
    "kind": "cards",
    "title": "Gerund / Present Progressive — comer + beber (-er)",
    "cards": [
        {
            "kind": "text",
            "title": "comer + beber (-er)",
            "body": "For regular -er verbs, the gerund ending is **-iendo**: comiendo, bebiendo. estar still flexes for the subject (estoy comiendo, estás bebiendo).",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "The -iendo ending is shared with regular -ir verbs (next sub-block).",
        },
        {
            "kind": "mini_table",
            "title": "comer (to eat) — present progressive",
            "rows": [
            ["yo", "est|oy comiendo"],
            ["tú", "est|ás comiendo"],
            ["él / ella / usted", "est|á comiendo"],
            ["nosotros / nosotras", "est|amos comiendo"],
            ["ellos / ellas / ustedes", "est|án comiendo"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "beber (to drink) — present progressive",
            "rows": [
            ["yo", "est|oy bebiendo"],
            ["tú", "est|ás bebiendo"],
            ["él / ella / usted", "est|á bebiendo"],
            ["nosotros / nosotras", "est|amos bebiendo"],
            ["ellos / ellas / ustedes", "est|án bebiendo"],
            ],
        },
    ],
    "recall": [
        {"verb": "comer", "answers": {"yo": "est|oy comiendo", "tú": "est|ás comiendo", "él": "est|á comiendo", "nosotros": "est|amos comiendo", "ellos": "est|án comiendo"}},
        {"verb": "beber", "answers": {"yo": "est|oy bebiendo", "tú": "est|ás bebiendo", "él": "est|á bebiendo", "nosotros": "est|amos bebiendo", "ellos": "est|án bebiendo"}},
    ],
}

GERUND_SALIR_INHIBIR_INTRO = {
    "kind": "cards",
    "title": "Gerund / Present Progressive — salir + inhibir (-ir)",
    "cards": [
        {
            "kind": "text",
            "title": "salir + inhibir (-ir)",
            "body": "Regular -ir verbs use the same **-iendo** ending: saliendo, inhibiendo.",
        },
        {
            "kind": "text",
            "title": "Notes",
            "body": "Some -ir verbs have stem changes in the gerund (durmiendo, pidiendo, sintiendo) — but salir and inhibir are regular here.",
        },
        {
            "kind": "mini_table",
            "title": "salir (to leave/go out) — present progressive",
            "rows": [
            ["yo", "est|oy saliendo"],
            ["tú", "est|ás saliendo"],
            ["él / ella / usted", "est|á saliendo"],
            ["nosotros / nosotras", "est|amos saliendo"],
            ["ellos / ellas / ustedes", "est|án saliendo"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "inhibir (to inhibit) — present progressive",
            "rows": [
            ["yo", "est|oy inhibiendo"],
            ["tú", "est|ás inhibiendo"],
            ["él / ella / usted", "est|á inhibiendo"],
            ["nosotros / nosotras", "est|amos inhibiendo"],
            ["ellos / ellas / ustedes", "est|án inhibiendo"],
            ],
        },
    ],
    "recall": [
        {"verb": "salir", "answers": {"yo": "est|oy saliendo", "tú": "est|ás saliendo", "él": "est|á saliendo", "nosotros": "est|amos saliendo", "ellos": "est|án saliendo"}},
        {"verb": "inhibir", "answers": {"yo": "est|oy inhibiendo", "tú": "est|ás inhibiendo", "él": "est|á inhibiendo", "nosotros": "est|amos inhibiendo", "ellos": "est|án inhibiendo"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_gerund_hablar_caminar_1": {
        "title": "Gerund — hablar + caminar (-ar) (1/2)",
        "grammar_level": 18,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "caminar"],
        "video_embed_id": "Xpma6w0jy7m",
        "drill_type": "conjugation",
        "tense": "gerund",
        "intro_chart": GERUND_HABLAR_CAMINAR_INTRO,
        "rule_chart": GERUND_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "est|oy hablando", "tú": "est|ás hablando", "él": "est|á hablando", "ella": "est|á hablando", "usted": "est|á hablando", "nosotros": "est|amos hablando", "nosotras": "est|amos hablando", "ellos": "est|án hablando", "ellas": "est|án hablando", "ustedes": "est|án hablando"},
                "caminar": {"yo": "est|oy caminando", "tú": "est|ás caminando", "él": "est|á caminando", "ella": "est|á caminando", "usted": "est|á caminando", "nosotros": "est|amos caminando", "nosotras": "est|amos caminando", "ellos": "est|án caminando", "ellas": "est|án caminando", "ustedes": "est|án caminando"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I am speaking Spanish.", "es": "Yo estoy hablando español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "You are speaking loudly.", "es": "Tú estás hablando fuerte.", "noun_id": None, "type": "auditory", "glosses": {"loudly": "fuerte", "fuerte": "loudly"}},
            {"en": "She is speaking with friends.", "es": "Ella está hablando con amigas.", "noun_id": None, "type": "written", "glosses": {"friends": "amigas", "amigas": "friends"}},
            {"en": "We (f) are speaking softly.", "es": "Nosotras estamos hablando suavemente.", "noun_id": None, "type": "auditory", "glosses": {"softly": "suavemente", "suavemente": "softly"}},
            {"en": "You all are speaking quickly.", "es": "Ustedes están hablando rápido.", "noun_id": None, "type": "written", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
            {"en": "I am walking in the park.", "es": "Yo estoy caminando en el parque.", "noun_id": None, "type": "written", "glosses": {"park": "parque", "parque": "park"}},
            {"en": "You are walking slowly.", "es": "Tú estás caminando despacio.", "noun_id": None, "type": "auditory", "glosses": {"slowly": "despacio", "despacio": "slowly"}},
            {"en": "She is walking to school.", "es": "Ella está caminando a la escuela.", "noun_id": None, "type": "written", "glosses": {"school": "escuela", "escuela": "school"}},
            {"en": "We (f) are walking together.", "es": "Nosotras estamos caminando juntas.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntas", "juntas": "together"}},
            {"en": "You all are walking fast.", "es": "Ustedes están caminando rápido.", "noun_id": None, "type": "written", "glosses": {"fast": "rápido", "rápido": "fast"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "caminar", "pronoun": "yo"}, {"verb": "caminar", "pronoun": "tú"}, {"verb": "caminar", "pronoun": "ella"}, {"verb": "caminar", "pronoun": "nosotras"}, {"verb": "caminar", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Gerund hablar + caminar (-ar) (1/2): hablar, caminar",
            "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "caminar", "pronoun": "yo"}, {"verb": "caminar", "pronoun": "tú"}, {"verb": "caminar", "pronoun": "ella"}, {"verb": "caminar", "pronoun": "nosotras"}, {"verb": "caminar", "pronoun": "ustedes"}],
        },
        "opener_en": "What are you saying?",
        "opener_es": "¿Qué estás hablando?",
    },

    "grammar_gerund_hablar_caminar_2": {
        "title": "Gerund — hablar + caminar (-ar) (2/2)",
        "grammar_level": 18,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "caminar"],
        "video_embed_id": "Xpma6w0jy7m",
        "drill_type": "conjugation",
        "tense": "gerund",
        "rule_chart": GERUND_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "est|oy hablando", "tú": "est|ás hablando", "él": "est|á hablando", "ella": "est|á hablando", "usted": "est|á hablando", "nosotros": "est|amos hablando", "nosotras": "est|amos hablando", "ellos": "est|án hablando", "ellas": "est|án hablando", "ustedes": "est|án hablando"},
                "caminar": {"yo": "est|oy caminando", "tú": "est|ás caminando", "él": "est|á caminando", "ella": "est|á caminando", "usted": "est|á caminando", "nosotros": "est|amos caminando", "nosotras": "est|amos caminando", "ellos": "est|án caminando", "ellas": "est|án caminando", "ustedes": "est|án caminando"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You are speaking Spanish.", "es": "Tú estás hablando español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "I am speaking very clearly.", "es": "Yo estoy hablando muy claro.", "noun_id": None, "type": "auditory", "glosses": {"clearly": "claro", "claro": "clearly"}},
            {"en": "He is speaking with friends.", "es": "Él está hablando con amigos.", "noun_id": None, "type": "written", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "We (m) are speaking loudly.", "es": "Nosotros estamos hablando fuerte.", "noun_id": None, "type": "auditory", "glosses": {"loudly": "fuerte", "fuerte": "loudly"}},
            {"en": "They (f) are speaking quickly.", "es": "Ellas están hablando rápido.", "noun_id": None, "type": "written", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
            {"en": "You are walking to school.", "es": "Tú estás caminando a la escuela.", "noun_id": None, "type": "written", "glosses": {"school": "escuela", "escuela": "school"}},
            {"en": "I am walking slowly.", "es": "Yo estoy caminando despacio.", "noun_id": None, "type": "auditory", "glosses": {"slowly": "despacio", "despacio": "slowly"}},
            {"en": "He is walking in the park.", "es": "Él está caminando en el parque.", "noun_id": None, "type": "written", "glosses": {"park": "parque", "parque": "park"}},
            {"en": "We (m) are walking together.", "es": "Nosotros estamos caminando juntos.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntos", "juntos": "together"}},
            {"en": "They (f) are walking fast.", "es": "Ellas están caminando rápido.", "noun_id": None, "type": "written", "glosses": {"fast": "rápido", "rápido": "fast"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "caminar", "pronoun": "tú"}, {"verb": "caminar", "pronoun": "yo"}, {"verb": "caminar", "pronoun": "él"}, {"verb": "caminar", "pronoun": "nosotros"}, {"verb": "caminar", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Gerund hablar + caminar (-ar) (2/2): hablar, caminar",
            "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "caminar", "pronoun": "tú"}, {"verb": "caminar", "pronoun": "yo"}, {"verb": "caminar", "pronoun": "él"}, {"verb": "caminar", "pronoun": "nosotros"}, {"verb": "caminar", "pronoun": "ellas"}],
        },
        "opener_en": "Where are you walking?",
        "opener_es": "¿Por dónde estás caminando?",
    },

    "grammar_gerund_comer_beber_1": {
        "title": "Gerund — comer + beber (-er) (1/2)",
        "grammar_level": 18,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["comer", "beber"],
        "video_embed_id": "Xpma6w0jy7m",
        "drill_type": "conjugation",
        "tense": "gerund",
        "intro_chart": GERUND_COMER_BEBER_INTRO,
        "rule_chart": GERUND_RULE,
        "drill_config": {
            "answers": {
                "comer": {"yo": "est|oy comiendo", "tú": "est|ás comiendo", "él": "est|á comiendo", "ella": "est|á comiendo", "usted": "est|á comiendo", "nosotros": "est|amos comiendo", "nosotras": "est|amos comiendo", "ellos": "est|án comiendo", "ellas": "est|án comiendo", "ustedes": "est|án comiendo"},
                "beber": {"yo": "est|oy bebiendo", "tú": "est|ás bebiendo", "él": "est|á bebiendo", "ella": "est|á bebiendo", "usted": "est|á bebiendo", "nosotros": "est|amos bebiendo", "nosotras": "est|amos bebiendo", "ellos": "est|án bebiendo", "ellas": "est|án bebiendo", "ustedes": "est|án bebiendo"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I am eating an apple.", "es": "Yo estoy comiendo una manzana.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "manzana": "apple"}},
            {"en": "You are eating bread.", "es": "Tú estás comiendo pan.", "noun_id": None, "type": "auditory", "glosses": {"bread": "pan", "pan": "bread"}},
            {"en": "She is eating rice.", "es": "Ella está comiendo arroz.", "noun_id": None, "type": "written", "glosses": {"rice": "arroz", "arroz": "rice"}},
            {"en": "We (f) are eating salad.", "es": "Nosotras estamos comiendo ensalada.", "noun_id": None, "type": "auditory", "glosses": {"salad": "ensalada", "ensalada": "salad"}},
            {"en": "You (pl) are eating fish.", "es": "Ustedes están comiendo pescado.", "noun_id": None, "type": "written", "glosses": {"fish": "pescado", "pescado": "fish"}},
            {"en": "I am drinking water.", "es": "Yo estoy bebiendo agua.", "noun_id": None, "type": "written", "glosses": {"water": "agua", "agua": "water"}},
            {"en": "You are drinking juice.", "es": "Tú estás bebiendo jugo.", "noun_id": None, "type": "auditory", "glosses": {"juice": "jugo", "jugo": "juice"}},
            {"en": "She is drinking tea.", "es": "Ella está bebiendo té.", "noun_id": None, "type": "written", "glosses": {"tea": "té", "té": "tea"}},
            {"en": "We (f) are drinking coffee.", "es": "Nosotras estamos bebiendo café.", "noun_id": None, "type": "auditory", "glosses": {"coffee": "café", "café": "coffee"}},
            {"en": "You (pl) are drinking milk.", "es": "Ustedes están bebiendo leche.", "noun_id": None, "type": "written", "glosses": {"milk": "leche", "leche": "milk"}},
        ],
        "drill_targets": [{"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "ella"}, {"verb": "beber", "pronoun": "nosotras"}, {"verb": "beber", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Gerund comer + beber (-er) (1/2): comer, beber",
            "targets": [{"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "ella"}, {"verb": "beber", "pronoun": "nosotras"}, {"verb": "beber", "pronoun": "ustedes"}],
        },
        "opener_en": "What are you eating?",
        "opener_es": "¿Qué estás comiendo?",
    },

    "grammar_gerund_comer_beber_2": {
        "title": "Gerund — comer + beber (-er) (2/2)",
        "grammar_level": 18,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["comer", "beber"],
        "video_embed_id": "Xpma6w0jy7m",
        "drill_type": "conjugation",
        "tense": "gerund",
        "rule_chart": GERUND_RULE,
        "drill_config": {
            "answers": {
                "comer": {"yo": "est|oy comiendo", "tú": "est|ás comiendo", "él": "est|á comiendo", "ella": "est|á comiendo", "usted": "est|á comiendo", "nosotros": "est|amos comiendo", "nosotras": "est|amos comiendo", "ellos": "est|án comiendo", "ellas": "est|án comiendo", "ustedes": "est|án comiendo"},
                "beber": {"yo": "est|oy bebiendo", "tú": "est|ás bebiendo", "él": "est|á bebiendo", "ella": "est|á bebiendo", "usted": "est|á bebiendo", "nosotros": "est|amos bebiendo", "nosotras": "est|amos bebiendo", "ellos": "est|án bebiendo", "ellas": "est|án bebiendo", "ustedes": "est|án bebiendo"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You are eating an apple.", "es": "Tú estás comiendo una manzana.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "manzana": "apple"}},
            {"en": "I am eating bread.", "es": "Yo estoy comiendo pan.", "noun_id": None, "type": "auditory", "glosses": {"bread": "pan", "pan": "bread"}},
            {"en": "He is eating rice.", "es": "Él está comiendo arroz.", "noun_id": None, "type": "written", "glosses": {"rice": "arroz", "arroz": "rice"}},
            {"en": "We (m) are eating salad.", "es": "Nosotros estamos comiendo ensalada.", "noun_id": None, "type": "auditory", "glosses": {"salad": "ensalada", "ensalada": "salad"}},
            {"en": "They (f) are eating fruit.", "es": "Ellas están comiendo fruta.", "noun_id": None, "type": "written", "glosses": {"fruit": "fruta", "fruta": "fruit"}},
            {"en": "You are drinking water.", "es": "Tú estás bebiendo agua.", "noun_id": None, "type": "written", "glosses": {"water": "agua", "agua": "water"}},
            {"en": "I am drinking juice.", "es": "Yo estoy bebiendo jugo.", "noun_id": None, "type": "auditory", "glosses": {"juice": "jugo", "jugo": "juice"}},
            {"en": "He is drinking milk.", "es": "Él está bebiendo leche.", "noun_id": None, "type": "written", "glosses": {"milk": "leche", "leche": "milk"}},
            {"en": "We (m) are drinking coffee.", "es": "Nosotros estamos bebiendo café.", "noun_id": None, "type": "auditory", "glosses": {"coffee": "café", "café": "coffee"}},
            {"en": "They (f) are drinking tea.", "es": "Ellas están bebiendo té.", "noun_id": None, "type": "written", "glosses": {"tea": "té", "té": "tea"}},
        ],
        "drill_targets": [{"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "él"}, {"verb": "beber", "pronoun": "nosotros"}, {"verb": "beber", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Gerund comer + beber (-er) (2/2): comer, beber",
            "targets": [{"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "él"}, {"verb": "beber", "pronoun": "nosotros"}, {"verb": "beber", "pronoun": "ellas"}],
        },
        "opener_en": "What are you drinking?",
        "opener_es": "¿Qué estás bebiendo?",
    },

    "grammar_gerund_salir_inhibir_1": {
        "title": "Gerund — salir + inhibir (-ir) (1/2)",
        "grammar_level": 18,
        "lesson_number": 5,
        "lesson_type": "conjugation",
        "word_workload": ["salir", "inhibir"],
        "video_embed_id": "Xpma6w0jy7m",
        "drill_type": "conjugation",
        "tense": "gerund",
        "intro_chart": GERUND_SALIR_INHIBIR_INTRO,
        "rule_chart": GERUND_RULE,
        "drill_config": {
            "answers": {
                "salir": {"yo": "est|oy saliendo", "tú": "est|ás saliendo", "él": "est|á saliendo", "ella": "est|á saliendo", "usted": "est|á saliendo", "nosotros": "est|amos saliendo", "nosotras": "est|amos saliendo", "ellos": "est|án saliendo", "ellas": "est|án saliendo", "ustedes": "est|án saliendo"},
                "inhibir": {"yo": "est|oy inhibiendo", "tú": "est|ás inhibiendo", "él": "est|á inhibiendo", "ella": "est|á inhibiendo", "usted": "est|á inhibiendo", "nosotros": "est|amos inhibiendo", "nosotras": "est|amos inhibiendo", "ellos": "est|án inhibiendo", "ellas": "est|án inhibiendo", "ustedes": "est|án inhibiendo"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I am leaving the house.", "es": "Yo estoy saliendo de la casa.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "casa": "house"}},
            {"en": "You are going out with friends.", "es": "Tú estás saliendo con amigos.", "noun_id": None, "type": "auditory", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "She is leaving the office now.", "es": "Ella está saliendo de la oficina ahora.", "noun_id": None, "type": "written", "glosses": {"office": "oficina", "oficina": "office", "now": "ahora", "ahora": "now"}},
            {"en": "We (f) are leaving the park.", "es": "Nosotras estamos saliendo del parque.", "noun_id": None, "type": "auditory", "glosses": {"park": "parque", "parque": "park"}},
            {"en": "You all are leaving early today.", "es": "Ustedes están saliendo temprano hoy.", "noun_id": None, "type": "written", "glosses": {"today": "hoy", "hoy": "today", "early": "temprano", "temprano": "early"}},
            {"en": "I am inhibiting the process carefully.", "es": "Yo estoy inhibiendo el proceso cuidadosamente.", "noun_id": None, "type": "written", "glosses": {"process": "proceso", "proceso": "process", "carefully": "cuidadosamente", "cuidadosamente": "carefully"}},
            {"en": "You are inhibiting the reaction now.", "es": "Tú estás inhibiendo la reacción ahora.", "noun_id": None, "type": "auditory", "glosses": {"reaction": "reacción", "reacción": "reaction", "now": "ahora", "ahora": "now"}},
            {"en": "She is inhibiting the signal strongly.", "es": "Ella está inhibiendo la señal fuertemente.", "noun_id": None, "type": "written", "glosses": {"signal": "señal", "señal": "signal", "strongly": "fuertemente", "fuertemente": "strongly"}},
            {"en": "We (f) are inhibiting the effects.", "es": "Nosotras estamos inhibiendo los efectos.", "noun_id": None, "type": "auditory", "glosses": {"effects": "efectos", "efectos": "effects"}},
            {"en": "You all are inhibiting the enzymes.", "es": "Ustedes están inhibiendo las enzimas.", "noun_id": None, "type": "written", "glosses": {"enzymes": "enzimas", "enzimas": "enzymes"}},
        ],
        "drill_targets": [{"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "ella"}, {"verb": "salir", "pronoun": "nosotras"}, {"verb": "salir", "pronoun": "ustedes"}, {"verb": "inhibir", "pronoun": "yo"}, {"verb": "inhibir", "pronoun": "tú"}, {"verb": "inhibir", "pronoun": "ella"}, {"verb": "inhibir", "pronoun": "nosotras"}, {"verb": "inhibir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Gerund salir + inhibir (-ir) (1/2): salir, inhibir",
            "targets": [{"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "ella"}, {"verb": "salir", "pronoun": "nosotras"}, {"verb": "salir", "pronoun": "ustedes"}, {"verb": "inhibir", "pronoun": "yo"}, {"verb": "inhibir", "pronoun": "tú"}, {"verb": "inhibir", "pronoun": "ella"}, {"verb": "inhibir", "pronoun": "nosotras"}, {"verb": "inhibir", "pronoun": "ustedes"}],
        },
        "opener_en": "Who is leaving the building?",
        "opener_es": "¿Quién está saliendo del edificio?",
    },

    "grammar_gerund_salir_inhibir_2": {
        "title": "Gerund — salir + inhibir (-ir) (2/2)",
        "grammar_level": 18,
        "lesson_number": 6,
        "lesson_type": "conjugation",
        "word_workload": ["salir", "inhibir"],
        "video_embed_id": "Xpma6w0jy7m",
        "drill_type": "conjugation",
        "tense": "gerund",
        "rule_chart": GERUND_RULE,
        "drill_config": {
            "answers": {
                "salir": {"yo": "est|oy saliendo", "tú": "est|ás saliendo", "él": "est|á saliendo", "ella": "est|á saliendo", "usted": "est|á saliendo", "nosotros": "est|amos saliendo", "nosotras": "est|amos saliendo", "ellos": "est|án saliendo", "ellas": "est|án saliendo", "ustedes": "est|án saliendo"},
                "inhibir": {"yo": "est|oy inhibiendo", "tú": "est|ás inhibiendo", "él": "est|á inhibiendo", "ella": "est|á inhibiendo", "usted": "est|á inhibiendo", "nosotros": "est|amos inhibiendo", "nosotras": "est|amos inhibiendo", "ellos": "est|án inhibiendo", "ellas": "est|án inhibiendo", "ustedes": "est|án inhibiendo"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You are leaving the house.", "es": "Tú estás saliendo de la casa.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "casa": "house"}},
            {"en": "I am leaving now.", "es": "Yo estoy saliendo ahora.", "noun_id": None, "type": "auditory", "glosses": {"now": "ahora", "ahora": "now"}},
            {"en": "He is leaving the room.", "es": "Él está saliendo del cuarto.", "noun_id": None, "type": "written", "glosses": {"room": "cuarto", "cuarto": "room"}},
            {"en": "We (m) are leaving together.", "es": "Nosotros estamos saliendo juntos.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntos", "juntos": "together"}},
            {"en": "They (f) are leaving early.", "es": "Ellas están saliendo temprano.", "noun_id": None, "type": "written", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "You are inhibiting the process.", "es": "Tú estás inhibiendo el proceso.", "noun_id": None, "type": "written", "glosses": {"process": "proceso", "proceso": "process"}},
            {"en": "I am inhibiting the reaction.", "es": "Yo estoy inhibiendo la reacción.", "noun_id": None, "type": "auditory", "glosses": {"reaction": "reacción", "reacción": "reaction"}},
            {"en": "He is inhibiting the signal.", "es": "Él está inhibiendo la señal.", "noun_id": None, "type": "written", "glosses": {"signal": "señal", "señal": "signal"}},
            {"en": "We (m) are inhibiting the response.", "es": "Nosotros estamos inhibiendo la respuesta.", "noun_id": None, "type": "auditory", "glosses": {"response": "respuesta", "respuesta": "response"}},
            {"en": "They (f) are inhibiting the effect.", "es": "Ellas están inhibiendo el efecto.", "noun_id": None, "type": "written", "glosses": {"effect": "efecto", "efecto": "effect"}},
        ],
        "drill_targets": [{"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "él"}, {"verb": "salir", "pronoun": "nosotros"}, {"verb": "salir", "pronoun": "ellas"}, {"verb": "inhibir", "pronoun": "tú"}, {"verb": "inhibir", "pronoun": "yo"}, {"verb": "inhibir", "pronoun": "él"}, {"verb": "inhibir", "pronoun": "nosotros"}, {"verb": "inhibir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Gerund salir + inhibir (-ir) (2/2): salir, inhibir",
            "targets": [{"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "él"}, {"verb": "salir", "pronoun": "nosotros"}, {"verb": "salir", "pronoun": "ellas"}, {"verb": "inhibir", "pronoun": "tú"}, {"verb": "inhibir", "pronoun": "yo"}, {"verb": "inhibir", "pronoun": "él"}, {"verb": "inhibir", "pronoun": "nosotros"}, {"verb": "inhibir", "pronoun": "ellas"}],
        },
        "opener_en": "Are you holding back the urge?",
        "opener_es": "¿Estás inhibiendo el impulso?",
    },

    "grammar_gerund_hablar_caminar_chat": {
        "title": "Gerund — hablar + caminar (-ar) Chat",
        "grammar_level": 18,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "caminar"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "gerund",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Gerund hablar + caminar (-ar) chat: hablar, caminar", "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "caminar", "pronoun": "tú"}, {"verb": "caminar", "pronoun": "yo"}, {"verb": "caminar", "pronoun": "él"}, {"verb": "caminar", "pronoun": "nosotros"}, {"verb": "caminar", "pronoun": "ellas"}]},
    },

    "grammar_gerund_comer_beber_chat": {
        "title": "Gerund — comer + beber (-er) Chat",
        "grammar_level": 18,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["comer", "beber"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "gerund",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Gerund comer + beber (-er) chat: comer, beber", "targets": [{"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}, {"verb": "beber", "pronoun": "tú"}, {"verb": "beber", "pronoun": "yo"}, {"verb": "beber", "pronoun": "él"}, {"verb": "beber", "pronoun": "nosotros"}, {"verb": "beber", "pronoun": "ellas"}]},
    },

    "grammar_gerund_salir_inhibir_chat": {
        "title": "Gerund — salir + inhibir (-ir) Chat",
        "grammar_level": 18,
        "lesson_number": 6.5,
        "lesson_type": "conjugation",
        "word_workload": ["salir", "inhibir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "gerund",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Gerund salir + inhibir (-ir) chat: salir, inhibir", "targets": [{"verb": "salir", "pronoun": "yo"}, {"verb": "salir", "pronoun": "tú"}, {"verb": "salir", "pronoun": "ella"}, {"verb": "salir", "pronoun": "nosotras"}, {"verb": "salir", "pronoun": "ustedes"}, {"verb": "inhibir", "pronoun": "tú"}, {"verb": "inhibir", "pronoun": "yo"}, {"verb": "inhibir", "pronoun": "él"}, {"verb": "inhibir", "pronoun": "nosotros"}, {"verb": "inhibir", "pronoun": "ellas"}]},
    },
