"""Auto-generated by scripts/split_gl6.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_present_o_ue_{1,2,3}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

PRESENT_O_UE_PODER_VOLVER_INTRO = {
    "kind": "cards",
    "title": "Stem o→ue — poder + volver",
    "cards": [
        {
            "kind": "text",
            "title": "poder + volver",
            "body": "Stem-changing verbs change **o → ue** in the stressed syllable: p**ue**do, v**ue**lvo. The change skips nosotros / nosotras.",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**poder** is the modal 'can/be able' (puedo ir = I can go). **volver** means 'to come back' or 'to return'. Both are workhorses in spoken Spanish.",
        },
        {
            "kind": "mini_table",
            "title": "poder (to be able to)",
            "rows": [
            ["yo", "p|uedo"],
            ["tú", "p|uedes"],
            ["él / ella / usted", "p|uede"],
            ["nosotros / nosotras", "pod|emos"],
            ["ellos / ellas / ustedes", "p|ueden"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "volver (to return)",
            "rows": [
            ["yo", "v|uelvo"],
            ["tú", "v|uelves"],
            ["él / ella / usted", "v|uelve"],
            ["nosotros / nosotras", "volv|emos"],
            ["ellos / ellas / ustedes", "v|uelven"],
            ],
        },
    ],
    "recall": [
        {"verb": "poder", "answers": {"yo": "p|uedo", "tú": "p|uedes", "él": "p|uede", "nosotros": "pod|emos", "ellos": "p|ueden"}},
        {"verb": "volver", "answers": {"yo": "v|uelvo", "tú": "v|uelves", "él": "v|uelve", "nosotros": "volv|emos", "ellos": "v|uelven"}},
    ],
}

PRESENT_O_UE_DORMIR_MORIR_INTRO = {
    "kind": "cards",
    "title": "Stem o→ue — dormir + morir",
    "cards": [
        {
            "kind": "text",
            "title": "dormir + morir",
            "body": "**dormir** (to sleep) and **morir** (to die) are the only two -ir o→ue stem-changers. Pattern: d**ue**rmo, m**ue**ro; nosotros stays unchanged (dormimos, morimos).",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "Both share an extra quirk in the preterite (durmió, murió) — but in present they follow the standard o→ue pattern.",
        },
        {
            "kind": "mini_table",
            "title": "dormir (to sleep)",
            "rows": [
            ["yo", "d|uermo"],
            ["tú", "d|uermes"],
            ["él / ella / usted", "d|uerme"],
            ["nosotros / nosotras", "dorm|imos"],
            ["ellos / ellas / ustedes", "d|uermen"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "morir (to die)",
            "rows": [
            ["yo", "m|uero"],
            ["tú", "m|ueres"],
            ["él / ella / usted", "m|uere"],
            ["nosotros / nosotras", "mor|imos"],
            ["ellos / ellas / ustedes", "m|ueren"],
            ],
        },
    ],
    "recall": [
        {"verb": "dormir", "answers": {"yo": "d|uermo", "tú": "d|uermes", "él": "d|uerme", "nosotros": "dorm|imos", "ellos": "d|uermen"}},
        {"verb": "morir", "answers": {"yo": "m|uero", "tú": "m|ueres", "él": "m|uere", "nosotros": "mor|imos", "ellos": "m|ueren"}},
    ],
}

PRESENT_O_UE_MOVER_ALMORZAR_INTRO = {
    "kind": "cards",
    "title": "Stem o→ue — mover + almorzar",
    "cards": [
        {
            "kind": "text",
            "title": "mover + almorzar",
            "body": "**mover** (to move) and **almorzar** (to have lunch) follow the standard o→ue pattern. m**ue**vo, alm**ue**rzo; nosotros forms (movemos, almorzamos) stay regular.",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "almorzar is built on **almuerzo** (the noun for 'lunch'). Many other -ar verbs follow this pattern: contar, encontrar, recordar.",
        },
        {
            "kind": "mini_table",
            "title": "mover (to move)",
            "rows": [
            ["yo", "m|uevo"],
            ["tú", "m|ueves"],
            ["él / ella / usted", "m|ueve"],
            ["nosotros / nosotras", "mov|emos"],
            ["ellos / ellas / ustedes", "m|ueven"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "almorzar (to have lunch)",
            "rows": [
            ["yo", "alm|uerzo"],
            ["tú", "alm|uerzas"],
            ["él / ella / usted", "alm|uerza"],
            ["nosotros / nosotras", "almorz|amos"],
            ["ellos / ellas / ustedes", "alm|uerzan"],
            ],
        },
    ],
    "recall": [
        {"verb": "mover", "answers": {"yo": "m|uevo", "tú": "m|ueves", "él": "m|ueve", "nosotros": "mov|emos", "ellos": "m|ueven"}},
        {"verb": "almorzar", "answers": {"yo": "alm|uerzo", "tú": "alm|uerzas", "él": "alm|uerza", "nosotros": "almorz|amos", "ellos": "alm|uerzan"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_present_o_ue_poder_volver_1": {
        "title": "Stem o→ue — poder + volver (1/2)",
        "grammar_level": 6,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["poder", "volver"],
        "video_embed_id": "9JFpAFFVQzc",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_O_UE_PODER_VOLVER_INTRO,
        "rule_chart": PRESENT_O_UE_RULE,
        "drill_config": {
            "answers": {
                "poder": {"yo": "p|uedo", "tú": "p|uedes", "él": "p|uede", "ella": "p|uede", "usted": "p|uede", "nosotros": "pod|emos", "nosotras": "pod|emos", "ellos": "p|ueden", "ellas": "p|ueden", "ustedes": "p|ueden"},
                "volver": {"yo": "v|uelvo", "tú": "v|uelves", "él": "v|uelve", "ella": "v|uelve", "usted": "v|uelve", "nosotros": "volv|emos", "nosotras": "volv|emos", "ellos": "v|uelven", "ellas": "v|uelven", "ustedes": "v|uelven"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I can swim well", "es": "Yo puedo nadar bien", "noun_id": None, "type": "written", "glosses": {"well": "bien", "bien": "well"}},
            {"en": "You can open the door", "es": "Tú puedes abrir la puerta", "noun_id": None, "type": "auditory", "glosses": {"door": "puerta", "puerta": "door"}},
            {"en": "She can read the book", "es": "Ella puede leer el libro", "noun_id": None, "type": "written", "glosses": {"book": "libro", "libro": "book"}},
            {"en": "We (f) can speak Spanish", "es": "Nosotras podemos hablar español", "noun_id": None, "type": "auditory", "glosses": {"spanish": "español", "español": "spanish"}},
            {"en": "You all can eat lunch", "es": "Ustedes pueden comer el almuerzo", "noun_id": None, "type": "written", "glosses": {"lunch": "almuerzo", "almuerzo": "lunch"}},
            {"en": "I return home late", "es": "Yo vuelvo a casa tarde", "noun_id": None, "type": "written", "glosses": {"home": "casa", "late": "tarde", "casa": "home", "tarde": "late"}},
            {"en": "You return every day", "es": "Tú vuelves todos los días", "noun_id": None, "type": "auditory", "glosses": {"day": "días", "every": "todos", "días": "day", "todos": "every"}},
            {"en": "She returns from school", "es": "Ella vuelve de la escuela", "noun_id": None, "type": "written", "glosses": {"school": "escuela", "escuela": "school"}},
            {"en": "We (f) return at five", "es": "Nosotras volvemos a las cinco", "noun_id": None, "type": "auditory", "glosses": {"five": "cinco", "cinco": "five"}},
            {"en": "You all return now", "es": "Ustedes vuelven ahora", "noun_id": None, "type": "written", "glosses": {"now": "ahora", "ahora": "now"}},
        ],
        "drill_targets": [{"verb": "poder", "pronoun": "yo"}, {"verb": "poder", "pronoun": "tú"}, {"verb": "poder", "pronoun": "ella"}, {"verb": "poder", "pronoun": "nosotras"}, {"verb": "poder", "pronoun": "ustedes"}, {"verb": "volver", "pronoun": "yo"}, {"verb": "volver", "pronoun": "tú"}, {"verb": "volver", "pronoun": "ella"}, {"verb": "volver", "pronoun": "nosotras"}, {"verb": "volver", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem o→ue poder + volver (1/2): poder, volver",
            "targets": [{"verb": "poder", "pronoun": "yo"}, {"verb": "poder", "pronoun": "tú"}, {"verb": "poder", "pronoun": "ella"}, {"verb": "poder", "pronoun": "nosotras"}, {"verb": "poder", "pronoun": "ustedes"}, {"verb": "volver", "pronoun": "yo"}, {"verb": "volver", "pronoun": "tú"}, {"verb": "volver", "pronoun": "ella"}, {"verb": "volver", "pronoun": "nosotras"}, {"verb": "volver", "pronoun": "ustedes"}],
        },
        "opener_en": "Can you help me?",
        "opener_es": "¿Puedes ayudarme?",
    },

    "grammar_present_o_ue_poder_volver_2": {
        "title": "Stem o→ue — poder + volver (2/2)",
        "grammar_level": 6,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["poder", "volver"],
        "video_embed_id": "9JFpAFFVQzc",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_O_UE_RULE,
        "drill_config": {
            "answers": {
                "poder": {"yo": "p|uedo", "tú": "p|uedes", "él": "p|uede", "ella": "p|uede", "usted": "p|uede", "nosotros": "pod|emos", "nosotras": "pod|emos", "ellos": "p|ueden", "ellas": "p|ueden", "ustedes": "p|ueden"},
                "volver": {"yo": "v|uelvo", "tú": "v|uelves", "él": "v|uelve", "ella": "v|uelve", "usted": "v|uelve", "nosotros": "volv|emos", "nosotras": "volv|emos", "ellos": "v|uelven", "ellas": "v|uelven", "ustedes": "v|uelven"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You can speak Spanish.", "es": "Tú puedes hablar español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "spanish": "español", "español": "Spanish"}},
            {"en": "I can read the book.", "es": "Yo puedo leer el libro.", "noun_id": None, "type": "auditory", "glosses": {"book": "libro", "libro": "book"}},
            {"en": "He can open the door.", "es": "Él puede abrir la puerta.", "noun_id": None, "type": "written", "glosses": {"door": "puerta", "puerta": "door"}},
            {"en": "We (m) can eat lunch.", "es": "Nosotros podemos comer el almuerzo.", "noun_id": None, "type": "auditory", "glosses": {"lunch": "almuerzo", "almuerzo": "lunch"}},
            {"en": "They (f) can run fast.", "es": "Ellas pueden correr rápido.", "noun_id": None, "type": "written", "glosses": {"fast": "rápido", "rápido": "fast"}},
            {"en": "You return home early.", "es": "Tú vuelves a casa temprano.", "noun_id": None, "type": "written", "glosses": {"home": "casa", "casa": "home", "early": "temprano", "temprano": "early"}},
            {"en": "I return to the park.", "es": "Yo vuelvo al parque.", "noun_id": None, "type": "auditory", "glosses": {"park": "parque", "parque": "park"}},
            {"en": "He returns the book today.", "es": "Él vuelve el libro hoy.", "noun_id": None, "type": "written", "glosses": {"book": "libro", "libro": "book", "today": "hoy", "hoy": "today"}},
            {"en": "We (m) return with friends.", "es": "Nosotros volvemos con amigos.", "noun_id": None, "type": "auditory", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "They (f) return late.", "es": "Ellas vuelven tarde.", "noun_id": None, "type": "written", "glosses": {"late": "tarde", "tarde": "late"}},
        ],
        "drill_targets": [{"verb": "poder", "pronoun": "tú"}, {"verb": "poder", "pronoun": "yo"}, {"verb": "poder", "pronoun": "él"}, {"verb": "poder", "pronoun": "nosotros"}, {"verb": "poder", "pronoun": "ellas"}, {"verb": "volver", "pronoun": "tú"}, {"verb": "volver", "pronoun": "yo"}, {"verb": "volver", "pronoun": "él"}, {"verb": "volver", "pronoun": "nosotros"}, {"verb": "volver", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem o→ue poder + volver (2/2): poder, volver",
            "targets": [{"verb": "poder", "pronoun": "tú"}, {"verb": "poder", "pronoun": "yo"}, {"verb": "poder", "pronoun": "él"}, {"verb": "poder", "pronoun": "nosotros"}, {"verb": "poder", "pronoun": "ellas"}, {"verb": "volver", "pronoun": "tú"}, {"verb": "volver", "pronoun": "yo"}, {"verb": "volver", "pronoun": "él"}, {"verb": "volver", "pronoun": "nosotros"}, {"verb": "volver", "pronoun": "ellas"}],
        },
        "opener_en": "When do you come back?",
        "opener_es": "¿Cuándo vuelves?",
    },

    "grammar_present_o_ue_dormir_morir_1": {
        "title": "Stem o→ue — dormir + morir (1/2)",
        "grammar_level": 6,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["dormir", "morir"],
        "video_embed_id": "9JFpAFFVQzc",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_O_UE_DORMIR_MORIR_INTRO,
        "rule_chart": PRESENT_O_UE_RULE,
        "drill_config": {
            "answers": {
                "dormir": {"yo": "d|uermo", "tú": "d|uermes", "él": "d|uerme", "ella": "d|uerme", "usted": "d|uerme", "nosotros": "dorm|imos", "nosotras": "dorm|imos", "ellos": "d|uermen", "ellas": "d|uermen", "ustedes": "d|uermen"},
                "morir": {"yo": "m|uero", "tú": "m|ueres", "él": "m|uere", "ella": "m|uere", "usted": "m|uere", "nosotros": "mor|imos", "nosotras": "mor|imos", "ellos": "m|ueren", "ellas": "m|ueren", "ustedes": "m|ueren"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I sleep well every night.", "es": "Yo duermo bien cada noche.", "noun_id": None, "type": "written", "glosses": {"night": "noche", "bien": "well", "every": "cada", "noche": "night", "well": "bien", "cada": "every"}},
            {"en": "You sleep early today.", "es": "Tú duermes temprano hoy.", "noun_id": None, "type": "auditory", "glosses": {"today": "hoy", "early": "temprano", "hoy": "today", "temprano": "early"}},
            {"en": "She sleeps in the bedroom.", "es": "Ella duerme en el dormitorio.", "noun_id": None, "type": "written", "glosses": {"bedroom": "dormitorio", "dormitorio": "bedroom"}},
            {"en": "We (f) sleep eight hours.", "es": "Nosotras dormimos ocho horas.", "noun_id": None, "type": "auditory", "glosses": {"hours": "horas", "eight": "ocho", "horas": "hours", "ocho": "eight"}},
            {"en": "You all sleep during the day.", "es": "Ustedes duermen durante el día.", "noun_id": None, "type": "written", "glosses": {"day": "día", "all": "all", "día": "day"}},
            {"en": "I die in the story.", "es": "Yo muero en la historia.", "noun_id": None, "type": "written", "glosses": {"story": "historia", "historia": "story"}},
            {"en": "You die in the movie.", "es": "Tú mueres en la película.", "noun_id": None, "type": "auditory", "glosses": {"movie": "película", "película": "movie"}},
            {"en": "She dies at the end.", "es": "Ella muere al final.", "noun_id": None, "type": "written", "glosses": {"end": "final", "final": "end"}},
            {"en": "We (f) die in the legend.", "es": "Nosotras morimos en la leyenda.", "noun_id": None, "type": "auditory", "glosses": {"legend": "leyenda", "leyenda": "legend"}},
            {"en": "You all die in the game.", "es": "Ustedes mueren en el juego.", "noun_id": None, "type": "written", "glosses": {"game": "juego", "juego": "game"}},
        ],
        "drill_targets": [{"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "ella"}, {"verb": "dormir", "pronoun": "nosotras"}, {"verb": "dormir", "pronoun": "ustedes"}, {"verb": "morir", "pronoun": "yo"}, {"verb": "morir", "pronoun": "tú"}, {"verb": "morir", "pronoun": "ella"}, {"verb": "morir", "pronoun": "nosotras"}, {"verb": "morir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem o→ue dormir + morir (1/2): dormir, morir",
            "targets": [{"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "ella"}, {"verb": "dormir", "pronoun": "nosotras"}, {"verb": "dormir", "pronoun": "ustedes"}, {"verb": "morir", "pronoun": "yo"}, {"verb": "morir", "pronoun": "tú"}, {"verb": "morir", "pronoun": "ella"}, {"verb": "morir", "pronoun": "nosotras"}, {"verb": "morir", "pronoun": "ustedes"}],
        },
        "opener_en": "Do you sleep well?",
        "opener_es": "¿Duermes bien?",
    },

    "grammar_present_o_ue_dormir_morir_2": {
        "title": "Stem o→ue — dormir + morir (2/2)",
        "grammar_level": 6,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["dormir", "morir"],
        "video_embed_id": "9JFpAFFVQzc",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_O_UE_RULE,
        "drill_config": {
            "answers": {
                "dormir": {"yo": "d|uermo", "tú": "d|uermes", "él": "d|uerme", "ella": "d|uerme", "usted": "d|uerme", "nosotros": "dorm|imos", "nosotras": "dorm|imos", "ellos": "d|uermen", "ellas": "d|uermen", "ustedes": "d|uermen"},
                "morir": {"yo": "m|uero", "tú": "m|ueres", "él": "m|uere", "ella": "m|uere", "usted": "m|uere", "nosotros": "mor|imos", "nosotras": "mor|imos", "ellos": "m|ueren", "ellas": "m|ueren", "ustedes": "m|ueren"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You sleep well.", "es": "Tú duermes bien.", "noun_id": None, "type": "written", "glosses": {"well": "bien", "bien": "well"}},
            {"en": "I sleep eight hours.", "es": "Yo duermo ocho horas.", "noun_id": None, "type": "auditory", "glosses": {"hours": "horas", "eight": "ocho", "horas": "hours", "ocho": "eight"}},
            {"en": "He sleeps in the room.", "es": "Él duerme en la habitación.", "noun_id": None, "type": "written", "glosses": {"room": "habitación", "habitación": "room"}},
            {"en": "We (m) sleep early.", "es": "Nosotros dormimos temprano.", "noun_id": None, "type": "auditory", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "They (f) sleep deeply.", "es": "Ellas duermen profundamente.", "noun_id": None, "type": "written", "glosses": {"deeply": "profundamente", "profundamente": "deeply"}},
            {"en": "You die young.", "es": "Tú mueres joven.", "noun_id": None, "type": "written", "glosses": {"young": "joven", "joven": "young"}},
            {"en": "I die old.", "es": "Yo muero viejo.", "noun_id": None, "type": "auditory", "glosses": {"old": "viejo", "viejo": "old"}},
            {"en": "He dies peacefully.", "es": "Él muere pacíficamente.", "noun_id": None, "type": "written", "glosses": {"peacefully": "pacíficamente", "pacíficamente": "peacefully"}},
            {"en": "We (m) die bravely.", "es": "Nosotros morimos valientemente.", "noun_id": None, "type": "auditory", "glosses": {"bravely": "valientemente", "valientemente": "bravely"}},
            {"en": "They (f) die quietly.", "es": "Ellas mueren silenciosamente.", "noun_id": None, "type": "written", "glosses": {"quietly": "silenciosamente", "silenciosamente": "quietly"}},
        ],
        "drill_targets": [{"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "él"}, {"verb": "dormir", "pronoun": "nosotros"}, {"verb": "dormir", "pronoun": "ellas"}, {"verb": "morir", "pronoun": "tú"}, {"verb": "morir", "pronoun": "yo"}, {"verb": "morir", "pronoun": "él"}, {"verb": "morir", "pronoun": "nosotros"}, {"verb": "morir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem o→ue dormir + morir (2/2): dormir, morir",
            "targets": [{"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "él"}, {"verb": "dormir", "pronoun": "nosotros"}, {"verb": "dormir", "pronoun": "ellas"}, {"verb": "morir", "pronoun": "tú"}, {"verb": "morir", "pronoun": "yo"}, {"verb": "morir", "pronoun": "él"}, {"verb": "morir", "pronoun": "nosotros"}, {"verb": "morir", "pronoun": "ellas"}],
        },
        "opener_en": "Are you dying of hunger?",
        "opener_es": "¿Te mueres de hambre?",
    },

    "grammar_present_o_ue_mover_almorzar_1": {
        "title": "Stem o→ue — mover + almorzar (1/2)",
        "grammar_level": 6,
        "lesson_number": 5,
        "lesson_type": "conjugation",
        "word_workload": ["mover", "almorzar"],
        "video_embed_id": "9JFpAFFVQzc",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_O_UE_MOVER_ALMORZAR_INTRO,
        "rule_chart": PRESENT_O_UE_RULE,
        "drill_config": {
            "answers": {
                "mover": {"yo": "m|uevo", "tú": "m|ueves", "él": "m|ueve", "ella": "m|ueve", "usted": "m|ueve", "nosotros": "mov|emos", "nosotras": "mov|emos", "ellos": "m|ueven", "ellas": "m|ueven", "ustedes": "m|ueven"},
                "almorzar": {"yo": "alm|uerzo", "tú": "alm|uerzas", "él": "alm|uerza", "ella": "alm|uerza", "usted": "alm|uerza", "nosotros": "almorz|amos", "nosotras": "almorz|amos", "ellos": "alm|uerzan", "ellas": "alm|uerzan", "ustedes": "alm|uerzan"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I move the table.", "es": "Yo muevo la mesa.", "noun_id": None, "type": "written", "glosses": {"table": "mesa", "mesa": "table"}},
            {"en": "You move the chair.", "es": "Tú mueves la silla.", "noun_id": None, "type": "auditory", "glosses": {"chair": "silla", "silla": "chair"}},
            {"en": "She moves the box.", "es": "Ella mueve la caja.", "noun_id": None, "type": "written", "glosses": {"box": "caja", "caja": "box"}},
            {"en": "We (f) move the books.", "es": "Nosotras movemos los libros.", "noun_id": None, "type": "auditory", "glosses": {"books": "libros", "libros": "books"}},
            {"en": "You all move the furniture.", "es": "Ustedes mueven los muebles.", "noun_id": None, "type": "written", "glosses": {"furniture": "muebles", "muebles": "furniture"}},
            {"en": "I have lunch at noon.", "es": "Yo almuerzo al mediodía.", "noun_id": None, "type": "written", "glosses": {"noon": "mediodía", "mediodía": "noon"}},
            {"en": "You have lunch with friends.", "es": "Tú almuerzas con amigos.", "noun_id": None, "type": "auditory", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "She has lunch at the park.", "es": "Ella almuerza en el parque.", "noun_id": None, "type": "written", "glosses": {"park": "parque", "parque": "park"}},
            {"en": "We (f) have lunch early.", "es": "Nosotras almorzamos temprano.", "noun_id": None, "type": "auditory", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "You all have lunch together.", "es": "Ustedes almuerzan juntos.", "noun_id": None, "type": "written", "glosses": {"together": "juntos", "juntos": "together"}},
        ],
        "drill_targets": [{"verb": "mover", "pronoun": "yo"}, {"verb": "mover", "pronoun": "tú"}, {"verb": "mover", "pronoun": "ella"}, {"verb": "mover", "pronoun": "nosotras"}, {"verb": "mover", "pronoun": "ustedes"}, {"verb": "almorzar", "pronoun": "yo"}, {"verb": "almorzar", "pronoun": "tú"}, {"verb": "almorzar", "pronoun": "ella"}, {"verb": "almorzar", "pronoun": "nosotras"}, {"verb": "almorzar", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem o→ue mover + almorzar (1/2): mover, almorzar",
            "targets": [{"verb": "mover", "pronoun": "yo"}, {"verb": "mover", "pronoun": "tú"}, {"verb": "mover", "pronoun": "ella"}, {"verb": "mover", "pronoun": "nosotras"}, {"verb": "mover", "pronoun": "ustedes"}, {"verb": "almorzar", "pronoun": "yo"}, {"verb": "almorzar", "pronoun": "tú"}, {"verb": "almorzar", "pronoun": "ella"}, {"verb": "almorzar", "pronoun": "nosotras"}, {"verb": "almorzar", "pronoun": "ustedes"}],
        },
        "opener_en": "Do you move the chair?",
        "opener_es": "¿Mueves la silla?",
    },

    "grammar_present_o_ue_mover_almorzar_2": {
        "title": "Stem o→ue — mover + almorzar (2/2)",
        "grammar_level": 6,
        "lesson_number": 6,
        "lesson_type": "conjugation",
        "word_workload": ["mover", "almorzar"],
        "video_embed_id": "9JFpAFFVQzc",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_O_UE_RULE,
        "drill_config": {
            "answers": {
                "mover": {"yo": "m|uevo", "tú": "m|ueves", "él": "m|ueve", "ella": "m|ueve", "usted": "m|ueve", "nosotros": "mov|emos", "nosotras": "mov|emos", "ellos": "m|ueven", "ellas": "m|ueven", "ustedes": "m|ueven"},
                "almorzar": {"yo": "alm|uerzo", "tú": "alm|uerzas", "él": "alm|uerza", "ella": "alm|uerza", "usted": "alm|uerza", "nosotros": "almorz|amos", "nosotras": "almorz|amos", "ellos": "alm|uerzan", "ellas": "alm|uerzan", "ustedes": "alm|uerzan"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You move the table.", "es": "Tú mueves la mesa.", "noun_id": None, "type": "written", "glosses": {"table": "mesa", "mesa": "table"}},
            {"en": "I move the chair.", "es": "Yo muevo la silla.", "noun_id": None, "type": "auditory", "glosses": {"chair": "silla", "silla": "chair"}},
            {"en": "He moves the box.", "es": "Él mueve la caja.", "noun_id": None, "type": "written", "glosses": {"box": "caja", "caja": "box"}},
            {"en": "We (m) move the sofa.", "es": "Nosotros movemos el sofá.", "noun_id": None, "type": "auditory", "glosses": {"sofa": "sofá", "sofá": "sofa"}},
            {"en": "They (f) move the books.", "es": "Ellas mueven los libros.", "noun_id": None, "type": "written", "glosses": {"books": "libros", "libros": "books"}},
            {"en": "You have lunch at noon.", "es": "Tú almuerzas al mediodía.", "noun_id": None, "type": "written", "glosses": {"noon": "mediodía", "mediodía": "noon"}},
            {"en": "I have lunch with friends.", "es": "Yo almuerzo con amigos.", "noun_id": None, "type": "auditory", "glosses": {"friends": "amigos", "amigos": "friends"}},
            {"en": "He has lunch in the park.", "es": "Él almuerza en el parque.", "noun_id": None, "type": "written", "glosses": {"park": "parque", "parque": "park"}},
            {"en": "We (m) have lunch early.", "es": "Nosotros almorzamos temprano.", "noun_id": None, "type": "auditory", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "They (f) have lunch together.", "es": "Ellas almuerzan juntas.", "noun_id": None, "type": "written", "glosses": {"together": "juntas", "juntas": "together"}},
        ],
        "drill_targets": [{"verb": "mover", "pronoun": "tú"}, {"verb": "mover", "pronoun": "yo"}, {"verb": "mover", "pronoun": "él"}, {"verb": "mover", "pronoun": "nosotros"}, {"verb": "mover", "pronoun": "ellas"}, {"verb": "almorzar", "pronoun": "tú"}, {"verb": "almorzar", "pronoun": "yo"}, {"verb": "almorzar", "pronoun": "él"}, {"verb": "almorzar", "pronoun": "nosotros"}, {"verb": "almorzar", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem o→ue mover + almorzar (2/2): mover, almorzar",
            "targets": [{"verb": "mover", "pronoun": "tú"}, {"verb": "mover", "pronoun": "yo"}, {"verb": "mover", "pronoun": "él"}, {"verb": "mover", "pronoun": "nosotros"}, {"verb": "mover", "pronoun": "ellas"}, {"verb": "almorzar", "pronoun": "tú"}, {"verb": "almorzar", "pronoun": "yo"}, {"verb": "almorzar", "pronoun": "él"}, {"verb": "almorzar", "pronoun": "nosotros"}, {"verb": "almorzar", "pronoun": "ellas"}],
        },
        "opener_en": "Where do you have lunch?",
        "opener_es": "¿Dónde almuerzas?",
    },

    "grammar_present_o_ue_poder_volver_chat": {
        "title": "Stem o→ue — poder + volver Chat",
        "grammar_level": 6,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["poder", "volver"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem o→ue poder + volver chat: poder, volver", "targets": [{"verb": "poder", "pronoun": "yo"}, {"verb": "poder", "pronoun": "tú"}, {"verb": "poder", "pronoun": "ella"}, {"verb": "poder", "pronoun": "nosotras"}, {"verb": "poder", "pronoun": "ustedes"}, {"verb": "volver", "pronoun": "tú"}, {"verb": "volver", "pronoun": "yo"}, {"verb": "volver", "pronoun": "él"}, {"verb": "volver", "pronoun": "nosotros"}, {"verb": "volver", "pronoun": "ellas"}]},
    },

    "grammar_present_o_ue_dormir_morir_chat": {
        "title": "Stem o→ue — dormir + morir Chat",
        "grammar_level": 6,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["dormir", "morir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem o→ue dormir + morir chat: dormir, morir", "targets": [{"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "ella"}, {"verb": "dormir", "pronoun": "nosotras"}, {"verb": "dormir", "pronoun": "ustedes"}, {"verb": "morir", "pronoun": "tú"}, {"verb": "morir", "pronoun": "yo"}, {"verb": "morir", "pronoun": "él"}, {"verb": "morir", "pronoun": "nosotros"}, {"verb": "morir", "pronoun": "ellas"}]},
    },

    "grammar_present_o_ue_mover_almorzar_chat": {
        "title": "Stem o→ue — mover + almorzar Chat",
        "grammar_level": 6,
        "lesson_number": 6.5,
        "lesson_type": "conjugation",
        "word_workload": ["mover", "almorzar"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem o→ue mover + almorzar chat: mover, almorzar", "targets": [{"verb": "mover", "pronoun": "yo"}, {"verb": "mover", "pronoun": "tú"}, {"verb": "mover", "pronoun": "ella"}, {"verb": "mover", "pronoun": "nosotras"}, {"verb": "mover", "pronoun": "ustedes"}, {"verb": "almorzar", "pronoun": "tú"}, {"verb": "almorzar", "pronoun": "yo"}, {"verb": "almorzar", "pronoun": "él"}, {"verb": "almorzar", "pronoun": "nosotros"}, {"verb": "almorzar", "pronoun": "ellas"}]},
    },
