"""Auto-generated by scripts/split_gl7.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_present_e_ie_{1,2,3}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

PRESENT_E_IE_QUERER_PENSAR_INTRO = {
    "kind": "cards",
    "title": "Stem e→ie — querer + pensar",
    "cards": [
        {
            "kind": "text",
            "title": "querer + pensar",
            "body": "**e → ie** in stressed syllables: qu**ie**ro, p**ie**nso. Nosotros / nosotras stay regular (queremos, pensamos).",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**querer** is 'to want' (and 'to love' with people). **pensar** is 'to think' or 'to plan' (pienso ir = I plan to go).",
        },
        {
            "kind": "mini_table",
            "title": "querer (to want)",
            "rows": [
            ["yo", "qu|iero"],
            ["tú", "qu|ieres"],
            ["él / ella / usted", "qu|iere"],
            ["nosotros / nosotras", "quer|emos"],
            ["ellos / ellas / ustedes", "qu|ieren"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "pensar (to think)",
            "rows": [
            ["yo", "p|ienso"],
            ["tú", "p|iensas"],
            ["él / ella / usted", "p|iensa"],
            ["nosotros / nosotras", "pens|amos"],
            ["ellos / ellas / ustedes", "p|iensan"],
            ],
        },
    ],
    "recall": [
        {"verb": "querer", "answers": {"yo": "qu|iero", "tú": "qu|ieres", "él": "qu|iere", "nosotros": "quer|emos", "ellos": "qu|ieren"}},
        {"verb": "pensar", "answers": {"yo": "p|ienso", "tú": "p|iensas", "él": "p|iensa", "nosotros": "pens|amos", "ellos": "p|iensan"}},
    ],
}

PRESENT_E_IE_CERRAR_EMPEZAR_INTRO = {
    "kind": "cards",
    "title": "Stem e→ie — cerrar + empezar",
    "cards": [
        {
            "kind": "text",
            "title": "cerrar + empezar",
            "body": "Same e → ie pattern: c**ie**rro, emp**ie**zo. The **z** in empezar / empiezo is part of the stem; no spelling change needed in present tense.",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**cerrar** is 'to close' (a door, a deal). **empezar** is 'to begin'; followed by *a + infinitive* (empiezo a trabajar = I'm starting to work).",
        },
        {
            "kind": "mini_table",
            "title": "cerrar (to close)",
            "rows": [
            ["yo", "c|ierro"],
            ["tú", "c|ierras"],
            ["él / ella / usted", "c|ierra"],
            ["nosotros / nosotras", "cerr|amos"],
            ["ellos / ellas / ustedes", "c|ierran"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "empezar (to begin)",
            "rows": [
            ["yo", "emp|iezo"],
            ["tú", "emp|iezas"],
            ["él / ella / usted", "emp|ieza"],
            ["nosotros / nosotras", "empez|amos"],
            ["ellos / ellas / ustedes", "emp|iezan"],
            ],
        },
    ],
    "recall": [
        {"verb": "cerrar", "answers": {"yo": "c|ierro", "tú": "c|ierras", "él": "c|ierra", "nosotros": "cerr|amos", "ellos": "c|ierran"}},
        {"verb": "empezar", "answers": {"yo": "emp|iezo", "tú": "emp|iezas", "él": "emp|ieza", "nosotros": "empez|amos", "ellos": "emp|iezan"}},
    ],
}

PRESENT_E_IE_ENTENDER_PREFERIR_INTRO = {
    "kind": "cards",
    "title": "Stem e→ie — entender + preferir",
    "cards": [
        {
            "kind": "text",
            "title": "entender + preferir",
            "body": "Same e → ie pattern: ent**ie**ndo, pref**ie**ro. **preferir** is one of the few -ir verbs in this group; it shares the change with sentir, mentir.",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**entender** is 'to understand' (synonym: comprender). **preferir** takes a noun or an infinitive: prefiero el café, prefiero salir.",
        },
        {
            "kind": "mini_table",
            "title": "entender (to understand)",
            "rows": [
            ["yo", "ent|iendo"],
            ["tú", "ent|iendes"],
            ["él / ella / usted", "ent|iende"],
            ["nosotros / nosotras", "entend|emos"],
            ["ellos / ellas / ustedes", "ent|ienden"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "preferir (to prefer)",
            "rows": [
            ["yo", "pref|iero"],
            ["tú", "pref|ieres"],
            ["él / ella / usted", "pref|iere"],
            ["nosotros / nosotras", "prefer|imos"],
            ["ellos / ellas / ustedes", "pref|ieren"],
            ],
        },
    ],
    "recall": [
        {"verb": "entender", "answers": {"yo": "ent|iendo", "tú": "ent|iendes", "él": "ent|iende", "nosotros": "entend|emos", "ellos": "ent|ienden"}},
        {"verb": "preferir", "answers": {"yo": "pref|iero", "tú": "pref|ieres", "él": "pref|iere", "nosotros": "prefer|imos", "ellos": "pref|ieren"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_present_e_ie_querer_pensar_1": {
        "title": "Stem e→ie — querer + pensar (1/2)",
        "grammar_level": 7,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["querer", "pensar"],
        "video_embed_id": "rk0AwBA9PEa",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_E_IE_QUERER_PENSAR_INTRO,
        "rule_chart": PRESENT_E_IE_RULE,
        "drill_config": {
            "answers": {
                "querer": {"yo": "qu|iero", "tú": "qu|ieres", "él": "qu|iere", "ella": "qu|iere", "usted": "qu|iere", "nosotros": "quer|emos", "nosotras": "quer|emos", "ellos": "qu|ieren", "ellas": "qu|ieren", "ustedes": "qu|ieren"},
                "pensar": {"yo": "p|ienso", "tú": "p|iensas", "él": "p|iensa", "ella": "p|iensa", "usted": "p|iensa", "nosotros": "pens|amos", "nosotras": "pens|amos", "ellos": "p|iensan", "ellas": "p|iensan", "ustedes": "p|iensan"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I want a red apple.", "es": "Yo quiero una manzana roja.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "manzana": "apple", "red": "roja", "roja": "red"}},
            {"en": "You want the big house.", "es": "Tú quieres la casa grande.", "noun_id": None, "type": "auditory", "glosses": {"house": "casa", "casa": "house", "big": "grande", "grande": "big"}},
            {"en": "She wants a new book.", "es": "Ella quiere un libro nuevo.", "noun_id": None, "type": "written", "glosses": {"book": "libro", "libro": "book", "new": "nuevo", "nuevo": "new"}},
            {"en": "We (f) want fresh water.", "es": "Nosotras queremos agua fresca.", "noun_id": None, "type": "auditory", "glosses": {"water": "agua", "agua": "water", "fresh": "fresca", "fresca": "fresh"}},
            {"en": "You (pl) want cold drinks.", "es": "Ustedes quieren bebidas frías.", "noun_id": None, "type": "written", "glosses": {"drink": "bebidas", "bebidas": "drink", "cold": "frías", "frías": "cold"}},
            {"en": "I think about the blue sky.", "es": "Yo pienso en el cielo azul.", "noun_id": None, "type": "written", "glosses": {"sky": "cielo", "cielo": "sky", "blue": "azul", "azul": "blue"}},
            {"en": "You think the movie is good.", "es": "Tú piensas que la película es buena.", "noun_id": None, "type": "auditory", "glosses": {"movie": "película", "película": "movie", "good": "buena", "buena": "good"}},
            {"en": "She thinks the city is big.", "es": "Ella piensa que la ciudad es grande.", "noun_id": None, "type": "written", "glosses": {"city": "ciudad", "ciudad": "city", "big": "grande", "grande": "big"}},
            {"en": "We (f) think about our friends.", "es": "Nosotras pensamos en nuestras amigas.", "noun_id": None, "type": "auditory", "glosses": {"friend": "amigas", "amigas": "friend", "our": "nuestras", "nuestras": "our"}},
            {"en": "You (pl) think the test is easy.", "es": "Ustedes piensan que el examen es fácil.", "noun_id": None, "type": "written", "glosses": {"test": "examen", "examen": "test", "easy": "fácil", "fácil": "easy"}},
        ],
        "drill_targets": [{"verb": "querer", "pronoun": "yo"}, {"verb": "querer", "pronoun": "tú"}, {"verb": "querer", "pronoun": "ella"}, {"verb": "querer", "pronoun": "nosotras"}, {"verb": "querer", "pronoun": "ustedes"}, {"verb": "pensar", "pronoun": "yo"}, {"verb": "pensar", "pronoun": "tú"}, {"verb": "pensar", "pronoun": "ella"}, {"verb": "pensar", "pronoun": "nosotras"}, {"verb": "pensar", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem e→ie querer + pensar (1/2): querer, pensar",
            "targets": [{"verb": "querer", "pronoun": "yo"}, {"verb": "querer", "pronoun": "tú"}, {"verb": "querer", "pronoun": "ella"}, {"verb": "querer", "pronoun": "nosotras"}, {"verb": "querer", "pronoun": "ustedes"}, {"verb": "pensar", "pronoun": "yo"}, {"verb": "pensar", "pronoun": "tú"}, {"verb": "pensar", "pronoun": "ella"}, {"verb": "pensar", "pronoun": "nosotras"}, {"verb": "pensar", "pronoun": "ustedes"}],
        },
        "opener_en": "What do you want?",
        "opener_es": "¿Qué quieres?",
    },

    "grammar_present_e_ie_querer_pensar_2": {
        "title": "Stem e→ie — querer + pensar (2/2)",
        "grammar_level": 7,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["querer", "pensar"],
        "video_embed_id": "rk0AwBA9PEa",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_E_IE_RULE,
        "drill_config": {
            "answers": {
                "querer": {"yo": "qu|iero", "tú": "qu|ieres", "él": "qu|iere", "ella": "qu|iere", "usted": "qu|iere", "nosotros": "quer|emos", "nosotras": "quer|emos", "ellos": "qu|ieren", "ellas": "qu|ieren", "ustedes": "qu|ieren"},
                "pensar": {"yo": "p|ienso", "tú": "p|iensas", "él": "p|iensa", "ella": "p|iensa", "usted": "p|iensa", "nosotros": "pens|amos", "nosotras": "pens|amos", "ellos": "p|iensan", "ellas": "p|iensan", "ustedes": "p|iensan"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You want a coffee.", "es": "Tú quieres un café.", "noun_id": None, "type": "written", "glosses": {"coffee": "café", "café": "coffee"}},
            {"en": "I want a new book.", "es": "Yo quiero un libro nuevo.", "noun_id": None, "type": "auditory", "glosses": {"book": "libro", "new": "nuevo", "libro": "book", "nuevo": "new"}},
            {"en": "He wants the red car.", "es": "Él quiere el coche rojo.", "noun_id": None, "type": "written", "glosses": {"car": "coche", "red": "rojo", "coche": "car", "rojo": "red"}},
            {"en": "We (m) want to eat now.", "es": "Nosotros queremos comer ahora.", "noun_id": None, "type": "auditory", "glosses": {"now": "ahora", "ahora": "now"}},
            {"en": "They (f) want big houses.", "es": "Ellas quieren casas grandes.", "noun_id": None, "type": "written", "glosses": {"houses": "casas", "big": "grande", "casas": "houses", "grande": "big"}},
            {"en": "You think the test is easy.", "es": "Tú piensas que el examen es fácil.", "noun_id": None, "type": "written", "glosses": {"test": "examen", "easy": "fácil", "examen": "test", "fácil": "easy"}},
            {"en": "I think about my family.", "es": "Yo pienso en mi familia.", "noun_id": None, "type": "auditory", "glosses": {"family": "familia", "familia": "family"}},
            {"en": "He thinks the movie is good.", "es": "Él piensa que la película es buena.", "noun_id": None, "type": "written", "glosses": {"movie": "película", "good": "buena", "película": "movie", "buena": "good"}},
            {"en": "We (m) think a lot.", "es": "Nosotros pensamos mucho.", "noun_id": None, "type": "auditory", "glosses": {"much": "mucho", "mucho": "much"}},
            {"en": "They (f) think the city is beautiful.", "es": "Ellas piensan que la ciudad es hermosa.", "noun_id": None, "type": "written", "glosses": {"city": "ciudad", "beautiful": "hermosa", "ciudad": "city", "hermosa": "beautiful"}},
        ],
        "drill_targets": [{"verb": "querer", "pronoun": "tú"}, {"verb": "querer", "pronoun": "yo"}, {"verb": "querer", "pronoun": "él"}, {"verb": "querer", "pronoun": "nosotros"}, {"verb": "querer", "pronoun": "ellas"}, {"verb": "pensar", "pronoun": "tú"}, {"verb": "pensar", "pronoun": "yo"}, {"verb": "pensar", "pronoun": "él"}, {"verb": "pensar", "pronoun": "nosotros"}, {"verb": "pensar", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem e→ie querer + pensar (2/2): querer, pensar",
            "targets": [{"verb": "querer", "pronoun": "tú"}, {"verb": "querer", "pronoun": "yo"}, {"verb": "querer", "pronoun": "él"}, {"verb": "querer", "pronoun": "nosotros"}, {"verb": "querer", "pronoun": "ellas"}, {"verb": "pensar", "pronoun": "tú"}, {"verb": "pensar", "pronoun": "yo"}, {"verb": "pensar", "pronoun": "él"}, {"verb": "pensar", "pronoun": "nosotros"}, {"verb": "pensar", "pronoun": "ellas"}],
        },
        "opener_en": "What are you thinking?",
        "opener_es": "¿Qué piensas?",
    },

    "grammar_present_e_ie_cerrar_empezar_1": {
        "title": "Stem e→ie — cerrar + empezar (1/2)",
        "grammar_level": 7,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["cerrar", "empezar"],
        "video_embed_id": "rk0AwBA9PEa",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_E_IE_CERRAR_EMPEZAR_INTRO,
        "rule_chart": PRESENT_E_IE_RULE,
        "drill_config": {
            "answers": {
                "cerrar": {"yo": "c|ierro", "tú": "c|ierras", "él": "c|ierra", "ella": "c|ierra", "usted": "c|ierra", "nosotros": "cerr|amos", "nosotras": "cerr|amos", "ellos": "c|ierran", "ellas": "c|ierran", "ustedes": "c|ierran"},
                "empezar": {"yo": "emp|iezo", "tú": "emp|iezas", "él": "emp|ieza", "ella": "emp|ieza", "usted": "emp|ieza", "nosotros": "empez|amos", "nosotras": "empez|amos", "ellos": "emp|iezan", "ellas": "emp|iezan", "ustedes": "emp|iezan"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I close the door", "es": "Yo cierro la puerta", "noun_id": None, "type": "written", "glosses": {"door": "puerta", "puerta": "door"}},
            {"en": "You close the window", "es": "Tú cierras la ventana", "noun_id": None, "type": "auditory", "glosses": {"window": "ventana", "ventana": "window"}},
            {"en": "She closes the shop", "es": "Ella cierra la tienda", "noun_id": None, "type": "written", "glosses": {"shop": "tienda", "tienda": "shop"}},
            {"en": "We (f) close the books", "es": "Nosotras cerramos los libros", "noun_id": None, "type": "auditory", "glosses": {"books": "libros", "libros": "books"}},
            {"en": "You all close the offices", "es": "Ustedes cierran las oficinas", "noun_id": None, "type": "written", "glosses": {"offices": "oficinas", "oficinas": "offices"}},
            {"en": "I begin the class", "es": "Yo empiezo la clase", "noun_id": None, "type": "written", "glosses": {"class": "clase", "clase": "class"}},
            {"en": "You begin the game", "es": "Tú empiezas el juego", "noun_id": None, "type": "auditory", "glosses": {"game": "juego", "juego": "game"}},
            {"en": "She begins the meeting", "es": "Ella empieza la reunión", "noun_id": None, "type": "written", "glosses": {"meeting": "reunión", "reunión": "meeting"}},
            {"en": "We (f) begin the project", "es": "Nosotras empezamos el proyecto", "noun_id": None, "type": "auditory", "glosses": {"project": "proyecto", "proyecto": "project"}},
            {"en": "You all begin the exams", "es": "Ustedes empiezan los exámenes", "noun_id": None, "type": "written", "glosses": {"exams": "exámenes", "exámenes": "exams"}},
        ],
        "drill_targets": [{"verb": "cerrar", "pronoun": "yo"}, {"verb": "cerrar", "pronoun": "tú"}, {"verb": "cerrar", "pronoun": "ella"}, {"verb": "cerrar", "pronoun": "nosotras"}, {"verb": "cerrar", "pronoun": "ustedes"}, {"verb": "empezar", "pronoun": "yo"}, {"verb": "empezar", "pronoun": "tú"}, {"verb": "empezar", "pronoun": "ella"}, {"verb": "empezar", "pronoun": "nosotras"}, {"verb": "empezar", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem e→ie cerrar + empezar (1/2): cerrar, empezar",
            "targets": [{"verb": "cerrar", "pronoun": "yo"}, {"verb": "cerrar", "pronoun": "tú"}, {"verb": "cerrar", "pronoun": "ella"}, {"verb": "cerrar", "pronoun": "nosotras"}, {"verb": "cerrar", "pronoun": "ustedes"}, {"verb": "empezar", "pronoun": "yo"}, {"verb": "empezar", "pronoun": "tú"}, {"verb": "empezar", "pronoun": "ella"}, {"verb": "empezar", "pronoun": "nosotras"}, {"verb": "empezar", "pronoun": "ustedes"}],
        },
        "opener_en": "Do you close the windows?",
        "opener_es": "¿Cierras las ventanas?",
    },

    "grammar_present_e_ie_cerrar_empezar_2": {
        "title": "Stem e→ie — cerrar + empezar (2/2)",
        "grammar_level": 7,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["cerrar", "empezar"],
        "video_embed_id": "rk0AwBA9PEa",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_E_IE_RULE,
        "drill_config": {
            "answers": {
                "cerrar": {"yo": "c|ierro", "tú": "c|ierras", "él": "c|ierra", "ella": "c|ierra", "usted": "c|ierra", "nosotros": "cerr|amos", "nosotras": "cerr|amos", "ellos": "c|ierran", "ellas": "c|ierran", "ustedes": "c|ierran"},
                "empezar": {"yo": "emp|iezo", "tú": "emp|iezas", "él": "emp|ieza", "ella": "emp|ieza", "usted": "emp|ieza", "nosotros": "empez|amos", "nosotras": "empez|amos", "ellos": "emp|iezan", "ellas": "emp|iezan", "ustedes": "emp|iezan"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You close the door.", "es": "Tú cierras la puerta.", "noun_id": None, "type": "written", "glosses": {"door": "puerta", "puerta": "door"}},
            {"en": "I close the window.", "es": "Yo cierro la ventana.", "noun_id": None, "type": "auditory", "glosses": {"window": "ventana", "ventana": "window"}},
            {"en": "He closes the shop.", "es": "Él cierra la tienda.", "noun_id": None, "type": "written", "glosses": {"shop": "tienda", "tienda": "shop"}},
            {"en": "We close the books.", "es": "Nosotros cerramos los libros.", "noun_id": None, "type": "auditory", "glosses": {"books": "libros", "libros": "books"}},
            {"en": "They (f) close the schools.", "es": "Ellas cierran las escuelas.", "noun_id": None, "type": "written", "glosses": {"schools": "escuelas", "escuelas": "schools"}},
            {"en": "You begin the class.", "es": "Tú empiezas la clase.", "noun_id": None, "type": "written", "glosses": {"class": "clase", "clase": "class"}},
            {"en": "I begin the project.", "es": "Yo empiezo el proyecto.", "noun_id": None, "type": "auditory", "glosses": {"project": "proyecto", "proyecto": "project"}},
            {"en": "He begins the game.", "es": "Él empieza el juego.", "noun_id": None, "type": "written", "glosses": {"game": "juego", "juego": "game"}},
            {"en": "We begin the lesson.", "es": "Nosotros empezamos la lección.", "noun_id": None, "type": "auditory", "glosses": {"lesson": "lección", "lección": "lesson"}},
            {"en": "They (f) begin the meeting.", "es": "Ellas empiezan la reunión.", "noun_id": None, "type": "written", "glosses": {"meeting": "reunión", "reunión": "meeting"}},
        ],
        "drill_targets": [{"verb": "cerrar", "pronoun": "tú"}, {"verb": "cerrar", "pronoun": "yo"}, {"verb": "cerrar", "pronoun": "él"}, {"verb": "cerrar", "pronoun": "nosotros"}, {"verb": "cerrar", "pronoun": "ellas"}, {"verb": "empezar", "pronoun": "tú"}, {"verb": "empezar", "pronoun": "yo"}, {"verb": "empezar", "pronoun": "él"}, {"verb": "empezar", "pronoun": "nosotros"}, {"verb": "empezar", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem e→ie cerrar + empezar (2/2): cerrar, empezar",
            "targets": [{"verb": "cerrar", "pronoun": "tú"}, {"verb": "cerrar", "pronoun": "yo"}, {"verb": "cerrar", "pronoun": "él"}, {"verb": "cerrar", "pronoun": "nosotros"}, {"verb": "cerrar", "pronoun": "ellas"}, {"verb": "empezar", "pronoun": "tú"}, {"verb": "empezar", "pronoun": "yo"}, {"verb": "empezar", "pronoun": "él"}, {"verb": "empezar", "pronoun": "nosotros"}, {"verb": "empezar", "pronoun": "ellas"}],
        },
        "opener_en": "When do you start work?",
        "opener_es": "¿Cuándo empiezas a trabajar?",
    },

    "grammar_present_e_ie_entender_preferir_1": {
        "title": "Stem e→ie — entender + preferir (1/2)",
        "grammar_level": 7,
        "lesson_number": 5,
        "lesson_type": "conjugation",
        "word_workload": ["entender", "preferir"],
        "video_embed_id": "rk0AwBA9PEa",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_E_IE_ENTENDER_PREFERIR_INTRO,
        "rule_chart": PRESENT_E_IE_RULE,
        "drill_config": {
            "answers": {
                "entender": {"yo": "ent|iendo", "tú": "ent|iendes", "él": "ent|iende", "ella": "ent|iende", "usted": "ent|iende", "nosotros": "entend|emos", "nosotras": "entend|emos", "ellos": "ent|ienden", "ellas": "ent|ienden", "ustedes": "ent|ienden"},
                "preferir": {"yo": "pref|iero", "tú": "pref|ieres", "él": "pref|iere", "ella": "pref|iere", "usted": "pref|iere", "nosotros": "prefer|imos", "nosotras": "prefer|imos", "ellos": "pref|ieren", "ellas": "pref|ieren", "ustedes": "pref|ieren"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I understand the question.", "es": "Yo entiendo la pregunta.", "noun_id": None, "type": "written", "glosses": {"question": "pregunta", "pregunta": "question"}},
            {"en": "You understand the lesson.", "es": "Tú entiendes la lección.", "noun_id": None, "type": "auditory", "glosses": {"lesson": "lección", "lección": "lesson"}},
            {"en": "She understands the problem.", "es": "Ella entiende el problema.", "noun_id": None, "type": "written", "glosses": {"problem": "problema", "problema": "problem"}},
            {"en": "We (f) understand the explanation.", "es": "Nosotras entendemos la explicación.", "noun_id": None, "type": "auditory", "glosses": {"explanation": "explicación", "explicación": "explanation"}},
            {"en": "You all understand the rules.", "es": "Ustedes entienden las reglas.", "noun_id": None, "type": "written", "glosses": {"rules": "reglas", "reglas": "rules"}},
            {"en": "I prefer the red apple.", "es": "Yo prefiero la manzana roja.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "manzana": "apple", "red": "roja", "roja": "red"}},
            {"en": "You prefer cold water.", "es": "Tú prefieres el agua fría.", "noun_id": None, "type": "auditory", "glosses": {"water": "agua", "agua": "water", "cold": "fría", "fría": "cold"}},
            {"en": "She prefers the blue dress.", "es": "Ella prefiere el vestido azul.", "noun_id": None, "type": "written", "glosses": {"dress": "vestido", "vestido": "dress", "blue": "azul", "azul": "blue"}},
            {"en": "We (f) prefer quiet places.", "es": "Nosotras preferimos lugares tranquilos.", "noun_id": None, "type": "auditory", "glosses": {"places": "lugares", "lugares": "places", "quiet": "tranquilos", "tranquilos": "quiet"}},
            {"en": "You all prefer hot coffee.", "es": "Ustedes prefieren el café caliente.", "noun_id": None, "type": "written", "glosses": {"coffee": "café", "café": "coffee", "hot": "caliente", "caliente": "hot"}},
        ],
        "drill_targets": [{"verb": "entender", "pronoun": "yo"}, {"verb": "entender", "pronoun": "tú"}, {"verb": "entender", "pronoun": "ella"}, {"verb": "entender", "pronoun": "nosotras"}, {"verb": "entender", "pronoun": "ustedes"}, {"verb": "preferir", "pronoun": "yo"}, {"verb": "preferir", "pronoun": "tú"}, {"verb": "preferir", "pronoun": "ella"}, {"verb": "preferir", "pronoun": "nosotras"}, {"verb": "preferir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem e→ie entender + preferir (1/2): entender, preferir",
            "targets": [{"verb": "entender", "pronoun": "yo"}, {"verb": "entender", "pronoun": "tú"}, {"verb": "entender", "pronoun": "ella"}, {"verb": "entender", "pronoun": "nosotras"}, {"verb": "entender", "pronoun": "ustedes"}, {"verb": "preferir", "pronoun": "yo"}, {"verb": "preferir", "pronoun": "tú"}, {"verb": "preferir", "pronoun": "ella"}, {"verb": "preferir", "pronoun": "nosotras"}, {"verb": "preferir", "pronoun": "ustedes"}],
        },
        "opener_en": "Do you understand me?",
        "opener_es": "¿Me entiendes?",
    },

    "grammar_present_e_ie_entender_preferir_2": {
        "title": "Stem e→ie — entender + preferir (2/2)",
        "grammar_level": 7,
        "lesson_number": 6,
        "lesson_type": "conjugation",
        "word_workload": ["entender", "preferir"],
        "video_embed_id": "rk0AwBA9PEa",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_E_IE_RULE,
        "drill_config": {
            "answers": {
                "entender": {"yo": "ent|iendo", "tú": "ent|iendes", "él": "ent|iende", "ella": "ent|iende", "usted": "ent|iende", "nosotros": "entend|emos", "nosotras": "entend|emos", "ellos": "ent|ienden", "ellas": "ent|ienden", "ustedes": "ent|ienden"},
                "preferir": {"yo": "pref|iero", "tú": "pref|ieres", "él": "pref|iere", "ella": "pref|iere", "usted": "pref|iere", "nosotros": "prefer|imos", "nosotras": "prefer|imos", "ellos": "pref|ieren", "ellas": "pref|ieren", "ustedes": "pref|ieren"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You understand the question.", "es": "Tú entiendes la pregunta.", "noun_id": None, "type": "written", "glosses": {"question": "pregunta", "pregunta": "question"}},
            {"en": "I understand the lesson well.", "es": "Yo entiendo bien la lección.", "noun_id": None, "type": "auditory", "glosses": {"lesson": "lección", "lección": "lesson", "well": "bien", "bien": "well"}},
            {"en": "He understands the problem.", "es": "Él entiende el problema.", "noun_id": None, "type": "written", "glosses": {"problem": "problema", "problema": "problem"}},
            {"en": "We understand the instructions.", "es": "Nosotros entendemos las instrucciones.", "noun_id": None, "type": "auditory", "glosses": {"instructions": "instrucciones", "instrucciones": "instructions"}},
            {"en": "They (f) understand the rules.", "es": "Ellas entienden las reglas.", "noun_id": None, "type": "written", "glosses": {"rules": "reglas", "reglas": "rules"}},
            {"en": "You prefer the red shirt.", "es": "Tú prefieres la camisa roja.", "noun_id": None, "type": "written", "glosses": {"shirt": "camisa", "camisa": "shirt", "red": "roja", "roja": "red"}},
            {"en": "I prefer cold water.", "es": "Yo prefiero el agua fría.", "noun_id": None, "type": "auditory", "glosses": {"water": "agua", "agua": "water", "cold": "fría", "fría": "cold"}},
            {"en": "He prefers the blue jacket.", "es": "Él prefiere la chaqueta azul.", "noun_id": None, "type": "written", "glosses": {"jacket": "chaqueta", "chaqueta": "jacket", "blue": "azul", "azul": "blue"}},
            {"en": "We prefer the big house.", "es": "Nosotros preferimos la casa grande.", "noun_id": None, "type": "auditory", "glosses": {"house": "casa", "casa": "house", "big": "grande", "grande": "big"}},
            {"en": "They (f) prefer hot coffee.", "es": "Ellas prefieren el café caliente.", "noun_id": None, "type": "written", "glosses": {"coffee": "café", "café": "coffee", "hot": "caliente", "caliente": "hot"}},
        ],
        "drill_targets": [{"verb": "entender", "pronoun": "tú"}, {"verb": "entender", "pronoun": "yo"}, {"verb": "entender", "pronoun": "él"}, {"verb": "entender", "pronoun": "nosotros"}, {"verb": "entender", "pronoun": "ellas"}, {"verb": "preferir", "pronoun": "tú"}, {"verb": "preferir", "pronoun": "yo"}, {"verb": "preferir", "pronoun": "él"}, {"verb": "preferir", "pronoun": "nosotros"}, {"verb": "preferir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem e→ie entender + preferir (2/2): entender, preferir",
            "targets": [{"verb": "entender", "pronoun": "tú"}, {"verb": "entender", "pronoun": "yo"}, {"verb": "entender", "pronoun": "él"}, {"verb": "entender", "pronoun": "nosotros"}, {"verb": "entender", "pronoun": "ellas"}, {"verb": "preferir", "pronoun": "tú"}, {"verb": "preferir", "pronoun": "yo"}, {"verb": "preferir", "pronoun": "él"}, {"verb": "preferir", "pronoun": "nosotros"}, {"verb": "preferir", "pronoun": "ellas"}],
        },
        "opener_en": "What do you prefer?",
        "opener_es": "¿Qué prefieres?",
    },

    "grammar_present_e_ie_querer_pensar_chat": {
        "title": "Stem e→ie — querer + pensar Chat",
        "grammar_level": 7,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["querer", "pensar"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem e→ie querer + pensar chat: querer, pensar", "targets": [{"verb": "querer", "pronoun": "yo"}, {"verb": "querer", "pronoun": "tú"}, {"verb": "querer", "pronoun": "ella"}, {"verb": "querer", "pronoun": "nosotras"}, {"verb": "querer", "pronoun": "ustedes"}, {"verb": "pensar", "pronoun": "tú"}, {"verb": "pensar", "pronoun": "yo"}, {"verb": "pensar", "pronoun": "él"}, {"verb": "pensar", "pronoun": "nosotros"}, {"verb": "pensar", "pronoun": "ellas"}]},
    },

    "grammar_present_e_ie_cerrar_empezar_chat": {
        "title": "Stem e→ie — cerrar + empezar Chat",
        "grammar_level": 7,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["cerrar", "empezar"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem e→ie cerrar + empezar chat: cerrar, empezar", "targets": [{"verb": "cerrar", "pronoun": "yo"}, {"verb": "cerrar", "pronoun": "tú"}, {"verb": "cerrar", "pronoun": "ella"}, {"verb": "cerrar", "pronoun": "nosotras"}, {"verb": "cerrar", "pronoun": "ustedes"}, {"verb": "empezar", "pronoun": "tú"}, {"verb": "empezar", "pronoun": "yo"}, {"verb": "empezar", "pronoun": "él"}, {"verb": "empezar", "pronoun": "nosotros"}, {"verb": "empezar", "pronoun": "ellas"}]},
    },

    "grammar_present_e_ie_entender_preferir_chat": {
        "title": "Stem e→ie — entender + preferir Chat",
        "grammar_level": 7,
        "lesson_number": 6.5,
        "lesson_type": "conjugation",
        "word_workload": ["entender", "preferir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem e→ie entender + preferir chat: entender, preferir", "targets": [{"verb": "entender", "pronoun": "yo"}, {"verb": "entender", "pronoun": "tú"}, {"verb": "entender", "pronoun": "ella"}, {"verb": "entender", "pronoun": "nosotras"}, {"verb": "entender", "pronoun": "ustedes"}, {"verb": "preferir", "pronoun": "tú"}, {"verb": "preferir", "pronoun": "yo"}, {"verb": "preferir", "pronoun": "él"}, {"verb": "preferir", "pronoun": "nosotros"}, {"verb": "preferir", "pronoun": "ellas"}]},
    },
