"""Auto-generated by scripts/split_gl8.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_present_e_i_{1,2,3}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

PRESENT_E_I_PEDIR_SERVIR_INTRO = {
    "kind": "cards",
    "title": "Stem e→i — pedir + servir",
    "cards": [
        {
            "kind": "text",
            "title": "pedir + servir",
            "body": "**e → i** in stressed syllables (only -ir verbs do this): p**i**do, s**i**rvo. Nosotros / nosotras stay regular (pedimos, servimos).",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**pedir** is 'to ask for' — used for ordering food, requesting things. **servir** is 'to serve' (food, a purpose).",
        },
        {
            "kind": "mini_table",
            "title": "pedir (to ask for/request)",
            "rows": [
            ["yo", "p|ido"],
            ["tú", "p|ides"],
            ["él / ella / usted", "p|ide"],
            ["nosotros / nosotras", "ped|imos"],
            ["ellos / ellas / ustedes", "p|iden"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "servir (to serve)",
            "rows": [
            ["yo", "s|irvo"],
            ["tú", "s|irves"],
            ["él / ella / usted", "s|irve"],
            ["nosotros / nosotras", "serv|imos"],
            ["ellos / ellas / ustedes", "s|irven"],
            ],
        },
    ],
    "recall": [
        {"verb": "pedir", "answers": {"yo": "p|ido", "tú": "p|ides", "él": "p|ide", "nosotros": "ped|imos", "ellos": "p|iden"}},
        {"verb": "servir", "answers": {"yo": "s|irvo", "tú": "s|irves", "él": "s|irve", "nosotros": "serv|imos", "ellos": "s|irven"}},
    ],
}

PRESENT_E_I_REPETIR_SEGUIR_INTRO = {
    "kind": "cards",
    "title": "Stem e→i — repetir + seguir",
    "cards": [
        {
            "kind": "text",
            "title": "repetir + seguir",
            "body": "Same e → i pattern: rep**i**to, s**i**go. **seguir** drops the **u** before -o/-a (yo sigo, not 'siguo') — same spelling rule we saw with conseguir.",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**repetir** is 'to repeat' (a word, an action). **seguir** is 'to follow' or 'to keep doing': sigo trabajando = I keep working.",
        },
        {
            "kind": "mini_table",
            "title": "repetir (to repeat)",
            "rows": [
            ["yo", "rep|ito"],
            ["tú", "rep|ites"],
            ["él / ella / usted", "rep|ite"],
            ["nosotros / nosotras", "repet|imos"],
            ["ellos / ellas / ustedes", "rep|iten"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "seguir (to follow)",
            "rows": [
            ["yo", "s|igo"],
            ["tú", "s|igues"],
            ["él / ella / usted", "s|igue"],
            ["nosotros / nosotras", "segu|imos"],
            ["ellos / ellas / ustedes", "s|iguen"],
            ],
        },
    ],
    "recall": [
        {"verb": "repetir", "answers": {"yo": "rep|ito", "tú": "rep|ites", "él": "rep|ite", "nosotros": "repet|imos", "ellos": "rep|iten"}},
        {"verb": "seguir", "answers": {"yo": "s|igo", "tú": "s|igues", "él": "s|igue", "nosotros": "segu|imos", "ellos": "s|iguen"}},
    ],
}

PRESENT_E_I_VESTIR_ELEGIR_INTRO = {
    "kind": "cards",
    "title": "Stem e→i — vestir + elegir",
    "cards": [
        {
            "kind": "text",
            "title": "vestir + elegir",
            "body": "Same e → i pattern: v**i**sto, el**i**jo. **elegir** changes **g → j** before -o (spelling-only): yo el**ijo**.",
        },
        {
            "kind": "text",
            "title": "Why these two together",
            "body": "**vestir** is 'to dress' (often reflexive: vestirse = to get dressed). **elegir** is 'to choose'.",
        },
        {
            "kind": "mini_table",
            "title": "vestir (to dress)",
            "rows": [
            ["yo", "v|isto"],
            ["tú", "v|istes"],
            ["él / ella / usted", "v|iste"],
            ["nosotros / nosotras", "vest|imos"],
            ["ellos / ellas / ustedes", "v|isten"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "elegir (to choose)",
            "rows": [
            ["yo", "el|ijo"],
            ["tú", "el|iges"],
            ["él / ella / usted", "el|ige"],
            ["nosotros / nosotras", "eleg|imos"],
            ["ellos / ellas / ustedes", "el|igen"],
            ],
        },
    ],
    "recall": [
        {"verb": "vestir", "answers": {"yo": "v|isto", "tú": "v|istes", "él": "v|iste", "nosotros": "vest|imos", "ellos": "v|isten"}},
        {"verb": "elegir", "answers": {"yo": "el|ijo", "tú": "el|iges", "él": "el|ige", "nosotros": "eleg|imos", "ellos": "el|igen"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_present_e_i_pedir_servir_1": {
        "title": "Stem e→i — pedir + servir (1/2)",
        "grammar_level": 8,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["pedir", "servir"],
        "video_embed_id": "L8M2P3RDsfx",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_E_I_PEDIR_SERVIR_INTRO,
        "rule_chart": PRESENT_E_I_RULE,
        "drill_config": {
            "answers": {
                "pedir": {"yo": "p|ido", "tú": "p|ides", "él": "p|ide", "ella": "p|ide", "usted": "p|ide", "nosotros": "ped|imos", "nosotras": "ped|imos", "ellos": "p|iden", "ellas": "p|iden", "ustedes": "p|iden"},
                "servir": {"yo": "s|irvo", "tú": "s|irves", "él": "s|irve", "ella": "s|irve", "usted": "s|irve", "nosotros": "serv|imos", "nosotras": "serv|imos", "ellos": "s|irven", "ellas": "s|irven", "ustedes": "s|irven"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I ask for water.", "es": "Yo pido agua.", "noun_id": None, "type": "written", "glosses": {"water": "agua", "agua": "water"}},
            {"en": "You ask for bread.", "es": "Tú pides pan.", "noun_id": None, "type": "auditory", "glosses": {"bread": "pan", "pan": "bread"}},
            {"en": "She asks for the menu.", "es": "Ella pide el menú.", "noun_id": None, "type": "written", "glosses": {"menu": "menú", "menú": "menu"}},
            {"en": "We (f) ask for the bill.", "es": "Nosotras pedimos la cuenta.", "noun_id": None, "type": "auditory", "glosses": {"bill": "cuenta", "cuenta": "bill"}},
            {"en": "You all ask for coffee.", "es": "Ustedes piden café.", "noun_id": None, "type": "written", "glosses": {"coffee": "café", "café": "coffee"}},
            {"en": "I serve the salad.", "es": "Yo sirvo la ensalada.", "noun_id": None, "type": "written", "glosses": {"salad": "ensalada", "ensalada": "salad"}},
            {"en": "You serve the soup.", "es": "Tú sirves la sopa.", "noun_id": None, "type": "auditory", "glosses": {"soup": "sopa", "sopa": "soup"}},
            {"en": "She serves the dessert.", "es": "Ella sirve el postre.", "noun_id": None, "type": "written", "glosses": {"dessert": "postre", "postre": "dessert"}},
            {"en": "We (f) serve the drinks.", "es": "Nosotras servimos las bebidas.", "noun_id": None, "type": "auditory", "glosses": {"drinks": "bebidas", "bebidas": "drinks"}},
            {"en": "You all serve the food.", "es": "Ustedes sirven la comida.", "noun_id": None, "type": "written", "glosses": {"food": "comida", "comida": "food"}},
        ],
        "drill_targets": [{"verb": "pedir", "pronoun": "yo"}, {"verb": "pedir", "pronoun": "tú"}, {"verb": "pedir", "pronoun": "ella"}, {"verb": "pedir", "pronoun": "nosotras"}, {"verb": "pedir", "pronoun": "ustedes"}, {"verb": "servir", "pronoun": "yo"}, {"verb": "servir", "pronoun": "tú"}, {"verb": "servir", "pronoun": "ella"}, {"verb": "servir", "pronoun": "nosotras"}, {"verb": "servir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem e→i pedir + servir (1/2): pedir, servir",
            "targets": [{"verb": "pedir", "pronoun": "yo"}, {"verb": "pedir", "pronoun": "tú"}, {"verb": "pedir", "pronoun": "ella"}, {"verb": "pedir", "pronoun": "nosotras"}, {"verb": "pedir", "pronoun": "ustedes"}, {"verb": "servir", "pronoun": "yo"}, {"verb": "servir", "pronoun": "tú"}, {"verb": "servir", "pronoun": "ella"}, {"verb": "servir", "pronoun": "nosotras"}, {"verb": "servir", "pronoun": "ustedes"}],
        },
        "opener_en": "What do you order?",
        "opener_es": "¿Qué pides?",
    },

    "grammar_present_e_i_pedir_servir_2": {
        "title": "Stem e→i — pedir + servir (2/2)",
        "grammar_level": 8,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["pedir", "servir"],
        "video_embed_id": "L8M2P3RDsfx",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_E_I_RULE,
        "drill_config": {
            "answers": {
                "pedir": {"yo": "p|ido", "tú": "p|ides", "él": "p|ide", "ella": "p|ide", "usted": "p|ide", "nosotros": "ped|imos", "nosotras": "ped|imos", "ellos": "p|iden", "ellas": "p|iden", "ustedes": "p|iden"},
                "servir": {"yo": "s|irvo", "tú": "s|irves", "él": "s|irve", "ella": "s|irve", "usted": "s|irve", "nosotros": "serv|imos", "nosotras": "serv|imos", "ellos": "s|irven", "ellas": "s|irven", "ustedes": "s|irven"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "Do you ask for the menu?", "es": "¿Pides el menú?", "noun_id": None, "type": "written", "glosses": {"menu": "menú", "menú": "menu"}},
            {"en": "I ask for water every day.", "es": "Pido agua todos los días.", "noun_id": None, "type": "auditory", "glosses": {"water": "agua", "agua": "water", "every day": "todos los días", "todos los días": "every day"}},
            {"en": "He asks for the bill.", "es": "Él pide la cuenta.", "noun_id": None, "type": "written", "glosses": {"bill": "cuenta", "cuenta": "bill"}},
            {"en": "We (m) ask for more bread.", "es": "Pedimos más pan.", "noun_id": None, "type": "auditory", "glosses": {"bread": "pan", "pan": "bread", "more": "más", "más": "more"}},
            {"en": "They (f) ask for the salad.", "es": "Ellas piden la ensalada.", "noun_id": None, "type": "written", "glosses": {"salad": "ensalada", "ensalada": "salad"}},
            {"en": "Do you serve the soup hot?", "es": "¿Sirves la sopa caliente?", "noun_id": None, "type": "written", "glosses": {"soup": "sopa", "sopa": "soup", "hot": "caliente", "caliente": "hot"}},
            {"en": "I serve the coffee in the morning.", "es": "Sirvo el café por la mañana.", "noun_id": None, "type": "auditory", "glosses": {"coffee": "café", "café": "coffee", "morning": "mañana", "mañana": "morning"}},
            {"en": "He serves the dishes quickly.", "es": "Él sirve los platos rápido.", "noun_id": None, "type": "written", "glosses": {"dishes": "platos", "platos": "dishes", "quickly": "rápido", "rápido": "quickly"}},
            {"en": "We (m) serve the guests now.", "es": "Servimos a los invitados ahora.", "noun_id": None, "type": "auditory", "glosses": {"guests": "invitados", "invitados": "guests", "now": "ahora", "ahora": "now"}},
            {"en": "They (f) serve the desserts.", "es": "Ellas sirven los postres.", "noun_id": None, "type": "written", "glosses": {"desserts": "postres", "postres": "desserts"}},
        ],
        "drill_targets": [{"verb": "pedir", "pronoun": "tú"}, {"verb": "pedir", "pronoun": "yo"}, {"verb": "pedir", "pronoun": "él"}, {"verb": "pedir", "pronoun": "nosotros"}, {"verb": "pedir", "pronoun": "ellas"}, {"verb": "servir", "pronoun": "tú"}, {"verb": "servir", "pronoun": "yo"}, {"verb": "servir", "pronoun": "él"}, {"verb": "servir", "pronoun": "nosotros"}, {"verb": "servir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem e→i pedir + servir (2/2): pedir, servir",
            "targets": [{"verb": "pedir", "pronoun": "tú"}, {"verb": "pedir", "pronoun": "yo"}, {"verb": "pedir", "pronoun": "él"}, {"verb": "pedir", "pronoun": "nosotros"}, {"verb": "pedir", "pronoun": "ellas"}, {"verb": "servir", "pronoun": "tú"}, {"verb": "servir", "pronoun": "yo"}, {"verb": "servir", "pronoun": "él"}, {"verb": "servir", "pronoun": "nosotros"}, {"verb": "servir", "pronoun": "ellas"}],
        },
        "opener_en": "Do they serve breakfast?",
        "opener_es": "¿Sirven desayuno?",
    },

    "grammar_present_e_i_repetir_seguir_1": {
        "title": "Stem e→i — repetir + seguir (1/2)",
        "grammar_level": 8,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["repetir", "seguir"],
        "video_embed_id": "L8M2P3RDsfx",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_E_I_REPETIR_SEGUIR_INTRO,
        "rule_chart": PRESENT_E_I_RULE,
        "drill_config": {
            "answers": {
                "repetir": {"yo": "rep|ito", "tú": "rep|ites", "él": "rep|ite", "ella": "rep|ite", "usted": "rep|ite", "nosotros": "repet|imos", "nosotras": "repet|imos", "ellos": "rep|iten", "ellas": "rep|iten", "ustedes": "rep|iten"},
                "seguir": {"yo": "s|igo", "tú": "s|igues", "él": "s|igue", "ella": "s|igue", "usted": "s|igue", "nosotros": "segu|imos", "nosotras": "segu|imos", "ellos": "s|iguen", "ellas": "s|iguen", "ustedes": "s|iguen"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I repeat the question", "es": "Yo repito la pregunta", "noun_id": None, "type": "written", "glosses": {"question": "pregunta", "pregunta": "question"}},
            {"en": "You repeat my words", "es": "Tú repites mis palabras", "noun_id": None, "type": "auditory", "glosses": {"words": "palabras", "palabras": "words"}},
            {"en": "She repeats the lesson", "es": "Ella repite la lección", "noun_id": None, "type": "written", "glosses": {"lesson": "lección", "lección": "lesson"}},
            {"en": "We (f) repeat the instructions", "es": "Nosotras repetimos las instrucciones", "noun_id": None, "type": "auditory", "glosses": {"instructions": "instrucciones", "instrucciones": "instructions"}},
            {"en": "You all repeat the song", "es": "Ustedes repiten la canción", "noun_id": None, "type": "written", "glosses": {"song": "canción", "canción": "song"}},
            {"en": "I follow the path", "es": "Yo sigo el camino", "noun_id": None, "type": "written", "glosses": {"path": "camino", "camino": "path"}},
            {"en": "You follow the map", "es": "Tú sigues el mapa", "noun_id": None, "type": "auditory", "glosses": {"map": "mapa", "mapa": "map"}},
            {"en": "She follows the rules", "es": "Ella sigue las reglas", "noun_id": None, "type": "written", "glosses": {"rules": "reglas", "reglas": "rules"}},
            {"en": "We (f) follow the signs", "es": "Nosotras seguimos las señales", "noun_id": None, "type": "auditory", "glosses": {"signs": "señales", "señales": "signs"}},
            {"en": "You all follow the leader", "es": "Ustedes siguen al líder", "noun_id": None, "type": "written", "glosses": {"leader": "líder", "líder": "leader"}},
        ],
        "drill_targets": [{"verb": "repetir", "pronoun": "yo"}, {"verb": "repetir", "pronoun": "tú"}, {"verb": "repetir", "pronoun": "ella"}, {"verb": "repetir", "pronoun": "nosotras"}, {"verb": "repetir", "pronoun": "ustedes"}, {"verb": "seguir", "pronoun": "yo"}, {"verb": "seguir", "pronoun": "tú"}, {"verb": "seguir", "pronoun": "ella"}, {"verb": "seguir", "pronoun": "nosotras"}, {"verb": "seguir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem e→i repetir + seguir (1/2): repetir, seguir",
            "targets": [{"verb": "repetir", "pronoun": "yo"}, {"verb": "repetir", "pronoun": "tú"}, {"verb": "repetir", "pronoun": "ella"}, {"verb": "repetir", "pronoun": "nosotras"}, {"verb": "repetir", "pronoun": "ustedes"}, {"verb": "seguir", "pronoun": "yo"}, {"verb": "seguir", "pronoun": "tú"}, {"verb": "seguir", "pronoun": "ella"}, {"verb": "seguir", "pronoun": "nosotras"}, {"verb": "seguir", "pronoun": "ustedes"}],
        },
        "opener_en": "Can you repeat that?",
        "opener_es": "¿Puedes repetir?",
    },

    "grammar_present_e_i_repetir_seguir_2": {
        "title": "Stem e→i — repetir + seguir (2/2)",
        "grammar_level": 8,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["repetir", "seguir"],
        "video_embed_id": "L8M2P3RDsfx",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_E_I_RULE,
        "drill_config": {
            "answers": {
                "repetir": {"yo": "rep|ito", "tú": "rep|ites", "él": "rep|ite", "ella": "rep|ite", "usted": "rep|ite", "nosotros": "repet|imos", "nosotras": "repet|imos", "ellos": "rep|iten", "ellas": "rep|iten", "ustedes": "rep|iten"},
                "seguir": {"yo": "s|igo", "tú": "s|igues", "él": "s|igue", "ella": "s|igue", "usted": "s|igue", "nosotros": "segu|imos", "nosotras": "segu|imos", "ellos": "s|iguen", "ellas": "s|iguen", "ustedes": "s|iguen"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You repeat the question.", "es": "Tú repites la pregunta.", "noun_id": None, "type": "written", "glosses": {"question": "pregunta", "pregunta": "question"}},
            {"en": "I repeat the words.", "es": "Yo repito las palabras.", "noun_id": None, "type": "auditory", "glosses": {"words": "palabras", "palabras": "words"}},
            {"en": "He repeats the sentence.", "es": "Él repite la frase.", "noun_id": None, "type": "written", "glosses": {"sentence": "frase", "frase": "sentence"}},
            {"en": "We repeat the instructions.", "es": "Nosotros repetimos las instrucciones.", "noun_id": None, "type": "auditory", "glosses": {"instructions": "instrucciones", "instrucciones": "instructions"}},
            {"en": "They (f) repeat the story.", "es": "Ellas repiten la historia.", "noun_id": None, "type": "written", "glosses": {"story": "historia", "historia": "story"}},
            {"en": "You follow the path.", "es": "Tú sigues el camino.", "noun_id": None, "type": "written", "glosses": {"path": "camino", "camino": "path"}},
            {"en": "I follow the rules.", "es": "Yo sigo las reglas.", "noun_id": None, "type": "auditory", "glosses": {"rules": "reglas", "reglas": "rules"}},
            {"en": "He follows the car.", "es": "Él sigue el coche.", "noun_id": None, "type": "written", "glosses": {"car": "coche", "coche": "car"}},
            {"en": "We follow the map.", "es": "Nosotros seguimos el mapa.", "noun_id": None, "type": "auditory", "glosses": {"map": "mapa", "mapa": "map"}},
            {"en": "They (f) follow the leader.", "es": "Ellas siguen a la líder.", "noun_id": None, "type": "written", "glosses": {"leader": "líder", "líder": "leader"}},
        ],
        "drill_targets": [{"verb": "repetir", "pronoun": "tú"}, {"verb": "repetir", "pronoun": "yo"}, {"verb": "repetir", "pronoun": "él"}, {"verb": "repetir", "pronoun": "nosotros"}, {"verb": "repetir", "pronoun": "ellas"}, {"verb": "seguir", "pronoun": "tú"}, {"verb": "seguir", "pronoun": "yo"}, {"verb": "seguir", "pronoun": "él"}, {"verb": "seguir", "pronoun": "nosotros"}, {"verb": "seguir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem e→i repetir + seguir (2/2): repetir, seguir",
            "targets": [{"verb": "repetir", "pronoun": "tú"}, {"verb": "repetir", "pronoun": "yo"}, {"verb": "repetir", "pronoun": "él"}, {"verb": "repetir", "pronoun": "nosotros"}, {"verb": "repetir", "pronoun": "ellas"}, {"verb": "seguir", "pronoun": "tú"}, {"verb": "seguir", "pronoun": "yo"}, {"verb": "seguir", "pronoun": "él"}, {"verb": "seguir", "pronoun": "nosotros"}, {"verb": "seguir", "pronoun": "ellas"}],
        },
        "opener_en": "Do you follow me?",
        "opener_es": "¿Me sigues?",
    },

    "grammar_present_e_i_vestir_elegir_1": {
        "title": "Stem e→i — vestir + elegir (1/2)",
        "grammar_level": 8,
        "lesson_number": 5,
        "lesson_type": "conjugation",
        "word_workload": ["vestir", "elegir"],
        "video_embed_id": "L8M2P3RDsfx",
        "drill_type": "conjugation",
        "tense": "present",
        "intro_chart": PRESENT_E_I_VESTIR_ELEGIR_INTRO,
        "rule_chart": PRESENT_E_I_RULE,
        "drill_config": {
            "answers": {
                "vestir": {"yo": "v|isto", "tú": "v|istes", "él": "v|iste", "ella": "v|iste", "usted": "v|iste", "nosotros": "vest|imos", "nosotras": "vest|imos", "ellos": "v|isten", "ellas": "v|isten", "ustedes": "v|isten"},
                "elegir": {"yo": "el|ijo", "tú": "el|iges", "él": "el|ige", "ella": "el|ige", "usted": "el|ige", "nosotros": "eleg|imos", "nosotras": "eleg|imos", "ellos": "el|igen", "ellas": "el|igen", "ustedes": "el|igen"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I dress in blue clothes.", "es": "Yo visto ropa azul.", "noun_id": None, "type": "written", "glosses": {"blue": "azul", "clothes": "ropa", "ropa": "clothes", "azul": "blue"}},
            {"en": "You dress quickly every day.", "es": "Tú vistes rápido todos los días.", "noun_id": None, "type": "auditory", "glosses": {"quickly": "rápido", "rápido": "quickly", "day": "día", "days": "días", "día": "day", "días": "days"}},
            {"en": "She dresses very elegantly.", "es": "Ella viste muy elegante.", "noun_id": None, "type": "written", "glosses": {"elegantly": "elegante", "elegante": "elegantly"}},
            {"en": "We (f) dress for the party.", "es": "Nosotras vestimos para la fiesta.", "noun_id": None, "type": "auditory", "glosses": {"party": "fiesta", "fiesta": "party"}},
            {"en": "You all dress in black jackets.", "es": "Ustedes visten chaquetas negras.", "noun_id": None, "type": "written", "glosses": {"black": "negras", "jackets": "chaquetas", "chaquetas": "jackets", "negras": "black"}},
            {"en": "I choose the red apple.", "es": "Yo elijo la manzana roja.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "red": "roja", "manzana": "apple", "roja": "red"}},
            {"en": "You choose good books.", "es": "Tú eliges buenos libros.", "noun_id": None, "type": "auditory", "glosses": {"books": "libros", "good": "buenos", "libros": "books", "buenos": "good"}},
            {"en": "She chooses a small gift.", "es": "Ella elige un regalo pequeño.", "noun_id": None, "type": "written", "glosses": {"gift": "regalo", "small": "pequeño", "regalo": "gift", "pequeño": "small"}},
            {"en": "We (f) choose fresh fruits.", "es": "Nosotras elegimos frutas frescas.", "noun_id": None, "type": "auditory", "glosses": {"fruits": "frutas", "fresh": "frescas", "frutas": "fruits", "frescas": "fresh"}},
            {"en": "You all choose the best options.", "es": "Ustedes eligen las mejores opciones.", "noun_id": None, "type": "written", "glosses": {"best": "mejores", "options": "opciones", "mejores": "best", "opciones": "options"}},
        ],
        "drill_targets": [{"verb": "vestir", "pronoun": "yo"}, {"verb": "vestir", "pronoun": "tú"}, {"verb": "vestir", "pronoun": "ella"}, {"verb": "vestir", "pronoun": "nosotras"}, {"verb": "vestir", "pronoun": "ustedes"}, {"verb": "elegir", "pronoun": "yo"}, {"verb": "elegir", "pronoun": "tú"}, {"verb": "elegir", "pronoun": "ella"}, {"verb": "elegir", "pronoun": "nosotras"}, {"verb": "elegir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "Stem e→i vestir + elegir (1/2): vestir, elegir",
            "targets": [{"verb": "vestir", "pronoun": "yo"}, {"verb": "vestir", "pronoun": "tú"}, {"verb": "vestir", "pronoun": "ella"}, {"verb": "vestir", "pronoun": "nosotras"}, {"verb": "vestir", "pronoun": "ustedes"}, {"verb": "elegir", "pronoun": "yo"}, {"verb": "elegir", "pronoun": "tú"}, {"verb": "elegir", "pronoun": "ella"}, {"verb": "elegir", "pronoun": "nosotras"}, {"verb": "elegir", "pronoun": "ustedes"}],
        },
        "opener_en": "How do you dress for work?",
        "opener_es": "¿Cómo te vistes para el trabajo?",
    },

    "grammar_present_e_i_vestir_elegir_2": {
        "title": "Stem e→i — vestir + elegir (2/2)",
        "grammar_level": 8,
        "lesson_number": 6,
        "lesson_type": "conjugation",
        "word_workload": ["vestir", "elegir"],
        "video_embed_id": "L8M2P3RDsfx",
        "drill_type": "conjugation",
        "tense": "present",
        "rule_chart": PRESENT_E_I_RULE,
        "drill_config": {
            "answers": {
                "vestir": {"yo": "v|isto", "tú": "v|istes", "él": "v|iste", "ella": "v|iste", "usted": "v|iste", "nosotros": "vest|imos", "nosotras": "vest|imos", "ellos": "v|isten", "ellas": "v|isten", "ustedes": "v|isten"},
                "elegir": {"yo": "el|ijo", "tú": "el|iges", "él": "el|ige", "ella": "el|ige", "usted": "el|ige", "nosotros": "eleg|imos", "nosotras": "eleg|imos", "ellos": "el|igen", "ellas": "el|igen", "ustedes": "el|igen"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You dress quickly.", "es": "Tú vistes rápido.", "noun_id": None, "type": "written", "glosses": {"quickly": "rápido", "rápido": "quickly"}},
            {"en": "I dress in the morning.", "es": "Yo visto en la mañana.", "noun_id": None, "type": "auditory", "glosses": {"morning": "mañana", "mañana": "morning"}},
            {"en": "He dresses very well.", "es": "Él viste muy bien.", "noun_id": None, "type": "written", "glosses": {}},
            {"en": "We (m) dress for the party.", "es": "Nosotros vestimos para la fiesta.", "noun_id": None, "type": "auditory", "glosses": {"party": "fiesta", "fiesta": "party"}},
            {"en": "They (f) dress in red dresses.", "es": "Ellas visten vestidos rojos.", "noun_id": None, "type": "written", "glosses": {"dresses": "vestidos", "red": "rojos", "vestidos": "dresses", "rojos": "red"}},
            {"en": "You choose the blue shirt.", "es": "Tú eliges la camisa azul.", "noun_id": None, "type": "written", "glosses": {"shirt": "camisa", "blue": "azul", "camisa": "shirt", "azul": "blue"}},
            {"en": "I choose a small gift.", "es": "Yo elijo un regalo pequeño.", "noun_id": None, "type": "auditory", "glosses": {"gift": "regalo", "small": "pequeño", "regalo": "gift", "pequeño": "small"}},
            {"en": "He chooses the best option.", "es": "Él elige la mejor opción.", "noun_id": None, "type": "written", "glosses": {"option": "opción", "best": "mejor", "opción": "option", "mejor": "best"}},
            {"en": "We (m) choose new books.", "es": "Nosotros elegimos libros nuevos.", "noun_id": None, "type": "auditory", "glosses": {"books": "libros", "new": "nuevos", "libros": "books", "nuevos": "new"}},
            {"en": "They (f) choose old houses.", "es": "Ellas eligen casas viejas.", "noun_id": None, "type": "written", "glosses": {"houses": "casas", "old": "viejas", "casas": "houses", "viejas": "old"}},
        ],
        "drill_targets": [{"verb": "vestir", "pronoun": "tú"}, {"verb": "vestir", "pronoun": "yo"}, {"verb": "vestir", "pronoun": "él"}, {"verb": "vestir", "pronoun": "nosotros"}, {"verb": "vestir", "pronoun": "ellas"}, {"verb": "elegir", "pronoun": "tú"}, {"verb": "elegir", "pronoun": "yo"}, {"verb": "elegir", "pronoun": "él"}, {"verb": "elegir", "pronoun": "nosotros"}, {"verb": "elegir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "Stem e→i vestir + elegir (2/2): vestir, elegir",
            "targets": [{"verb": "vestir", "pronoun": "tú"}, {"verb": "vestir", "pronoun": "yo"}, {"verb": "vestir", "pronoun": "él"}, {"verb": "vestir", "pronoun": "nosotros"}, {"verb": "vestir", "pronoun": "ellas"}, {"verb": "elegir", "pronoun": "tú"}, {"verb": "elegir", "pronoun": "yo"}, {"verb": "elegir", "pronoun": "él"}, {"verb": "elegir", "pronoun": "nosotros"}, {"verb": "elegir", "pronoun": "ellas"}],
        },
        "opener_en": "Which one do you choose?",
        "opener_es": "¿Cuál eliges?",
    },

    "grammar_present_e_i_pedir_servir_chat": {
        "title": "Stem e→i — pedir + servir Chat",
        "grammar_level": 8,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["pedir", "servir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem e→i pedir + servir chat: pedir, servir", "targets": [{"verb": "pedir", "pronoun": "yo"}, {"verb": "pedir", "pronoun": "tú"}, {"verb": "pedir", "pronoun": "ella"}, {"verb": "pedir", "pronoun": "nosotras"}, {"verb": "pedir", "pronoun": "ustedes"}, {"verb": "servir", "pronoun": "tú"}, {"verb": "servir", "pronoun": "yo"}, {"verb": "servir", "pronoun": "él"}, {"verb": "servir", "pronoun": "nosotros"}, {"verb": "servir", "pronoun": "ellas"}]},
    },

    "grammar_present_e_i_repetir_seguir_chat": {
        "title": "Stem e→i — repetir + seguir Chat",
        "grammar_level": 8,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["repetir", "seguir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem e→i repetir + seguir chat: repetir, seguir", "targets": [{"verb": "repetir", "pronoun": "yo"}, {"verb": "repetir", "pronoun": "tú"}, {"verb": "repetir", "pronoun": "ella"}, {"verb": "repetir", "pronoun": "nosotras"}, {"verb": "repetir", "pronoun": "ustedes"}, {"verb": "seguir", "pronoun": "tú"}, {"verb": "seguir", "pronoun": "yo"}, {"verb": "seguir", "pronoun": "él"}, {"verb": "seguir", "pronoun": "nosotros"}, {"verb": "seguir", "pronoun": "ellas"}]},
    },

    "grammar_present_e_i_vestir_elegir_chat": {
        "title": "Stem e→i — vestir + elegir Chat",
        "grammar_level": 8,
        "lesson_number": 6.5,
        "lesson_type": "conjugation",
        "word_workload": ["vestir", "elegir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "present",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "Stem e→i vestir + elegir chat: vestir, elegir", "targets": [{"verb": "vestir", "pronoun": "yo"}, {"verb": "vestir", "pronoun": "tú"}, {"verb": "vestir", "pronoun": "ella"}, {"verb": "vestir", "pronoun": "nosotras"}, {"verb": "vestir", "pronoun": "ustedes"}, {"verb": "elegir", "pronoun": "tú"}, {"verb": "elegir", "pronoun": "yo"}, {"verb": "elegir", "pronoun": "él"}, {"verb": "elegir", "pronoun": "nosotros"}, {"verb": "elegir", "pronoun": "ellas"}]},
    },
