"""Auto-generated by scripts/split_gl9.py — splice into grammar_situations.py.
"""


# ── Retire keys: grammar_ir_a_inf_{1,2,3}{,_chat}

# ── New intro constants ──────────────────────────────────────────────────

IR_A_INF_HABLAR_COMER_INTRO = {
    "kind": "cards",
    "title": "ir a + Infinitive — hablar + comer",
    "cards": [
        {
            "kind": "text",
            "title": "hablar + comer",
            "body": "**ir + a + infinitive** is the everyday Spanish 'going-to' future. Conjugate **ir** (voy, vas, va, vamos, van), add **a**, then any infinitive. *Voy a hablar* = I'm going to speak.",
        },
        {
            "kind": "text",
            "title": "What changes, what stays",
            "body": "This sub-block uses **hablar** (to speak) and **comer** (to eat) as the infinitives. The conjugated part — ir — is what you're learning to flex.",
        },
        {
            "kind": "mini_table",
            "title": "ir a + hablar (to speak)",
            "rows": [
            ["yo", "|voy a hablar"],
            ["tú", "|vas a hablar"],
            ["él / ella / usted", "|va a hablar"],
            ["nosotros / nosotras", "|vamos a hablar"],
            ["ellos / ellas / ustedes", "|van a hablar"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "ir a + comer (to eat)",
            "rows": [
            ["yo", "|voy a comer"],
            ["tú", "|vas a comer"],
            ["él / ella / usted", "|va a comer"],
            ["nosotros / nosotras", "|vamos a comer"],
            ["ellos / ellas / ustedes", "|van a comer"],
            ],
        },
    ],
    "recall": [
        {"verb": "hablar", "answers": {"yo": "|voy a hablar", "tú": "|vas a hablar", "él": "|va a hablar", "nosotros": "|vamos a hablar", "ellos": "|van a hablar"}},
        {"verb": "comer", "answers": {"yo": "|voy a comer", "tú": "|vas a comer", "él": "|va a comer", "nosotros": "|vamos a comer", "ellos": "|van a comer"}},
    ],
}

IR_A_INF_VIVIR_ESCRIBIR_INTRO = {
    "kind": "cards",
    "title": "ir a + Infinitive — vivir + escribir",
    "cards": [
        {
            "kind": "text",
            "title": "vivir + escribir",
            "body": "Same construction: **ir + a + infinitive**. Today we use **vivir** (to live) and **escribir** (to write) as the infinitives.",
        },
        {
            "kind": "text",
            "title": "What changes, what stays",
            "body": "Notice that the infinitive never changes — only **ir** flexes for the subject. The whole structure functions as a near-future tense.",
        },
        {
            "kind": "mini_table",
            "title": "ir a + vivir (to live)",
            "rows": [
            ["yo", "|voy a vivir"],
            ["tú", "|vas a vivir"],
            ["él / ella / usted", "|va a vivir"],
            ["nosotros / nosotras", "|vamos a vivir"],
            ["ellos / ellas / ustedes", "|van a vivir"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "ir a + escribir (to write)",
            "rows": [
            ["yo", "|voy a escribir"],
            ["tú", "|vas a escribir"],
            ["él / ella / usted", "|va a escribir"],
            ["nosotros / nosotras", "|vamos a escribir"],
            ["ellos / ellas / ustedes", "|van a escribir"],
            ],
        },
    ],
    "recall": [
        {"verb": "vivir", "answers": {"yo": "|voy a vivir", "tú": "|vas a vivir", "él": "|va a vivir", "nosotros": "|vamos a vivir", "ellos": "|van a vivir"}},
        {"verb": "escribir", "answers": {"yo": "|voy a escribir", "tú": "|vas a escribir", "él": "|va a escribir", "nosotros": "|vamos a escribir", "ellos": "|van a escribir"}},
    ],
}

IR_A_INF_DORMIR_ESTUDIAR_INTRO = {
    "kind": "cards",
    "title": "ir a + Infinitive — dormir + estudiar",
    "cards": [
        {
            "kind": "text",
            "title": "dormir + estudiar",
            "body": "Same construction with **dormir** (to sleep) and **estudiar** (to study). Even stem-changers like dormir keep their plain infinitive shape here — only **ir** flexes.",
        },
        {
            "kind": "text",
            "title": "What changes, what stays",
            "body": "ir + a + inf is more common in spoken Spanish than the simple future tense (hablaré). Drill it until it's automatic.",
        },
        {
            "kind": "mini_table",
            "title": "ir a + dormir (to sleep)",
            "rows": [
            ["yo", "|voy a dormir"],
            ["tú", "|vas a dormir"],
            ["él / ella / usted", "|va a dormir"],
            ["nosotros / nosotras", "|vamos a dormir"],
            ["ellos / ellas / ustedes", "|van a dormir"],
            ],
        },
        {
            "kind": "mini_table",
            "title": "ir a + estudiar (to study)",
            "rows": [
            ["yo", "|voy a estudiar"],
            ["tú", "|vas a estudiar"],
            ["él / ella / usted", "|va a estudiar"],
            ["nosotros / nosotras", "|vamos a estudiar"],
            ["ellos / ellas / ustedes", "|van a estudiar"],
            ],
        },
    ],
    "recall": [
        {"verb": "dormir", "answers": {"yo": "|voy a dormir", "tú": "|vas a dormir", "él": "|va a dormir", "nosotros": "|vamos a dormir", "ellos": "|van a dormir"}},
        {"verb": "estudiar", "answers": {"yo": "|voy a estudiar", "tú": "|vas a estudiar", "él": "|va a estudiar", "nosotros": "|vamos a estudiar", "ellos": "|van a estudiar"}},
    ],
}

# ── New lesson dicts ────────────────────────────────────────────────────

    "grammar_ir_a_inf_hablar_comer_1": {
        "title": "ir a + Infinitive — hablar + comer (1/2)",
        "grammar_level": 9,
        "lesson_number": 1,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": "geHPDI9tMdH",
        "drill_type": "ir_a_inf",
        "tense": "ir_a_infinitive",
        "intro_chart": IR_A_INF_HABLAR_COMER_INTRO,
        "rule_chart": IR_A_INF_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "|voy a hablar", "tú": "|vas a hablar", "él": "|va a hablar", "ella": "|va a hablar", "usted": "|va a hablar", "nosotros": "|vamos a hablar", "nosotras": "|vamos a hablar", "ellos": "|van a hablar", "ellas": "|van a hablar", "ustedes": "|van a hablar"},
                "comer": {"yo": "|voy a comer", "tú": "|vas a comer", "él": "|va a comer", "ella": "|va a comer", "usted": "|va a comer", "nosotros": "|vamos a comer", "nosotras": "|vamos a comer", "ellos": "|van a comer", "ellas": "|van a comer", "ustedes": "|van a comer"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I'm going to speak Spanish.", "es": "Voy a hablar español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "Are you going to speak now?", "es": "¿Vas a hablar ahora?", "noun_id": None, "type": "auditory", "glosses": {"now": "ahora", "ahora": "now"}},
            {"en": "She is going to speak with the teacher.", "es": "Ella va a hablar con la profesora.", "noun_id": None, "type": "written", "glosses": {"teacher": "profesora", "profesora": "teacher"}},
            {"en": "We (f) are going to speak loudly.", "es": "Nosotras vamos a hablar fuerte.", "noun_id": None, "type": "auditory", "glosses": {"loudly": "fuerte", "fuerte": "loudly"}},
            {"en": "You (pl) are going to speak tomorrow.", "es": "Ustedes van a hablar mañana.", "noun_id": None, "type": "written", "glosses": {"tomorrow": "mañana", "mañana": "tomorrow"}},
            {"en": "I'm going to eat an apple.", "es": "Voy a comer una manzana.", "noun_id": None, "type": "written", "glosses": {"apple": "manzana", "manzana": "apple"}},
            {"en": "Are you going to eat breakfast?", "es": "¿Vas a comer el desayuno?", "noun_id": None, "type": "auditory", "glosses": {"breakfast": "desayuno", "desayuno": "breakfast"}},
            {"en": "She is going to eat rice.", "es": "Ella va a comer arroz.", "noun_id": None, "type": "written", "glosses": {"rice": "arroz", "arroz": "rice"}},
            {"en": "We (f) are going to eat early.", "es": "Nosotras vamos a comer temprano.", "noun_id": None, "type": "auditory", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "You (pl) are going to eat dinner.", "es": "Ustedes van a comer la cena.", "noun_id": None, "type": "written", "glosses": {"dinner": "cena", "cena": "dinner"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "ir a + Infinitive hablar + comer (1/2): hablar, comer",
            "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "ella"}, {"verb": "comer", "pronoun": "nosotras"}, {"verb": "comer", "pronoun": "ustedes"}],
        },
        "opener_en": "What are you going to say?",
        "opener_es": "¿Qué vas a decir?",
    },

    "grammar_ir_a_inf_hablar_comer_2": {
        "title": "ir a + Infinitive — hablar + comer (2/2)",
        "grammar_level": 9,
        "lesson_number": 2,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": "geHPDI9tMdH",
        "drill_type": "ir_a_inf",
        "tense": "ir_a_infinitive",
        "rule_chart": IR_A_INF_RULE,
        "drill_config": {
            "answers": {
                "hablar": {"yo": "|voy a hablar", "tú": "|vas a hablar", "él": "|va a hablar", "ella": "|va a hablar", "usted": "|va a hablar", "nosotros": "|vamos a hablar", "nosotras": "|vamos a hablar", "ellos": "|van a hablar", "ellas": "|van a hablar", "ustedes": "|van a hablar"},
                "comer": {"yo": "|voy a comer", "tú": "|vas a comer", "él": "|va a comer", "ella": "|va a comer", "usted": "|va a comer", "nosotros": "|vamos a comer", "nosotras": "|vamos a comer", "ellos": "|van a comer", "ellas": "|van a comer", "ustedes": "|van a comer"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You are going to speak with the teacher.", "es": "Tú vas a hablar con el profesor.", "noun_id": None, "type": "written", "glosses": {"teacher": "profesor", "profesor": "teacher"}},
            {"en": "I am going to speak Spanish today.", "es": "Yo voy a hablar español hoy.", "noun_id": None, "type": "auditory", "glosses": {"Spanish": "español", "hoy": "today", "español": "Spanish", "today": "hoy"}},
            {"en": "He is going to speak at the meeting.", "es": "Él va a hablar en la reunión.", "noun_id": None, "type": "written", "glosses": {"meeting": "reunión", "reunión": "meeting"}},
            {"en": "We (m) are going to speak about the project.", "es": "Nosotros vamos a hablar sobre el proyecto.", "noun_id": None, "type": "auditory", "glosses": {"project": "proyecto", "proyecto": "project"}},
            {"en": "They (f) are going to speak very clearly.", "es": "Ellas van a hablar muy claro.", "noun_id": None, "type": "written", "glosses": {"clear": "claro", "claro": "clear"}},
            {"en": "You are going to eat the apples.", "es": "Tú vas a comer las manzanas.", "noun_id": None, "type": "written", "glosses": {"apples": "manzanas", "manzanas": "apples"}},
            {"en": "I am going to eat lunch now.", "es": "Yo voy a comer el almuerzo ahora.", "noun_id": None, "type": "auditory", "glosses": {"lunch": "almuerzo", "now": "ahora", "almuerzo": "lunch", "ahora": "now"}},
            {"en": "He is going to eat a big sandwich.", "es": "Él va a comer un sándwich grande.", "noun_id": None, "type": "written", "glosses": {"sandwich": "sándwich", "big": "grande", "sándwich": "sandwich", "grande": "big"}},
            {"en": "We (m) are going to eat at the restaurant.", "es": "Nosotros vamos a comer en el restaurante.", "noun_id": None, "type": "auditory", "glosses": {"restaurant": "restaurante", "restaurante": "restaurant"}},
            {"en": "They (f) are going to eat fresh fruit.", "es": "Ellas van a comer fruta fresca.", "noun_id": None, "type": "written", "glosses": {"fruit": "fruta", "fresh": "fresca", "fruta": "fruit", "fresca": "fresh"}},
        ],
        "drill_targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "ir a + Infinitive hablar + comer (2/2): hablar, comer",
            "targets": [{"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "él"}, {"verb": "hablar", "pronoun": "nosotros"}, {"verb": "hablar", "pronoun": "ellas"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}],
        },
        "opener_en": "What are you going to eat?",
        "opener_es": "¿Qué vas a comer?",
    },

    "grammar_ir_a_inf_vivir_escribir_1": {
        "title": "ir a + Infinitive — vivir + escribir (1/2)",
        "grammar_level": 9,
        "lesson_number": 3,
        "lesson_type": "conjugation",
        "word_workload": ["vivir", "escribir"],
        "video_embed_id": "geHPDI9tMdH",
        "drill_type": "ir_a_inf",
        "tense": "ir_a_infinitive",
        "intro_chart": IR_A_INF_VIVIR_ESCRIBIR_INTRO,
        "rule_chart": IR_A_INF_RULE,
        "drill_config": {
            "answers": {
                "vivir": {"yo": "|voy a vivir", "tú": "|vas a vivir", "él": "|va a vivir", "ella": "|va a vivir", "usted": "|va a vivir", "nosotros": "|vamos a vivir", "nosotras": "|vamos a vivir", "ellos": "|van a vivir", "ellas": "|van a vivir", "ustedes": "|van a vivir"},
                "escribir": {"yo": "|voy a escribir", "tú": "|vas a escribir", "él": "|va a escribir", "ella": "|va a escribir", "usted": "|va a escribir", "nosotros": "|vamos a escribir", "nosotras": "|vamos a escribir", "ellos": "|van a escribir", "ellas": "|van a escribir", "ustedes": "|van a escribir"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I'm going to live in Madrid.", "es": "Voy a vivir en Madrid.", "noun_id": None, "type": "written", "glosses": {"Madrid": "Madrid"}},
            {"en": "You are going to live near the beach.", "es": "Vas a vivir cerca de la playa.", "noun_id": None, "type": "auditory", "glosses": {"beach": "playa", "playa": "beach"}},
            {"en": "She is going to live in a big house.", "es": "Ella va a vivir en una casa grande.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "big": "grande", "casa": "house", "grande": "big"}},
            {"en": "We (f) are going to live in the city.", "es": "Nosotras vamos a vivir en la ciudad.", "noun_id": None, "type": "auditory", "glosses": {"city": "ciudad", "ciudad": "city"}},
            {"en": "You all are going to live in new apartments.", "es": "Ustedes van a vivir en apartamentos nuevos.", "noun_id": None, "type": "written", "glosses": {"apartments": "apartamentos", "new": "nuevos", "apartamentos": "apartments", "nuevos": "new"}},
            {"en": "I'm going to write a letter.", "es": "Voy a escribir una carta.", "noun_id": None, "type": "written", "glosses": {"letter": "carta", "carta": "letter"}},
            {"en": "You are going to write a story.", "es": "Vas a escribir un cuento.", "noun_id": None, "type": "auditory", "glosses": {"story": "cuento", "cuento": "story"}},
            {"en": "She is going to write poems.", "es": "Ella va a escribir poemas.", "noun_id": None, "type": "written", "glosses": {"poems": "poemas", "poemas": "poems"}},
            {"en": "We (f) are going to write emails.", "es": "Nosotras vamos a escribir correos electrónicos.", "noun_id": None, "type": "auditory", "glosses": {"emails": "correos electrónicos", "correos electrónicos": "emails"}},
            {"en": "You all are going to write reports.", "es": "Ustedes van a escribir informes.", "noun_id": None, "type": "written", "glosses": {"reports": "informes", "informes": "reports"}},
        ],
        "drill_targets": [{"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "ella"}, {"verb": "vivir", "pronoun": "nosotras"}, {"verb": "vivir", "pronoun": "ustedes"}, {"verb": "escribir", "pronoun": "yo"}, {"verb": "escribir", "pronoun": "tú"}, {"verb": "escribir", "pronoun": "ella"}, {"verb": "escribir", "pronoun": "nosotras"}, {"verb": "escribir", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "ir a + Infinitive vivir + escribir (1/2): vivir, escribir",
            "targets": [{"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "ella"}, {"verb": "vivir", "pronoun": "nosotras"}, {"verb": "vivir", "pronoun": "ustedes"}, {"verb": "escribir", "pronoun": "yo"}, {"verb": "escribir", "pronoun": "tú"}, {"verb": "escribir", "pronoun": "ella"}, {"verb": "escribir", "pronoun": "nosotras"}, {"verb": "escribir", "pronoun": "ustedes"}],
        },
        "opener_en": "Where are you going to live?",
        "opener_es": "¿Dónde vas a vivir?",
    },

    "grammar_ir_a_inf_vivir_escribir_2": {
        "title": "ir a + Infinitive — vivir + escribir (2/2)",
        "grammar_level": 9,
        "lesson_number": 4,
        "lesson_type": "conjugation",
        "word_workload": ["vivir", "escribir"],
        "video_embed_id": "geHPDI9tMdH",
        "drill_type": "ir_a_inf",
        "tense": "ir_a_infinitive",
        "rule_chart": IR_A_INF_RULE,
        "drill_config": {
            "answers": {
                "vivir": {"yo": "|voy a vivir", "tú": "|vas a vivir", "él": "|va a vivir", "ella": "|va a vivir", "usted": "|va a vivir", "nosotros": "|vamos a vivir", "nosotras": "|vamos a vivir", "ellos": "|van a vivir", "ellas": "|van a vivir", "ustedes": "|van a vivir"},
                "escribir": {"yo": "|voy a escribir", "tú": "|vas a escribir", "él": "|va a escribir", "ella": "|va a escribir", "usted": "|va a escribir", "nosotros": "|vamos a escribir", "nosotras": "|vamos a escribir", "ellos": "|van a escribir", "ellas": "|van a escribir", "ustedes": "|van a escribir"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You are going to live in Madrid.", "es": "Tú vas a vivir en Madrid.", "noun_id": None, "type": "written", "glosses": {"Madrid": "Madrid"}},
            {"en": "I am going to live near the beach.", "es": "Yo voy a vivir cerca de la playa.", "noun_id": None, "type": "auditory", "glosses": {"beach": "playa", "playa": "beach"}},
            {"en": "He is going to live in a big house.", "es": "Él va a vivir en una casa grande.", "noun_id": None, "type": "written", "glosses": {"house": "casa", "big": "grande", "casa": "house", "grande": "big"}},
            {"en": "We (m) are going to live in the city.", "es": "Nosotros vamos a vivir en la ciudad.", "noun_id": None, "type": "auditory", "glosses": {"city": "ciudad", "ciudad": "city"}},
            {"en": "They (f) are going to live in a small town.", "es": "Ellas van a vivir en un pueblo pequeño.", "noun_id": None, "type": "written", "glosses": {"town": "pueblo", "small": "pequeño", "pueblo": "town", "pequeño": "small"}},
            {"en": "You are going to write a letter.", "es": "Tú vas a escribir una carta.", "noun_id": None, "type": "written", "glosses": {"letter": "carta", "carta": "letter"}},
            {"en": "I am going to write a story.", "es": "Yo voy a escribir una historia.", "noun_id": None, "type": "auditory", "glosses": {"story": "historia", "historia": "story"}},
            {"en": "He is going to write an email.", "es": "Él va a escribir un correo electrónico.", "noun_id": None, "type": "written", "glosses": {"email": "correo electrónico", "correo electrónico": "email"}},
            {"en": "We (m) are going to write poems.", "es": "Nosotros vamos a escribir poemas.", "noun_id": None, "type": "auditory", "glosses": {"poems": "poemas", "poemas": "poems"}},
            {"en": "They (f) are going to write songs.", "es": "Ellas van a escribir canciones.", "noun_id": None, "type": "written", "glosses": {"songs": "canciones", "canciones": "songs"}},
        ],
        "drill_targets": [{"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "él"}, {"verb": "vivir", "pronoun": "nosotros"}, {"verb": "vivir", "pronoun": "ellas"}, {"verb": "escribir", "pronoun": "tú"}, {"verb": "escribir", "pronoun": "yo"}, {"verb": "escribir", "pronoun": "él"}, {"verb": "escribir", "pronoun": "nosotros"}, {"verb": "escribir", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "ir a + Infinitive vivir + escribir (2/2): vivir, escribir",
            "targets": [{"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "él"}, {"verb": "vivir", "pronoun": "nosotros"}, {"verb": "vivir", "pronoun": "ellas"}, {"verb": "escribir", "pronoun": "tú"}, {"verb": "escribir", "pronoun": "yo"}, {"verb": "escribir", "pronoun": "él"}, {"verb": "escribir", "pronoun": "nosotros"}, {"verb": "escribir", "pronoun": "ellas"}],
        },
        "opener_en": "What are you going to write?",
        "opener_es": "¿Qué vas a escribir?",
    },

    "grammar_ir_a_inf_dormir_estudiar_1": {
        "title": "ir a + Infinitive — dormir + estudiar (1/2)",
        "grammar_level": 9,
        "lesson_number": 5,
        "lesson_type": "conjugation",
        "word_workload": ["dormir", "estudiar"],
        "video_embed_id": "geHPDI9tMdH",
        "drill_type": "ir_a_inf",
        "tense": "ir_a_infinitive",
        "intro_chart": IR_A_INF_DORMIR_ESTUDIAR_INTRO,
        "rule_chart": IR_A_INF_RULE,
        "drill_config": {
            "answers": {
                "dormir": {"yo": "|voy a dormir", "tú": "|vas a dormir", "él": "|va a dormir", "ella": "|va a dormir", "usted": "|va a dormir", "nosotros": "|vamos a dormir", "nosotras": "|vamos a dormir", "ellos": "|van a dormir", "ellas": "|van a dormir", "ustedes": "|van a dormir"},
                "estudiar": {"yo": "|voy a estudiar", "tú": "|vas a estudiar", "él": "|va a estudiar", "ella": "|va a estudiar", "usted": "|va a estudiar", "nosotros": "|vamos a estudiar", "nosotras": "|vamos a estudiar", "ellos": "|van a estudiar", "ellas": "|van a estudiar", "ustedes": "|van a estudiar"},
            },
        },
        "phases": {"0a": True, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "I'm going to sleep early.", "es": "Voy a dormir temprano.", "noun_id": None, "type": "written", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "You are going to sleep well.", "es": "Vas a dormir bien.", "noun_id": None, "type": "auditory", "glosses": {"well": "bien", "bien": "well"}},
            {"en": "She is going to sleep now.", "es": "Ella va a dormir ahora.", "noun_id": None, "type": "written", "glosses": {"now": "ahora", "ahora": "now"}},
            {"en": "We (f) are going to sleep soon.", "es": "Nosotras vamos a dormir pronto.", "noun_id": None, "type": "auditory", "glosses": {"soon": "pronto", "pronto": "soon"}},
            {"en": "You all are going to sleep late.", "es": "Ustedes van a dormir tarde.", "noun_id": None, "type": "written", "glosses": {"late": "tarde", "tarde": "late"}},
            {"en": "I'm going to study Spanish.", "es": "Voy a estudiar español.", "noun_id": None, "type": "written", "glosses": {"Spanish": "español", "español": "Spanish"}},
            {"en": "You are going to study hard.", "es": "Vas a estudiar mucho.", "noun_id": None, "type": "auditory", "glosses": {"hard": "mucho", "mucho": "hard"}},
            {"en": "She is going to study tomorrow.", "es": "Ella va a estudiar mañana.", "noun_id": None, "type": "written", "glosses": {"tomorrow": "mañana", "mañana": "tomorrow"}},
            {"en": "We (f) are going to study together.", "es": "Nosotras vamos a estudiar juntas.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntas", "juntas": "together"}},
            {"en": "You all are going to study now.", "es": "Ustedes van a estudiar ahora.", "noun_id": None, "type": "written", "glosses": {"now": "ahora", "ahora": "now"}},
        ],
        "drill_targets": [{"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "ella"}, {"verb": "dormir", "pronoun": "nosotras"}, {"verb": "dormir", "pronoun": "ustedes"}, {"verb": "estudiar", "pronoun": "yo"}, {"verb": "estudiar", "pronoun": "tú"}, {"verb": "estudiar", "pronoun": "ella"}, {"verb": "estudiar", "pronoun": "nosotras"}, {"verb": "estudiar", "pronoun": "ustedes"}],
        "phase_2_config": {
            "description": "ir a + Infinitive dormir + estudiar (1/2): dormir, estudiar",
            "targets": [{"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "ella"}, {"verb": "dormir", "pronoun": "nosotras"}, {"verb": "dormir", "pronoun": "ustedes"}, {"verb": "estudiar", "pronoun": "yo"}, {"verb": "estudiar", "pronoun": "tú"}, {"verb": "estudiar", "pronoun": "ella"}, {"verb": "estudiar", "pronoun": "nosotras"}, {"verb": "estudiar", "pronoun": "ustedes"}],
        },
        "opener_en": "When are you going to sleep?",
        "opener_es": "¿Cuándo vas a dormir?",
    },

    "grammar_ir_a_inf_dormir_estudiar_2": {
        "title": "ir a + Infinitive — dormir + estudiar (2/2)",
        "grammar_level": 9,
        "lesson_number": 6,
        "lesson_type": "conjugation",
        "word_workload": ["dormir", "estudiar"],
        "video_embed_id": "geHPDI9tMdH",
        "drill_type": "ir_a_inf",
        "tense": "ir_a_infinitive",
        "rule_chart": IR_A_INF_RULE,
        "drill_config": {
            "answers": {
                "dormir": {"yo": "|voy a dormir", "tú": "|vas a dormir", "él": "|va a dormir", "ella": "|va a dormir", "usted": "|va a dormir", "nosotros": "|vamos a dormir", "nosotras": "|vamos a dormir", "ellos": "|van a dormir", "ellas": "|van a dormir", "ustedes": "|van a dormir"},
                "estudiar": {"yo": "|voy a estudiar", "tú": "|vas a estudiar", "él": "|va a estudiar", "ella": "|va a estudiar", "usted": "|va a estudiar", "nosotros": "|vamos a estudiar", "nosotras": "|vamos a estudiar", "ellos": "|van a estudiar", "ellas": "|van a estudiar", "ustedes": "|van a estudiar"},
            },
        },
        "phases": {"0a": False, "0b": True, "1a": False, "1b": False, "1c": False, "2": False, "3": False},
        "phase_1c_config": {"total_items": 5, "mode": "random_pronoun_verb"},
        "drill_sentences": [
            {"en": "You are going to sleep early.", "es": "Tú vas a dormir temprano.", "noun_id": None, "type": "written", "glosses": {"early": "temprano", "temprano": "early"}},
            {"en": "I am going to sleep now.", "es": "Yo voy a dormir ahora.", "noun_id": None, "type": "auditory", "glosses": {"now": "ahora", "ahora": "now"}},
            {"en": "He is going to sleep well.", "es": "Él va a dormir bien.", "noun_id": None, "type": "written", "glosses": {"well": "bien", "bien": "well"}},
            {"en": "We (m) are going to sleep at night.", "es": "Nosotros vamos a dormir por la noche.", "noun_id": None, "type": "auditory", "glosses": {"night": "noche", "noche": "night"}},
            {"en": "They (f) are going to sleep tired.", "es": "Ellas van a dormir cansadas.", "noun_id": None, "type": "written", "glosses": {"tired": "cansadas", "cansadas": "tired"}},
            {"en": "You are going to study the lesson.", "es": "Tú vas a estudiar la lección.", "noun_id": None, "type": "written", "glosses": {"lesson": "lección", "lección": "lesson"}},
            {"en": "I am going to study today.", "es": "Yo voy a estudiar hoy.", "noun_id": None, "type": "auditory", "glosses": {"today": "hoy", "hoy": "today"}},
            {"en": "He is going to study hard.", "es": "Él va a estudiar mucho.", "noun_id": None, "type": "written", "glosses": {"hard": "mucho", "mucho": "hard"}},
            {"en": "We (m) are going to study together.", "es": "Nosotros vamos a estudiar juntos.", "noun_id": None, "type": "auditory", "glosses": {"together": "juntos", "juntos": "together"}},
            {"en": "They (f) are going to study in the library.", "es": "Ellas van a estudiar en la biblioteca.", "noun_id": None, "type": "written", "glosses": {"library": "biblioteca", "biblioteca": "library"}},
        ],
        "drill_targets": [{"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "él"}, {"verb": "dormir", "pronoun": "nosotros"}, {"verb": "dormir", "pronoun": "ellas"}, {"verb": "estudiar", "pronoun": "tú"}, {"verb": "estudiar", "pronoun": "yo"}, {"verb": "estudiar", "pronoun": "él"}, {"verb": "estudiar", "pronoun": "nosotros"}, {"verb": "estudiar", "pronoun": "ellas"}],
        "phase_2_config": {
            "description": "ir a + Infinitive dormir + estudiar (2/2): dormir, estudiar",
            "targets": [{"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "él"}, {"verb": "dormir", "pronoun": "nosotros"}, {"verb": "dormir", "pronoun": "ellas"}, {"verb": "estudiar", "pronoun": "tú"}, {"verb": "estudiar", "pronoun": "yo"}, {"verb": "estudiar", "pronoun": "él"}, {"verb": "estudiar", "pronoun": "nosotros"}, {"verb": "estudiar", "pronoun": "ellas"}],
        },
        "opener_en": "What are you going to study?",
        "opener_es": "¿Qué vas a estudiar?",
    },

    "grammar_ir_a_inf_hablar_comer_chat": {
        "title": "ir a + Infinitive — hablar + comer Chat",
        "grammar_level": 9,
        "lesson_number": 2.5,
        "lesson_type": "conjugation",
        "word_workload": ["hablar", "comer"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "ir_a_infinitive",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "ir a + Infinitive hablar + comer chat: hablar, comer", "targets": [{"verb": "hablar", "pronoun": "yo"}, {"verb": "hablar", "pronoun": "tú"}, {"verb": "hablar", "pronoun": "ella"}, {"verb": "hablar", "pronoun": "nosotras"}, {"verb": "hablar", "pronoun": "ustedes"}, {"verb": "comer", "pronoun": "tú"}, {"verb": "comer", "pronoun": "yo"}, {"verb": "comer", "pronoun": "él"}, {"verb": "comer", "pronoun": "nosotros"}, {"verb": "comer", "pronoun": "ellas"}]},
    },

    "grammar_ir_a_inf_vivir_escribir_chat": {
        "title": "ir a + Infinitive — vivir + escribir Chat",
        "grammar_level": 9,
        "lesson_number": 4.5,
        "lesson_type": "conjugation",
        "word_workload": ["vivir", "escribir"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "ir_a_infinitive",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "ir a + Infinitive vivir + escribir chat: vivir, escribir", "targets": [{"verb": "vivir", "pronoun": "yo"}, {"verb": "vivir", "pronoun": "tú"}, {"verb": "vivir", "pronoun": "ella"}, {"verb": "vivir", "pronoun": "nosotras"}, {"verb": "vivir", "pronoun": "ustedes"}, {"verb": "escribir", "pronoun": "tú"}, {"verb": "escribir", "pronoun": "yo"}, {"verb": "escribir", "pronoun": "él"}, {"verb": "escribir", "pronoun": "nosotros"}, {"verb": "escribir", "pronoun": "ellas"}]},
    },

    "grammar_ir_a_inf_dormir_estudiar_chat": {
        "title": "ir a + Infinitive — dormir + estudiar Chat",
        "grammar_level": 9,
        "lesson_number": 6.5,
        "lesson_type": "conjugation",
        "word_workload": ["dormir", "estudiar"],
        "video_embed_id": None,
        "drill_type": "skip",
        "tense": "ir_a_infinitive",
        "phases": {"0a": False, "0b": False, "1a": False, "1b": False, "1c": False, "2": True, "3": False},
        "drill_sentences": [],
        "phase_2_config": {"description": "ir a + Infinitive dormir + estudiar chat: dormir, estudiar", "targets": [{"verb": "dormir", "pronoun": "yo"}, {"verb": "dormir", "pronoun": "tú"}, {"verb": "dormir", "pronoun": "ella"}, {"verb": "dormir", "pronoun": "nosotras"}, {"verb": "dormir", "pronoun": "ustedes"}, {"verb": "estudiar", "pronoun": "tú"}, {"verb": "estudiar", "pronoun": "yo"}, {"verb": "estudiar", "pronoun": "él"}, {"verb": "estudiar", "pronoun": "nosotros"}, {"verb": "estudiar", "pronoun": "ellas"}]},
    },
