#!/usr/bin/env python3
"""Regenerate the English field for core_1..core_47 from the Spanish.

Earlier translations read like word-for-word renderings; this rewrites
them in natural conversational US English. Only touches the `en` field
of `core_*` entries — es/ca/sv stay as authored.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import httpx

from app.config import settings
from app.services.encounter_messages_generated import ENCOUNTER_MESSAGES

OUT_PATH = Path(__file__).resolve().parents[1] / "app" / "services" / "encounter_messages_generated.py"

SYSTEM = (
    "You translate short Spanish chat openers into natural conversational "
    "US English. Rules: casual tú-equivalent register; keep questions as "
    "questions; match length and energy; sound like something a native "
    "English speaker would actually say in conversation. AVOID literal or "
    "stilted phrasing — fix it if the Spanish lands awkwardly when "
    "rendered word-for-word. Return ONLY a JSON object mapping each id to "
    "the English string."
)


def render_python_source(messages: dict[str, dict[str, str]]) -> str:
    lines: list[str] = [
        '"""Auto-generated per-encounter initial messages (multi-language).',
        "",
        "Generated by scripts/translate_openers.py using GPT-4.1-mini.",
        f"Total: {len(messages)} situations x 4 languages.",
        '"""',
        "",
        "ENCOUNTER_MESSAGES: dict[str, dict[str, str]] = {",
    ]
    for sid, langs in messages.items():
        lines.append(f'    "{sid}": {{')
        for lang in ("en", "es", "ca", "sv"):
            if lang in langs:
                escaped = json.dumps(langs[lang], ensure_ascii=False)
                lines.append(f'        "{lang}": {escaped},')
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    es_by_id = {f"core_{n}": ENCOUNTER_MESSAGES[f"core_{n}"]["es"] for n in range(1, 48)}

    user_msg = (
        "Translate each Spanish opener below to natural conversational US "
        "English. Return JSON keyed by id, value = English string.\n\n"
        + json.dumps(es_by_id, ensure_ascii=False, indent=2)
    )
    resp = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {settings.openai_api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": "gpt-4.1-mini",
            "response_format": {"type": "json_object"},
            "messages": [
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": user_msg},
            ],
            "temperature": 0.4,
        },
        timeout=120,
    )
    resp.raise_for_status()
    new_en = json.loads(resp.json()["choices"][0]["message"]["content"])

    missing = set(es_by_id) - set(new_en)
    if missing:
        sys.exit(f"Translation missing ids: {sorted(missing)}")

    merged = dict(ENCOUNTER_MESSAGES)
    changed = 0
    for sid, en in new_en.items():
        if merged[sid]["en"] != en:
            changed += 1
        merged[sid] = {**merged[sid], "en": en}

    OUT_PATH.write_text(render_python_source(merged), encoding="utf-8")
    print(f"updated {changed}/{len(new_en)} core_* English entries")
    for sid in sorted(new_en, key=lambda s: int(s.split("_")[1])):
        print(f"  {sid}: {new_en[sid]}")


if __name__ == "__main__":
    main()
